# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/leap/bitmask/gui/ui/eip_status.ui'
#
# Created: Thu Sep 18 13:04:05 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_EIPStatus(object):
    def setupUi(self, EIPStatus):
        EIPStatus.setObjectName("EIPStatus")
        EIPStatus.resize(470, 157)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EIPStatus.sizePolicy().hasHeightForWidth())
        EIPStatus.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(EIPStatus)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnEipStartStop = QtGui.QPushButton(EIPStatus)
        self.btnEipStartStop.setObjectName("btnEipStartStop")
        self.gridLayout.addWidget(self.btnEipStartStop, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.label = QtGui.QLabel(EIPStatus)
        self.label.setMaximumSize(QtCore.QSize(32, 32))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/black/32/earth.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lblEIPStatus = QtGui.QLabel(EIPStatus)
        self.lblEIPStatus.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lblEIPStatus.setStyleSheet("color: rgb(80, 80, 80);")
        self.lblEIPStatus.setWordWrap(True)
        self.lblEIPStatus.setObjectName("lblEIPStatus")
        self.gridLayout.addWidget(self.lblEIPStatus, 3, 2, 1, 1)
        self.lblEIPMessage = QtGui.QLabel(EIPStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEIPMessage.sizePolicy().hasHeightForWidth())
        self.lblEIPMessage.setSizePolicy(sizePolicy)
        self.lblEIPMessage.setWordWrap(True)
        self.lblEIPMessage.setObjectName("lblEIPMessage")
        self.gridLayout.addWidget(self.lblEIPMessage, 0, 2, 1, 1)
        self.lblVPNStatusIcon = QtGui.QLabel(EIPStatus)
        self.lblVPNStatusIcon.setMaximumSize(QtCore.QSize(22, 22))
        self.lblVPNStatusIcon.setText("")
        self.lblVPNStatusIcon.setPixmap(QtGui.QPixmap(":/images/black/22/off.png"))
        self.lblVPNStatusIcon.setScaledContents(True)
        self.lblVPNStatusIcon.setObjectName("lblVPNStatusIcon")
        self.gridLayout.addWidget(self.lblVPNStatusIcon, 0, 6, 1, 1)
        self.eip_bandwidth = QtGui.QWidget(EIPStatus)
        self.eip_bandwidth.setObjectName("eip_bandwidth")
        self.horizontalLayout = QtGui.QHBoxLayout(self.eip_bandwidth)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eip_bandwidth_layout = QtGui.QHBoxLayout()
        self.eip_bandwidth_layout.setSpacing(4)
        self.eip_bandwidth_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.eip_bandwidth_layout.setObjectName("eip_bandwidth_layout")
        self.btnDownload = QtGui.QPushButton(self.eip_bandwidth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDownload.sizePolicy().hasHeightForWidth())
        self.btnDownload.setSizePolicy(sizePolicy)
        self.btnDownload.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDownload.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btnDownload.setCursor(QtCore.Qt.PointingHandCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/black/32/arrow-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDownload.setIcon(icon)
        self.btnDownload.setFlat(True)
        self.btnDownload.setObjectName("btnDownload")
        self.eip_bandwidth_layout.addWidget(self.btnDownload)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.eip_bandwidth_layout.addItem(spacerItem1)
        self.btnUpload = QtGui.QPushButton(self.eip_bandwidth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpload.sizePolicy().hasHeightForWidth())
        self.btnUpload.setSizePolicy(sizePolicy)
        self.btnUpload.setMinimumSize(QtCore.QSize(100, 0))
        self.btnUpload.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btnUpload.setCursor(QtCore.Qt.PointingHandCursor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/black/32/arrow-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpload.setIcon(icon1)
        self.btnUpload.setFlat(True)
        self.btnUpload.setObjectName("btnUpload")
        self.eip_bandwidth_layout.addWidget(self.btnUpload)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.eip_bandwidth_layout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.eip_bandwidth_layout)
        self.gridLayout.addWidget(self.eip_bandwidth, 2, 2, 1, 5)
        self.btnFwDown = QtGui.QPushButton(EIPStatus)
        self.btnFwDown.setObjectName("btnFwDown")
        self.gridLayout.addWidget(self.btnFwDown, 0, 4, 1, 1)
        self.lblGatewayCountryCode = QtGui.QLabel(EIPStatus)
        self.lblGatewayCountryCode.setText("")
        self.lblGatewayCountryCode.setObjectName("lblGatewayCountryCode")
        self.gridLayout.addWidget(self.lblGatewayCountryCode, 0, 1, 1, 1)
        self.btnEipCancel = QtGui.QPushButton(EIPStatus)
        self.btnEipCancel.setObjectName("btnEipCancel")
        self.gridLayout.addWidget(self.btnEipCancel, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(EIPStatus)
        QtCore.QMetaObject.connectSlotsByName(EIPStatus)

    def retranslateUi(self, EIPStatus):
        EIPStatus.setWindowTitle(QtGui.QApplication.translate("EIPStatus", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEipStartStop.setText(QtGui.QApplication.translate("EIPStatus", "Turn On", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEIPStatus.setText(QtGui.QApplication.translate("EIPStatus", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEIPMessage.setText(QtGui.QApplication.translate("EIPStatus", "Traffic is being routed in the clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownload.setText(QtGui.QApplication.translate("EIPStatus", "0.0 KB/s", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpload.setText(QtGui.QApplication.translate("EIPStatus", "0.0 KB/s", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwDown.setText(QtGui.QApplication.translate("EIPStatus", "Turn Off", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEipCancel.setText(QtGui.QApplication.translate("EIPStatus", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
import flags_rc
