INSTALLED_APPS = (
    'oauth_tokens',
    'taggit',
#    'odnoklassniki_places',
)

# OAUTH_TOKENS_ODNOKLASSNIKI_CLIENT_ID = 3430034
# OAUTH_TOKENS_ODNOKLASSNIKI_CLIENT_SECRET = 'b0FwzyKtO8QiQmgWQMTz'
# OAUTH_TOKENS_ODNOKLASSNIKI_SCOPE = ['ads,wall,photos,friends,stats']
# OAUTH_TOKENS_ODNOKLASSNIKI_USERNAME = '+919665223715'
# OAUTH_TOKENS_ODNOKLASSNIKI_PASSWORD = 'githubovich'
# OAUTH_TOKENS_ODNOKLASSNIKI_PHONE_END = '3715'