__version__ = "0.1.3"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "tal.yalon@gmail.com"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@infinigit.infinidat.com:/host/pystick.git'
__git_head_hash__ = 'a103d09f60d8c69252bbd1ed438e55b30ca43ee0'
__git_head_subject__ = 'Finished release v0.1.3.'
__git_head_message__ = ''
__git_dirty_diff__ = ''