__version__ = "0.2.8"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a3b99f586817efd08de30fcbcb01ac4b2996b4c3'
__git_head_subject__ = 'Finished release v0.2.8.'
__git_head_message__ = '* release/v0.2.8:\n  TRIVIAL attachmetns, footer and header\n  TRIVIAL fixing'
__git_dirty_diff__ = ''