# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bitnomon/res/main.ui'
#
# Created: Mon Feb  2 20:23:59 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(848, 675)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/128x128/bitnomon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_logo = QtGui.QLabel(self.centralwidget)
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout.addWidget(self.label_logo)
        self.group_basic = QtGui.QGroupBox(self.centralwidget)
        self.group_basic.setObjectName(_fromUtf8("group_basic"))
        self.gridLayout_2 = QtGui.QGridLayout(self.group_basic)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.group_basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.lBlocks = QtGui.QLabel(self.group_basic)
        self.lBlocks.setObjectName(_fromUtf8("lBlocks"))
        self.gridLayout_2.addWidget(self.lBlocks, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.group_basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.group_basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 1, 1, 1)
        self.lPooledTx = QtGui.QLabel(self.group_basic)
        self.lPooledTx.setObjectName(_fromUtf8("lPooledTx"))
        self.gridLayout_2.addWidget(self.lPooledTx, 2, 2, 1, 1)
        self.lConns = QtGui.QLabel(self.group_basic)
        self.lConns.setMinimumSize(QtCore.QSize(80, 0))
        self.lConns.setObjectName(_fromUtf8("lConns"))
        self.gridLayout_2.addWidget(self.lConns, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.group_basic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 3, 1, 1, 1)
        self.lDifficulty = QtGui.QLabel(self.group_basic)
        self.lDifficulty.setObjectName(_fromUtf8("lDifficulty"))
        self.gridLayout_2.addWidget(self.lDifficulty, 3, 2, 1, 1)
        self.horizontalLayout.addWidget(self.group_basic)
        self.group_traffic = QtGui.QGroupBox(self.centralwidget)
        self.group_traffic.setObjectName(_fromUtf8("group_traffic"))
        self.gridLayout = QtGui.QGridLayout(self.group_traffic)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.group_traffic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.lRecv1m = QtGui.QLabel(self.group_traffic)
        self.lRecv1m.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRecv1m.setObjectName(_fromUtf8("lRecv1m"))
        self.gridLayout.addWidget(self.lRecv1m, 3, 3, 1, 1)
        self.lSent10m = QtGui.QLabel(self.group_traffic)
        self.lSent10m.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lSent10m.setObjectName(_fromUtf8("lSent10m"))
        self.gridLayout.addWidget(self.lSent10m, 5, 4, 1, 1)
        self.lSent10s = QtGui.QLabel(self.group_traffic)
        self.lSent10s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lSent10s.setObjectName(_fromUtf8("lSent10s"))
        self.gridLayout.addWidget(self.lSent10s, 5, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.group_traffic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.group_traffic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.group_traffic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.lRecv10m = QtGui.QLabel(self.group_traffic)
        self.lRecv10m.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRecv10m.setObjectName(_fromUtf8("lRecv10m"))
        self.gridLayout.addWidget(self.lRecv10m, 3, 4, 1, 1)
        self.lSent1m = QtGui.QLabel(self.group_traffic)
        self.lSent1m.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lSent1m.setObjectName(_fromUtf8("lSent1m"))
        self.gridLayout.addWidget(self.lSent1m, 5, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.group_traffic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.group_traffic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lRecvTotal = QtGui.QLabel(self.group_traffic)
        self.lRecvTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRecvTotal.setObjectName(_fromUtf8("lRecvTotal"))
        self.gridLayout.addWidget(self.lRecvTotal, 3, 1, 1, 1)
        self.lSentTotal = QtGui.QLabel(self.group_traffic)
        self.lSentTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lSentTotal.setObjectName(_fromUtf8("lSentTotal"))
        self.gridLayout.addWidget(self.lSentTotal, 5, 1, 1, 1)
        self.lRecv10s = QtGui.QLabel(self.group_traffic)
        self.lRecv10s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRecv10s.setObjectName(_fromUtf8("lRecv10s"))
        self.gridLayout.addWidget(self.lRecv10s, 3, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(1, 80)
        self.gridLayout.setColumnMinimumWidth(2, 100)
        self.gridLayout.setColumnMinimumWidth(3, 100)
        self.gridLayout.setColumnMinimumWidth(4, 100)
        self.horizontalLayout.addWidget(self.group_traffic)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.memPoolPlotView = GraphicsView(self.centralwidget)
        self.memPoolPlotView.setObjectName(_fromUtf8("memPoolPlotView"))
        self.verticalLayout.addWidget(self.memPoolPlotView)
        self.networkPlotView = GraphicsView(self.centralwidget)
        self.networkPlotView.setObjectName(_fromUtf8("networkPlotView"))
        self.verticalLayout.addWidget(self.networkPlotView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_NetUnitBitSI = QtGui.QAction(MainWindow)
        self.action_NetUnitBitSI.setCheckable(True)
        self.action_NetUnitBitSI.setObjectName(_fromUtf8("action_NetUnitBitSI"))
        self.action_NetUnitByteSI = QtGui.QAction(MainWindow)
        self.action_NetUnitByteSI.setCheckable(True)
        self.action_NetUnitByteSI.setObjectName(_fromUtf8("action_NetUnitByteSI"))
        self.action_NetUnitByteBinary = QtGui.QAction(MainWindow)
        self.action_NetUnitByteBinary.setCheckable(True)
        self.action_NetUnitByteBinary.setObjectName(_fromUtf8("action_NetUnitByteBinary"))
        self.action_NetUnits = QtGui.QAction(MainWindow)
        self.action_NetUnits.setEnabled(False)
        self.action_NetUnits.setObjectName(_fromUtf8("action_NetUnits"))
        self.action_FullScreen = QtGui.QAction(MainWindow)
        self.action_FullScreen.setCheckable(True)
        self.action_FullScreen.setObjectName(_fromUtf8("action_FullScreen"))
        self.action_ResetZoom = QtGui.QAction(MainWindow)
        self.action_ResetZoom.setObjectName(_fromUtf8("action_ResetZoom"))
        self.action_StatusBar = QtGui.QAction(MainWindow)
        self.action_StatusBar.setCheckable(True)
        self.action_StatusBar.setChecked(True)
        self.action_StatusBar.setObjectName(_fromUtf8("action_StatusBar"))
        self.action_AboutQt = QtGui.QAction(MainWindow)
        self.action_AboutQt.setObjectName(_fromUtf8("action_AboutQt"))
        self.action_ClearTraffic = QtGui.QAction(MainWindow)
        self.action_ClearTraffic.setObjectName(_fromUtf8("action_ClearTraffic"))
        self.action_ShutDownQuit = QtGui.QAction(MainWindow)
        self.action_ShutDownQuit.setObjectName(_fromUtf8("action_ShutDownQuit"))
        self.action_ReloadConf = QtGui.QAction(MainWindow)
        self.action_ReloadConf.setObjectName(_fromUtf8("action_ReloadConf"))
        self.menu_File.addAction(self.action_ReloadConf)
        self.menu_File.addAction(self.action_ClearTraffic)
        self.menu_File.addAction(self.action_ShutDownQuit)
        self.menu_File.addAction(self.action_Quit)
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.action_AboutQt)
        self.menu_View.addAction(self.action_FullScreen)
        self.menu_View.addAction(self.action_StatusBar)
        self.menu_View.addAction(self.action_ResetZoom)
        self.menu_View.addAction(self.action_NetUnits)
        self.menu_View.addAction(self.action_NetUnitBitSI)
        self.menu_View.addAction(self.action_NetUnitByteSI)
        self.menu_View.addAction(self.action_NetUnitByteBinary)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.action_StatusBar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.statusBar.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Bitnomon", None))
        self.label_logo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Bitnomon</span><br/><img src=\":/icons/64x64/bitnomon.png\"/><br/><span style=\" font-size:8pt;\">by Jacob Welsh</span></p></body></html>", None))
        self.label_9.setToolTip(_translate("MainWindow", "Number of blocks in the best chain", None))
        self.label_9.setText(_translate("MainWindow", "Blocks", None))
        self.lBlocks.setText(_translate("MainWindow", "-", None))
        self.label_7.setToolTip(_translate("MainWindow", "Active peer connections to this node", None))
        self.label_7.setText(_translate("MainWindow", "Connections", None))
        self.label_8.setToolTip(_translate("MainWindow", "Transactions in the local memory pool", None))
        self.label_8.setText(_translate("MainWindow", "Pooled TX", None))
        self.lPooledTx.setText(_translate("MainWindow", "-", None))
        self.lConns.setText(_translate("MainWindow", "-", None))
        self.label_10.setToolTip(_translate("MainWindow", "Network difficulty", None))
        self.label_10.setText(_translate("MainWindow", "Difficulty", None))
        self.lDifficulty.setText(_translate("MainWindow", "-", None))
        self.group_traffic.setTitle(_translate("MainWindow", "Network Traffic", None))
        self.label_3.setToolTip(_translate("MainWindow", "Total data received/sent since node startup", None))
        self.label_3.setText(_translate("MainWindow", "Total", None))
        self.lRecv1m.setText(_translate("MainWindow", "-", None))
        self.lSent10m.setText(_translate("MainWindow", "-", None))
        self.lSent10s.setText(_translate("MainWindow", "-", None))
        self.label_6.setToolTip(_translate("MainWindow", "10-minute average", None))
        self.label_6.setText(_translate("MainWindow", "10m", None))
        self.label_4.setToolTip(_translate("MainWindow", "10-second average", None))
        self.label_4.setText(_translate("MainWindow", "10s", None))
        self.label_5.setToolTip(_translate("MainWindow", "One-minute average", None))
        self.label_5.setText(_translate("MainWindow", "1m", None))
        self.lRecv10m.setText(_translate("MainWindow", "-", None))
        self.lSent1m.setText(_translate("MainWindow", "-", None))
        self.label_2.setText(_translate("MainWindow", "Out", None))
        self.label.setText(_translate("MainWindow", "In", None))
        self.lRecvTotal.setText(_translate("MainWindow", "-", None))
        self.lSentTotal.setText(_translate("MainWindow", "-", None))
        self.lRecv10s.setText(_translate("MainWindow", "-", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_About.setText(_translate("MainWindow", "&About Bitnomon", None))
        self.action_NetUnitBitSI.setText(_translate("MainWindow", "Bits, SI (kb)", None))
        self.action_NetUnitByteSI.setText(_translate("MainWindow", "Bytes, SI (kB)", None))
        self.action_NetUnitByteBinary.setText(_translate("MainWindow", "Bytes, Binary (KiB)", None))
        self.action_NetUnits.setText(_translate("MainWindow", "Network Units", None))
        self.action_FullScreen.setText(_translate("MainWindow", "&Full Screen", None))
        self.action_FullScreen.setShortcut(_translate("MainWindow", "F11", None))
        self.action_ResetZoom.setText(_translate("MainWindow", "&Reset Zoom", None))
        self.action_ResetZoom.setShortcut(_translate("MainWindow", "Ctrl+0", None))
        self.action_StatusBar.setText(_translate("MainWindow", "&Status Bar", None))
        self.action_AboutQt.setText(_translate("MainWindow", "About &Qt", None))
        self.action_ClearTraffic.setText(_translate("MainWindow", "&Clear Traffic Data...", None))
        self.action_ClearTraffic.setToolTip(_translate("MainWindow", "Clear the long-term network traffic history", None))
        self.action_ShutDownQuit.setText(_translate("MainWindow", "&Shut Down Node and Quit...", None))
        self.action_ShutDownQuit.setToolTip(_translate("MainWindow", "Quit after telling the Bitcoin node to shut down", None))
        self.action_ReloadConf.setText(_translate("MainWindow", "&Reload Bitcoin Configuration", None))

from pyqtgraph import GraphicsView
from . import bitnomon_rc
