__version__ = "0.2.1"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.2.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'aaf5b89e91e5f3b51b994e5e57c536c9d318e1ef'
__git_head_subject__ = 'buildout.cfg: remove python-cjson from requirements'
__git_head_message__ = ''
__git_dirty_diff__ = ''