
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.0'
version_full = 'd66b23b896851ebd0682d2f2f4627b075262f962'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

