# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'growth_computation.ui'
#
# Created: Wed May 14 15:26:22 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GrowthComputationDlg(object):
    def setupUi(self, GrowthComputationDlg):
        GrowthComputationDlg.setObjectName(_fromUtf8("GrowthComputationDlg"))
        GrowthComputationDlg.resize(778, 571)
        self.verticalLayout_2 = QtGui.QVBoxLayout(GrowthComputationDlg)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(GrowthComputationDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.allImages = QtGui.QTreeView(self.groupBox_5)
        self.allImages.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.allImages.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.allImages.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.allImages.setIconSize(QtCore.QSize(64, 64))
        self.allImages.setObjectName(_fromUtf8("allImages"))
        self.gridLayout_2.addWidget(self.allImages, 1, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.addImages = QtGui.QPushButton(self.groupBox_5)
        self.addImages.setMinimumSize(QtCore.QSize(32, 32))
        self.addImages.setMaximumSize(QtCore.QSize(32, 32))
        self.addImages.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImages.setIcon(icon)
        self.addImages.setIconSize(QtCore.QSize(32, 32))
        self.addImages.setObjectName(_fromUtf8("addImages"))
        self.verticalLayout_3.addWidget(self.addImages)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.removeImages = QtGui.QPushButton(self.groupBox_5)
        self.removeImages.setMinimumSize(QtCore.QSize(32, 32))
        self.removeImages.setMaximumSize(QtCore.QSize(32, 32))
        self.removeImages.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeImages.setIcon(icon1)
        self.removeImages.setIconSize(QtCore.QSize(32, 32))
        self.removeImages.setObjectName(_fromUtf8("removeImages"))
        self.verticalLayout_3.addWidget(self.removeImages)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.selectedImages = QtGui.QTreeView(self.groupBox_5)
        self.selectedImages.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.selectedImages.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.selectedImages.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.selectedImages.setIconSize(QtCore.QSize(64, 64))
        self.selectedImages.setObjectName(_fromUtf8("selectedImages"))
        self.gridLayout_2.addWidget(self.selectedImages, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(GrowthComputationDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.samePoints = QtGui.QRadioButton(self.groupBox_2)
        self.samePoints.setObjectName(_fromUtf8("samePoints"))
        self.horizontalLayout_4.addWidget(self.samePoints)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.daughterCells = QtGui.QCheckBox(self.groupBox_2)
        self.daughterCells.setChecked(True)
        self.daughterCells.setObjectName(_fromUtf8("daughterCells"))
        self.horizontalLayout_4.addWidget(self.daughterCells)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.allCells = QtGui.QRadioButton(self.groupBox_2)
        self.allCells.setObjectName(_fromUtf8("allCells"))
        self.horizontalLayout_3.addWidget(self.allCells)
        self.frame = QtGui.QFrame(self.groupBox_2)
        self.frame.setEnabled(False)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.withVariation = QtGui.QCheckBox(self.frame)
        self.withVariation.setEnabled(False)
        self.withVariation.setObjectName(_fromUtf8("withVariation"))
        self.horizontalLayout_2.addWidget(self.withVariation)
        self.maxVariationAllCells = QtGui.QSpinBox(self.frame)
        self.maxVariationAllCells.setEnabled(False)
        self.maxVariationAllCells.setMinimum(0)
        self.maxVariationAllCells.setMaximum(200)
        self.maxVariationAllCells.setProperty("value", 30)
        self.maxVariationAllCells.setObjectName(_fromUtf8("maxVariationAllCells"))
        self.horizontalLayout_2.addWidget(self.maxVariationAllCells)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.frame)
        spacerItem4 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.addPoints = QtGui.QRadioButton(self.groupBox_2)
        self.addPoints.setChecked(True)
        self.addPoints.setObjectName(_fromUtf8("addPoints"))
        self.horizontalLayout_5.addWidget(self.addPoints)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.maxVariationAddPoints = QtGui.QSpinBox(self.groupBox_2)
        self.maxVariationAddPoints.setMinimum(0)
        self.maxVariationAddPoints.setMaximum(200)
        self.maxVariationAddPoints.setProperty("value", 30)
        self.maxVariationAddPoints.setObjectName(_fromUtf8("maxVariationAddPoints"))
        self.horizontalLayout_5.addWidget(self.maxVariationAddPoints)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem5 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(GrowthComputationDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.forwardMethod = QtGui.QRadioButton(self.groupBox)
        self.forwardMethod.setStatusTip(_fromUtf8(""))
        self.forwardMethod.setChecked(True)
        self.forwardMethod.setObjectName(_fromUtf8("forwardMethod"))
        self.gridLayout.addWidget(self.forwardMethod, 0, 0, 1, 1)
        self.backwardMethod = QtGui.QRadioButton(self.groupBox)
        self.backwardMethod.setStatusTip(_fromUtf8(""))
        self.backwardMethod.setChecked(False)
        self.backwardMethod.setObjectName(_fromUtf8("backwardMethod"))
        self.gridLayout.addWidget(self.backwardMethod, 0, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        self.samplingPoints = QtGui.QSpinBox(self.groupBox)
        self.samplingPoints.setEnabled(False)
        self.samplingPoints.setMinimum(10)
        self.samplingPoints.setMaximum(5000)
        self.samplingPoints.setSingleStep(10)
        self.samplingPoints.setProperty("value", 100)
        self.samplingPoints.setObjectName(_fromUtf8("samplingPoints"))
        self.gridLayout.addWidget(self.samplingPoints, 1, 2, 1, 1)
        self.resample = QtGui.QCheckBox(self.groupBox)
        self.resample.setObjectName(_fromUtf8("resample"))
        self.gridLayout.addWidget(self.resample, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(GrowthComputationDlg)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.savePath = QtGui.QLineEdit(GrowthComputationDlg)
        self.savePath.setObjectName(_fromUtf8("savePath"))
        self.horizontalLayout.addWidget(self.savePath)
        self.chooseFile = QtGui.QPushButton(GrowthComputationDlg)
        self.chooseFile.setMaximumSize(QtCore.QSize(32, 16777215))
        self.chooseFile.setObjectName(_fromUtf8("chooseFile"))
        self.horizontalLayout.addWidget(self.chooseFile)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(GrowthComputationDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.actionSelect_even_images = QtGui.QAction(GrowthComputationDlg)
        self.actionSelect_even_images.setObjectName(_fromUtf8("actionSelect_even_images"))
        self.actionSelect_odd_images = QtGui.QAction(GrowthComputationDlg)
        self.actionSelect_odd_images.setObjectName(_fromUtf8("actionSelect_odd_images"))
        self.actionSelect_all_images = QtGui.QAction(GrowthComputationDlg)
        self.actionSelect_all_images.setObjectName(_fromUtf8("actionSelect_all_images"))
        self.actionSelect_no_image = QtGui.QAction(GrowthComputationDlg)
        self.actionSelect_no_image.setObjectName(_fromUtf8("actionSelect_no_image"))
        self.actionInvert_selection = QtGui.QAction(GrowthComputationDlg)
        self.actionInvert_selection.setObjectName(_fromUtf8("actionInvert_selection"))

        self.retranslateUi(GrowthComputationDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GrowthComputationDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GrowthComputationDlg.reject)
        QtCore.QObject.connect(self.addPoints, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_4.setEnabled)
        QtCore.QObject.connect(self.addPoints, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.maxVariationAddPoints.setEnabled)
        QtCore.QObject.connect(self.addPoints, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_5.setEnabled)
        QtCore.QObject.connect(self.withVariation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.maxVariationAllCells.setEnabled)
        QtCore.QObject.connect(self.withVariation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_2.setEnabled)
        QtCore.QObject.connect(self.allCells, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.withVariation.setEnabled)
        QtCore.QObject.connect(self.allCells, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QObject.connect(self.resample, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.samplingPoints.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GrowthComputationDlg)

    def retranslateUi(self, GrowthComputationDlg):
        GrowthComputationDlg.setWindowTitle(_translate("GrowthComputationDlg", "Dialog", None))
        self.groupBox_5.setTitle(_translate("GrowthComputationDlg", "Images selection", None))
        self.label_10.setText(_translate("GrowthComputationDlg", "Available images", None))
        self.label_11.setText(_translate("GrowthComputationDlg", "Selected images", None))
        self.groupBox_2.setToolTip(_translate("GrowthComputationDlg", "Criteria under which a cell growth will be computed or not.", None))
        self.groupBox_2.setTitle(_translate("GrowthComputationDlg", "Cell selection", None))
        self.samePoints.setText(_translate("GrowthComputationDlg", "Full cells only", None))
        self.daughterCells.setText(_translate("GrowthComputationDlg", "Include daughter cells", None))
        self.allCells.setText(_translate("GrowthComputationDlg", "All cells", None))
        self.withVariation.setText(_translate("GrowthComputationDlg", "with", None))
        self.maxVariationAllCells.setSuffix(_translate("GrowthComputationDlg", "%", None))
        self.label_2.setText(_translate("GrowthComputationDlg", "area variation", None))
        self.addPoints.setText(_translate("GrowthComputationDlg", "Add points only", None))
        self.label_4.setText(_translate("GrowthComputationDlg", "with", None))
        self.maxVariationAddPoints.setSuffix(_translate("GrowthComputationDlg", "%", None))
        self.label_5.setText(_translate("GrowthComputationDlg", "area variation", None))
        self.groupBox.setTitle(_translate("GrowthComputationDlg", "Method", None))
        self.forwardMethod.setToolTip(_translate("GrowthComputationDlg", "Compute growth, placing the computation on the start image.", None))
        self.forwardMethod.setText(_translate("GrowthComputationDlg", "Forward", None))
        self.backwardMethod.setToolTip(_translate("GrowthComputationDlg", "Compute growth, placing the computation on the end image.", None))
        self.backwardMethod.setText(_translate("GrowthComputationDlg", "Backward", None))
        self.samplingPoints.setSuffix(_translate("GrowthComputationDlg", " points", None))
        self.resample.setToolTip(_translate("GrowthComputationDlg", "If checked, the contour of the cells are resampled, associating common vertices but trying to spread point all over on the start cell. Otherwise, only the corresponding vertices are used to compute growht.", None))
        self.resample.setText(_translate("GrowthComputationDlg", "Resample", None))
        self.label.setText(_translate("GrowthComputationDlg", "File to save:", None))
        self.chooseFile.setText(_translate("GrowthComputationDlg", "...", None))
        self.actionSelect_even_images.setText(_translate("GrowthComputationDlg", "Select even images", None))
        self.actionSelect_odd_images.setText(_translate("GrowthComputationDlg", "Select odd images", None))
        self.actionSelect_all_images.setText(_translate("GrowthComputationDlg", "Select all images", None))
        self.actionSelect_no_image.setText(_translate("GrowthComputationDlg", "Select no image", None))
        self.actionInvert_selection.setText(_translate("GrowthComputationDlg", "Invert selection", None))

from . import icons_rc
