# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plottingdlg.ui'
#
# Created: Wed May 14 15:26:23 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlottingDlg(object):
    def setupUi(self, PlottingDlg):
        PlottingDlg.setObjectName(_fromUtf8("PlottingDlg"))
        PlottingDlg.resize(701, 505)
        self.verticalLayout_4 = QtGui.QVBoxLayout(PlottingDlg)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setMargin(3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(PlottingDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.growthFile = QtGui.QLineEdit(self.groupBox)
        self.growthFile.setObjectName(_fromUtf8("growthFile"))
        self.horizontalLayout_9.addWidget(self.growthFile)
        self.selectGrowthFile = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectGrowthFile.sizePolicy().hasHeightForWidth())
        self.selectGrowthFile.setSizePolicy(sizePolicy)
        self.selectGrowthFile.setMinimumSize(QtCore.QSize(31, 31))
        self.selectGrowthFile.setMaximumSize(QtCore.QSize(31, 31))
        self.selectGrowthFile.setObjectName(_fromUtf8("selectGrowthFile"))
        self.horizontalLayout_9.addWidget(self.selectGrowthFile)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.outputBox = QtGui.QGroupBox(PlottingDlg)
        self.outputBox.setObjectName(_fromUtf8("outputBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.outputBox)
        self.gridLayout_3.setMargin(3)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.outputBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(-1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.filePrefix = QtGui.QLineEdit(self.outputBox)
        self.filePrefix.setObjectName(_fromUtf8("filePrefix"))
        self.horizontalLayout_7.addWidget(self.filePrefix)
        self.selectFilePrefix = QtGui.QPushButton(self.outputBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFilePrefix.sizePolicy().hasHeightForWidth())
        self.selectFilePrefix.setSizePolicy(sizePolicy)
        self.selectFilePrefix.setMinimumSize(QtCore.QSize(31, 31))
        self.selectFilePrefix.setMaximumSize(QtCore.QSize(31, 31))
        self.selectFilePrefix.setObjectName(_fromUtf8("selectFilePrefix"))
        self.horizontalLayout_7.addWidget(self.selectFilePrefix)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.outputBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.fileFormat = QtGui.QComboBox(self.outputBox)
        self.fileFormat.setObjectName(_fromUtf8("fileFormat"))
        self.gridLayout_3.addWidget(self.fileFormat, 1, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_11 = QtGui.QLabel(self.outputBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.overSampling = QtGui.QSpinBox(self.outputBox)
        self.overSampling.setMinimum(1)
        self.overSampling.setObjectName(_fromUtf8("overSampling"))
        self.gridLayout_2.addWidget(self.overSampling, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(138, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.outputBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.outputBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 4, 1, 1)
        self.crop_left = QtGui.QSpinBox(self.outputBox)
        self.crop_left.setEnabled(False)
        self.crop_left.setPrefix(_fromUtf8(""))
        self.crop_left.setMinimum(0)
        self.crop_left.setProperty("value", 0)
        self.crop_left.setObjectName(_fromUtf8("crop_left"))
        self.gridLayout_2.addWidget(self.crop_left, 0, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.outputBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 6, 1, 1)
        self.crop_top = QtGui.QSpinBox(self.outputBox)
        self.crop_top.setEnabled(False)
        self.crop_top.setPrefix(_fromUtf8(""))
        self.crop_top.setMinimum(0)
        self.crop_top.setProperty("value", 0)
        self.crop_top.setObjectName(_fromUtf8("crop_top"))
        self.gridLayout_2.addWidget(self.crop_top, 0, 7, 1, 1)
        self.resetCrop = QtGui.QPushButton(self.outputBox)
        self.resetCrop.setObjectName(_fromUtf8("resetCrop"))
        self.gridLayout_2.addWidget(self.resetCrop, 1, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.outputBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 1, 4, 1, 1)
        self.crop_width = QtGui.QSpinBox(self.outputBox)
        self.crop_width.setEnabled(False)
        self.crop_width.setPrefix(_fromUtf8(""))
        self.crop_width.setMinimum(0)
        self.crop_width.setMaximum(99999)
        self.crop_width.setProperty("value", 0)
        self.crop_width.setObjectName(_fromUtf8("crop_width"))
        self.gridLayout_2.addWidget(self.crop_width, 1, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.outputBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 1, 6, 1, 1)
        self.crop_height = QtGui.QSpinBox(self.outputBox)
        self.crop_height.setEnabled(False)
        self.crop_height.setPrefix(_fromUtf8(""))
        self.crop_height.setMinimum(0)
        self.crop_height.setMaximum(99999)
        self.crop_height.setProperty("value", 0)
        self.crop_height.setObjectName(_fromUtf8("crop_height"))
        self.gridLayout_2.addWidget(self.crop_height, 1, 7, 1, 1)
        self.endImagePlot = QtGui.QCheckBox(self.outputBox)
        self.endImagePlot.setEnabled(False)
        self.endImagePlot.setObjectName(_fromUtf8("endImagePlot"))
        self.gridLayout_2.addWidget(self.endImagePlot, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.outputBox)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pointsColoring = QtGui.QGroupBox(PlottingDlg)
        self.pointsColoring.setEnabled(False)
        self.pointsColoring.setObjectName(_fromUtf8("pointsColoring"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pointsColoring)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_10 = QtGui.QLabel(self.pointsColoring)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        self.pointColoring = QtGui.QComboBox(self.pointsColoring)
        self.pointColoring.setObjectName(_fromUtf8("pointColoring"))
        self.horizontalLayout_6.addWidget(self.pointColoring)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.pointsColoring)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.pointSize = QtGui.QDoubleSpinBox(self.pointsColoring)
        self.pointSize.setObjectName(_fromUtf8("pointSize"))
        self.horizontalLayout_5.addWidget(self.pointSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.PointConfigWidget = QtGui.QWidget(self.pointsColoring)
        self.PointConfigWidget.setObjectName(_fromUtf8("PointConfigWidget"))
        self.verticalLayout_3.addWidget(self.PointConfigWidget)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_8.addWidget(self.pointsColoring)
        self.wallsColoring = QtGui.QGroupBox(PlottingDlg)
        self.wallsColoring.setEnabled(False)
        self.wallsColoring.setObjectName(_fromUtf8("wallsColoring"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wallsColoring)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.wallsColoring)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.wallColoring = QtGui.QComboBox(self.wallsColoring)
        self.wallColoring.setObjectName(_fromUtf8("wallColoring"))
        self.horizontalLayout_4.addWidget(self.wallColoring)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_18 = QtGui.QLabel(self.wallsColoring)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.wallThickness = QtGui.QDoubleSpinBox(self.wallsColoring)
        self.wallThickness.setObjectName(_fromUtf8("wallThickness"))
        self.horizontalLayout.addWidget(self.wallThickness)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.WallConfigWidget = QtGui.QWidget(self.wallsColoring)
        self.WallConfigWidget.setObjectName(_fromUtf8("WallConfigWidget"))
        self.verticalLayout_2.addWidget(self.WallConfigWidget)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_8.addWidget(self.wallsColoring)
        self.cellsColoring = QtGui.QGroupBox(PlottingDlg)
        self.cellsColoring.setEnabled(False)
        self.cellsColoring.setObjectName(_fromUtf8("cellsColoring"))
        self.verticalLayout = QtGui.QVBoxLayout(self.cellsColoring)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.plotEllipsis = QtGui.QCheckBox(self.cellsColoring)
        self.plotEllipsis.setChecked(False)
        self.plotEllipsis.setObjectName(_fromUtf8("plotEllipsis"))
        self.verticalLayout.addWidget(self.plotEllipsis)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.cellsColoring)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.cellColoring = QtGui.QComboBox(self.cellsColoring)
        self.cellColoring.setObjectName(_fromUtf8("cellColoring"))
        self.horizontalLayout_3.addWidget(self.cellColoring)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.CellConfigWidget = QtGui.QWidget(self.cellsColoring)
        self.CellConfigWidget.setObjectName(_fromUtf8("CellConfigWidget"))
        self.verticalLayout.addWidget(self.CellConfigWidget)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_8.addWidget(self.cellsColoring)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.buttonBox = QtGui.QDialogButtonBox(PlottingDlg)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(PlottingDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PlottingDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PlottingDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(PlottingDlg)

    def retranslateUi(self, PlottingDlg):
        PlottingDlg.setWindowTitle(_translate("PlottingDlg", "Plotting Parameters", None))
        self.groupBox.setTitle(_translate("PlottingDlg", "Input", None))
        self.label_8.setText(_translate("PlottingDlg", "Growth file:", None))
        self.selectGrowthFile.setText(_translate("PlottingDlg", "...", None))
        self.outputBox.setTitle(_translate("PlottingDlg", "Output", None))
        self.label_7.setText(_translate("PlottingDlg", "Prefix:", None))
        self.selectFilePrefix.setText(_translate("PlottingDlg", "...", None))
        self.label_9.setText(_translate("PlottingDlg", "File format:", None))
        self.label_11.setText(_translate("PlottingDlg", "Oversampling", None))
        self.overSampling.setPrefix(_translate("PlottingDlg", "x ", None))
        self.label_12.setText(_translate("PlottingDlg", "Cropping:", None))
        self.label_14.setText(_translate("PlottingDlg", "x", None))
        self.crop_left.setSuffix(_translate("PlottingDlg", " px", None))
        self.label_13.setText(_translate("PlottingDlg", "y", None))
        self.crop_top.setSuffix(_translate("PlottingDlg", " px", None))
        self.resetCrop.setText(_translate("PlottingDlg", "Reset crop", None))
        self.label_15.setText(_translate("PlottingDlg", "w", None))
        self.crop_width.setSuffix(_translate("PlottingDlg", " px", None))
        self.label_16.setText(_translate("PlottingDlg", "h", None))
        self.crop_height.setSuffix(_translate("PlottingDlg", " px", None))
        self.endImagePlot.setToolTip(_translate("PlottingDlg", "Plot growth data on the end image rather than the start image.", None))
        self.endImagePlot.setText(_translate("PlottingDlg", "Plot on end image", None))
        self.pointsColoring.setTitle(_translate("PlottingDlg", "Point coloring", None))
        self.label_10.setText(_translate("PlottingDlg", "Coloring: ", None))
        self.label_2.setText(_translate("PlottingDlg", "Size", None))
        self.wallsColoring.setTitle(_translate("PlottingDlg", "Walls coloring", None))
        self.label_6.setText(_translate("PlottingDlg", "Coloring: ", None))
        self.label_18.setText(_translate("PlottingDlg", "Thickness", None))
        self.cellsColoring.setTitle(_translate("PlottingDlg", "Cells coloring", None))
        self.plotEllipsis.setText(_translate("PlottingDlg", "Plot growth tensor ellipsis", None))
        self.label_5.setText(_translate("PlottingDlg", "Coloring: ", None))

from . import icons_rc
