# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plottingoptionsdlg.ui'
#
# Created: Wed May 14 15:26:23 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlottingOptionsDlg(object):
    def setupUi(self, PlottingOptionsDlg):
        PlottingOptionsDlg.setObjectName(_fromUtf8("PlottingOptionsDlg"))
        PlottingOptionsDlg.resize(658, 292)
        self.gridLayout_4 = QtGui.QGridLayout(PlottingOptionsDlg)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox = QtGui.QGroupBox(PlottingOptionsDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scaleAxis = QtGui.QCheckBox(self.groupBox)
        self.scaleAxis.setChecked(True)
        self.scaleAxis.setObjectName(_fromUtf8("scaleAxis"))
        self.gridLayout_2.addWidget(self.scaleAxis, 0, 0, 1, 2)
        self.majorAxis = QtGui.QCheckBox(self.groupBox)
        self.majorAxis.setChecked(True)
        self.majorAxis.setObjectName(_fromUtf8("majorAxis"))
        self.gridLayout_2.addWidget(self.majorAxis, 1, 0, 1, 1)
        self.minorAxis = QtGui.QCheckBox(self.groupBox)
        self.minorAxis.setChecked(True)
        self.minorAxis.setObjectName(_fromUtf8("minorAxis"))
        self.gridLayout_2.addWidget(self.minorAxis, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.scalingFactor = QtGui.QDoubleSpinBox(self.groupBox)
        self.scalingFactor.setDecimals(3)
        self.scalingFactor.setMaximum(999999.99)
        self.scalingFactor.setObjectName(_fromUtf8("scalingFactor"))
        self.gridLayout_2.addWidget(self.scalingFactor, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.minAnisotropy = QtGui.QDoubleSpinBox(self.groupBox)
        self.minAnisotropy.setDecimals(3)
        self.minAnisotropy.setMaximum(1.0)
        self.minAnisotropy.setSingleStep(0.1)
        self.minAnisotropy.setProperty("value", 0.1)
        self.minAnisotropy.setObjectName(_fromUtf8("minAnisotropy"))
        self.gridLayout_2.addWidget(self.minAnisotropy, 4, 1, 1, 1)
        self.ellipsisThickness = QtGui.QDoubleSpinBox(self.groupBox)
        self.ellipsisThickness.setObjectName(_fromUtf8("ellipsisThickness"))
        self.gridLayout_2.addWidget(self.ellipsisThickness, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self._12 = QtGui.QHBoxLayout()
        self._12.setSpacing(6)
        self._12.setObjectName(_fromUtf8("_12"))
        self.ellipsisColor = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipsisColor.sizePolicy().hasHeightForWidth())
        self.ellipsisColor.setSizePolicy(sizePolicy)
        self.ellipsisColor.setMinimumSize(QtCore.QSize(31, 31))
        self.ellipsisColor.setMaximumSize(QtCore.QSize(31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ellipsisColor.setPalette(palette)
        self.ellipsisColor.setAutoFillBackground(True)
        self.ellipsisColor.setFrameShape(QtGui.QFrame.Box)
        self.ellipsisColor.setText(_fromUtf8(""))
        self.ellipsisColor.setMargin(0)
        self.ellipsisColor.setObjectName(_fromUtf8("ellipsisColor"))
        self._12.addWidget(self.ellipsisColor)
        self.selectEllipsisColor = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectEllipsisColor.sizePolicy().hasHeightForWidth())
        self.selectEllipsisColor.setSizePolicy(sizePolicy)
        self.selectEllipsisColor.setMinimumSize(QtCore.QSize(31, 31))
        self.selectEllipsisColor.setMaximumSize(QtCore.QSize(31, 31))
        self.selectEllipsisColor.setObjectName(_fromUtf8("selectEllipsisColor"))
        self._12.addWidget(self.selectEllipsisColor)
        self.gridLayout.addLayout(self._12, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self._11 = QtGui.QHBoxLayout()
        self._11.setSpacing(6)
        self._11.setObjectName(_fromUtf8("_11"))
        self.ellipsisNegativeColor = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipsisNegativeColor.sizePolicy().hasHeightForWidth())
        self.ellipsisNegativeColor.setSizePolicy(sizePolicy)
        self.ellipsisNegativeColor.setMinimumSize(QtCore.QSize(31, 31))
        self.ellipsisNegativeColor.setMaximumSize(QtCore.QSize(31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ellipsisNegativeColor.setPalette(palette)
        self.ellipsisNegativeColor.setAutoFillBackground(True)
        self.ellipsisNegativeColor.setFrameShape(QtGui.QFrame.Box)
        self.ellipsisNegativeColor.setText(_fromUtf8(""))
        self.ellipsisNegativeColor.setMargin(0)
        self.ellipsisNegativeColor.setObjectName(_fromUtf8("ellipsisNegativeColor"))
        self._11.addWidget(self.ellipsisNegativeColor)
        self.selectEllipsisNegativeColor = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectEllipsisNegativeColor.sizePolicy().hasHeightForWidth())
        self.selectEllipsisNegativeColor.setSizePolicy(sizePolicy)
        self.selectEllipsisNegativeColor.setMinimumSize(QtCore.QSize(31, 31))
        self.selectEllipsisNegativeColor.setMaximumSize(QtCore.QSize(31, 31))
        self.selectEllipsisNegativeColor.setObjectName(_fromUtf8("selectEllipsisNegativeColor"))
        self._11.addWidget(self.selectEllipsisNegativeColor)
        self.gridLayout.addLayout(self._11, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self._10 = QtGui.QHBoxLayout()
        self._10.setSpacing(6)
        self._10.setObjectName(_fromUtf8("_10"))
        self.ellipsisPositiveColor = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipsisPositiveColor.sizePolicy().hasHeightForWidth())
        self.ellipsisPositiveColor.setSizePolicy(sizePolicy)
        self.ellipsisPositiveColor.setMinimumSize(QtCore.QSize(31, 31))
        self.ellipsisPositiveColor.setMaximumSize(QtCore.QSize(31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ellipsisPositiveColor.setPalette(palette)
        self.ellipsisPositiveColor.setAutoFillBackground(True)
        self.ellipsisPositiveColor.setFrameShape(QtGui.QFrame.Box)
        self.ellipsisPositiveColor.setText(_fromUtf8(""))
        self.ellipsisPositiveColor.setMargin(0)
        self.ellipsisPositiveColor.setObjectName(_fromUtf8("ellipsisPositiveColor"))
        self._10.addWidget(self.ellipsisPositiveColor)
        self.selectEllipsisPositiveColor = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectEllipsisPositiveColor.sizePolicy().hasHeightForWidth())
        self.selectEllipsisPositiveColor.setSizePolicy(sizePolicy)
        self.selectEllipsisPositiveColor.setMinimumSize(QtCore.QSize(31, 31))
        self.selectEllipsisPositiveColor.setMaximumSize(QtCore.QSize(31, 31))
        self.selectEllipsisPositiveColor.setObjectName(_fromUtf8("selectEllipsisPositiveColor"))
        self._10.addWidget(self.selectEllipsisPositiveColor)
        self.gridLayout.addLayout(self._10, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(PlottingOptionsDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.pointLineThickness = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.pointLineThickness.setObjectName(_fromUtf8("pointLineThickness"))
        self.horizontalLayout_3.addWidget(self.pointLineThickness)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self._13 = QtGui.QHBoxLayout()
        self._13.setSpacing(6)
        self._13.setObjectName(_fromUtf8("_13"))
        self.pointLineColor = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointLineColor.sizePolicy().hasHeightForWidth())
        self.pointLineColor.setSizePolicy(sizePolicy)
        self.pointLineColor.setMinimumSize(QtCore.QSize(31, 31))
        self.pointLineColor.setMaximumSize(QtCore.QSize(31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pointLineColor.setPalette(palette)
        self.pointLineColor.setAutoFillBackground(True)
        self.pointLineColor.setFrameShape(QtGui.QFrame.Box)
        self.pointLineColor.setText(_fromUtf8(""))
        self.pointLineColor.setMargin(0)
        self.pointLineColor.setObjectName(_fromUtf8("pointLineColor"))
        self._13.addWidget(self.pointLineColor)
        self.selectPointLineColor = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPointLineColor.sizePolicy().hasHeightForWidth())
        self.selectPointLineColor.setSizePolicy(sizePolicy)
        self.selectPointLineColor.setMinimumSize(QtCore.QSize(31, 31))
        self.selectPointLineColor.setMaximumSize(QtCore.QSize(31, 31))
        self.selectPointLineColor.setObjectName(_fromUtf8("selectPointLineColor"))
        self._13.addWidget(self.selectPointLineColor)
        self.horizontalLayout_2.addLayout(self._13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 51, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(PlottingOptionsDlg)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.bgColor = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgColor.sizePolicy().hasHeightForWidth())
        self.bgColor.setSizePolicy(sizePolicy)
        self.bgColor.setMinimumSize(QtCore.QSize(31, 31))
        self.bgColor.setMaximumSize(QtCore.QSize(31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.bgColor.setPalette(palette)
        self.bgColor.setAutoFillBackground(True)
        self.bgColor.setFrameShape(QtGui.QFrame.Box)
        self.bgColor.setText(_fromUtf8(""))
        self.bgColor.setMargin(0)
        self.bgColor.setObjectName(_fromUtf8("bgColor"))
        self._2.addWidget(self.bgColor)
        self.selectBgColor = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBgColor.sizePolicy().hasHeightForWidth())
        self.selectBgColor.setSizePolicy(sizePolicy)
        self.selectBgColor.setMinimumSize(QtCore.QSize(31, 31))
        self.selectBgColor.setMaximumSize(QtCore.QSize(31, 31))
        self.selectBgColor.setObjectName(_fromUtf8("selectBgColor"))
        self._2.addWidget(self.selectBgColor)
        self.horizontalLayout.addLayout(self._2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PlottingOptionsDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(PlottingOptionsDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PlottingOptionsDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PlottingOptionsDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(PlottingOptionsDlg)

    def retranslateUi(self, PlottingOptionsDlg):
        PlottingOptionsDlg.setWindowTitle(_translate("PlottingOptionsDlg", "Plotting Options", None))
        self.groupBox.setTitle(_translate("PlottingOptionsDlg", "Growth Tensor Ellipses", None))
        self.scaleAxis.setText(_translate("PlottingOptionsDlg", "Scale axis", None))
        self.majorAxis.setText(_translate("PlottingOptionsDlg", "Major axis", None))
        self.minorAxis.setText(_translate("PlottingOptionsDlg", "Minor axis", None))
        self.label_10.setText(_translate("PlottingOptionsDlg", "Size", None))
        self.label_5.setText(_translate("PlottingOptionsDlg", "Line thickness", None))
        self.label_2.setToolTip(_translate("PlottingOptionsDlg", "Minimum anisotropy required to draw ellipsis axis.", None))
        self.label_2.setStatusTip(_translate("PlottingOptionsDlg", "Minimum anisotropy required to draw ellipsis axis.", None))
        self.label_2.setText(_translate("PlottingOptionsDlg", "Min. anisotropy", None))
        self.label.setText(_translate("PlottingOptionsDlg", "Ellipsis color", None))
        self.selectEllipsisColor.setText(_translate("PlottingOptionsDlg", "...", None))
        self.label_4.setText(_translate("PlottingOptionsDlg", "Negative color", None))
        self.selectEllipsisNegativeColor.setText(_translate("PlottingOptionsDlg", "...", None))
        self.label_3.setText(_translate("PlottingOptionsDlg", "Positive color", None))
        self.selectEllipsisPositiveColor.setText(_translate("PlottingOptionsDlg", "...", None))
        self.groupBox_2.setTitle(_translate("PlottingOptionsDlg", "Point Coloring", None))
        self.label_6.setText(_translate("PlottingOptionsDlg", "Line Thickness", None))
        self.label_7.setText(_translate("PlottingOptionsDlg", "Line Color", None))
        self.selectPointLineColor.setText(_translate("PlottingOptionsDlg", "...", None))
        self.groupBox_3.setTitle(_translate("PlottingOptionsDlg", "Global", None))
        self.label_17.setText(_translate("PlottingOptionsDlg", "Background", None))
        self.selectBgColor.setText(_translate("PlottingOptionsDlg", "...", None))

