# This file was auto-generated by zetup
#
# https://bitbucket.org/userzimmermann/zetup.py


try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


setup(
  
  setup_requires=[
    'zetup',
    'path.py>=7.0',
    'jinjatools>=0.1.4',
    'libarray-ptr>=0.10',
    
    
    ],
  use_zetup=True,
  
  )