options = (
    ('long-transaction-worker',
     {'type': 'yn',
      'default': True,
      'help': "set to True if a long transaction worker is to be run",
      'group': 'worker',
      'level': 1,
      }),
    ('worker-max-load',
     {'type': 'int',
      'default': 2,
      'help': "the maximum number of tasks simultaneously handled by the worker",
      'group': 'worker',
      'level': 2,
      }),
    ('worker-polling-period',
     {'type': 'int',
      'default': 7,
      'help': "the polling period for new tasks (in seconds) ",
      'group': 'worker',
      'level': 2,
      }),

    )
