# -*- coding: utf-8 -*-

musicals = ('Aida',
'Annie',
'Seussical the Musical',
'The King and I',
'Guys and Dolls',
'South Pacific',
'The Pirates of Penzance',
'Footloose',
'Beauty and the Beast',
'Damn Yankees',
'Jekyll and Hyde',
'Wonderful Town',
'Footloose',
'Oklahoma',
'The Music Man',
'Once Upon a Mattress',
'South Pacific',
'The Pirates of Penzance',
'Bye Bye Birdie',
'Joseph and the Amazing Technicolor Dreamcoat',
'Oliver',
'Crazy for You',
'West Side Story',
'My One and Only',
'Pippin',
'The Wizard of Oz',
'Anything Goes',
'Jesus Christ Superstar',
'Peter Pan',
'Leader of the Pack',
'Once on This Island',
'Singing in the Rain',
'Hello Dolly',
'The Sound of Music',
'My Fair Lady',
'Fiddler on the Roof',
'A Twentieth Century Celebration',
'The Wildest',
"You're a Good Man Charlie Brown",
'Gypsy',
'42nd Street',
'Good News',
'Children of Eden',
'The Wiz',
'Anything Goes',
'Cinderella',
'Kiss Me Kate')

