# -*- coding: utf-8 -*-


flowers = [{"common_name": "african corn lily", "botonical_name": "ixia", "meaning": ""},
{"common_name": "african lily", "botonical_name": "agapanthus", "meaning": "Secret Love, Love Letters."},
{"common_name": "alpine thistle", "botonical_name": "eryngium", "meaning": ""},
{"common_name": "amaryllis", "botonical_name": "hippeastrum", "meaning": "Pride, Timidity, Splendid Beauty"},
{"common_name": "amazon lily", "botonical_name": "eucharis", "meaning": ""},
{"common_name": "arum", "botonical_name": "zantedeschia", "meaning": ""},
{"common_name": "baby's breath", "botonical_name": "gypsophila", "meaning": "Innocence, Pure Heart"},
{"common_name": "balloon flower", "botonical_name": "platycodon", "meaning": ""},
{"common_name": "barberton daisy", "botonical_name": "gerbera", "meaning": ""},
{"common_name": "bee balm", "botonical_name": "monarda", "meaning": ""},
{"common_name": "bell flower", "botonical_name": "campanula", "meaning": ""},
{"common_name": "bells of Ireland", "botonical_name": "moluccella", "meaning": "Good Luck"},
{"common_name": "bergamot", "botonical_name": "monarda", "meaning": ""},
{"common_name": "bird of paradise", "botonical_name": "strelizia", "meaning": ""},
{"common_name": "bloom", "botonical_name": "chrysanthemum", "meaning": ""},
{"common_name": "blue throatwort", "botonical_name": "trachelium", "meaning": ""},
{"common_name": "bottlebrush", "botonical_name": "banksia", "meaning": ""},
{"common_name": "brodiaea", "botonical_name": "triteleia (syn)", "meaning": ""},
{"common_name": "broom", "botonical_name": "genista", "meaning": ""},
{"common_name": "calla lily", "botonical_name": "zantedeschia", "meaning": "Magnificent Beauty"},
{"common_name": "canterbury bells", "botonical_name": "campanula", "meaning": ""},
{"common_name": "carnation", "botonical_name": "dianthus", "meaning": "General - Fascination, Devoted LoveRed - Heartache, Admiration Pink - I'll never forget you, Woman's LoveWhite - Pure and Ardent Love, Innocence Yellow - Disappointment, Rejection, Disdain"},
{"common_name": "china aster", "botonical_name": "callistephus", "meaning": ""},
{"common_name": "chincerinchee", "botonical_name": "ornithogalum", "meaning": ""},
{"common_name": "chinese bellflower", "botonical_name": "platycodon", "meaning": ""},
{"common_name": "christmas rose", "botonical_name": "hellebore", "meaning": ""},
{"common_name": "Chrysanthemum", "botonical_name": "Dendranthema", "meaning": "General - Cheerfulness, Rest, Wonderful Friendship, Abundance and WealthRed - Love White - TruthYellow - Slighted Love"},
{"common_name": "cockscomb", "botonical_name": "celosia", "meaning": ""},
{"common_name": "columbine", "botonical_name": "aquilegia", "meaning": ""},
{"common_name": "coneflower", "botonical_name": "rudbeckia, echinacea", "meaning": ""},
{"common_name": "cornflower", "botonical_name": "centaurea", "meaning": ""},
{"common_name": "corsage orchid", "botonical_name": "cattleya", "meaning": ""},
{"common_name": "cosmos", "botonical_name": "cosmea (syn)", "meaning": ""},
{"common_name": "cuban lily", "botonical_name": "scilla", "meaning": ""},
{"common_name": "daffodil", "botonical_name": "narcissus", "meaning": "Regard, Respect, Formality, You're the only one, Unrequited Love"},
{"common_name": "delphinium", "botonical_name": "delphinium", "meaning": "An Open Heart, Flights of Fancy, Ardent Attachment"},
{"common_name": "dill", "botonical_name": "anethum", "meaning": ""},
{"common_name": "drumstick", "botonical_name": "craspedia", "meaning": ""},
{"common_name": "eucharis lily", "botonical_name": "eucharis", "meaning": "Maiden Charms"},
{"common_name": "eustoma", "botonical_name": "lisianthus (syn)", "meaning": ""},
{"common_name": "evening primrose", "botonical_name": "oenothera", "meaning": ""},
{"common_name": "false goat's beard, false spirea", "botonical_name": "astilbe", "meaning": "Waiting"},
{"common_name": "feverfew", "botonical_name": "tanacetum parthenium", "meaning": ""},
{"common_name": "flame lily", "botonical_name": "gloriosa", "meaning": ""},
{"common_name": "flame tip", "botonical_name": "leucadendron", "meaning": ""},
{"common_name": "flamingo flower", "botonical_name": "anthurium", "meaning": ""},
{"common_name": "florist's nighmare", "botonical_name": "ornithogalum", "meaning": ""},
{"common_name": "floss flower", "botonical_name": "ageratum", "meaning": ""},
{"common_name": "flowering cherry", "botonical_name": "prunus", "meaning": ""},
{"common_name": "flowering onion", "botonical_name": "allium", "meaning": ""},
{"common_name": "forget-me-not", "botonical_name": "myosotis", "meaning": ""},
{"common_name": "foxglove", "botonical_name": "digitalis", "meaning": ""},
{"common_name": "foxtail lily", "botonical_name": "eremurus", "meaning": "Fidelity"},
{"common_name": "freesia", "botonical_name": "freesia", "meaning": "Innocence, Trust, Friendship"},
{"common_name": "gay feather", "botonical_name": "liatris", "meaning": ""},
{"common_name": "gentian", "botonical_name": "gentiana", "meaning": ""},
{"common_name": "gillyflower", "botonical_name": "matthiola", "meaning": ""},
{"common_name": "ginger", "botonical_name": "alpinia", "meaning": ""},
{"common_name": "globe amarath", "botonical_name": "gomphrena", "meaning": ""},
{"common_name": "globe artichoke", "botonical_name": "cynara", "meaning": ""},
{"common_name": "globe flower", "botonical_name": "trollius", "meaning": ""},
{"common_name": "globe thistle", "botonical_name": "echinops", "meaning": ""},
{"common_name": "glory lily", "botonical_name": "gloriosa", "meaning": ""},
{"common_name": "golden rod", "botonical_name": "solidago", "meaning": "Success"},
{"common_name": "golden shower orchid", "botonical_name": "oncidium", "meaning": ""},
{"common_name": "goosefoot", "botonical_name": "chenpodium", "meaning": ""},
{"common_name": "grape hyacinth", "botonical_name": "muscari", "meaning": ""},
{"common_name": "guelder rose", "botonical_name": "viburnum opulus", "meaning": ""},
{"common_name": "guernsey lily", "botonical_name": "nerine", "meaning": ""},
{"common_name": "holly berry", "botonical_name": "ilex", "meaning": "Defense, Foresight, Domestic Happiness"},
{"common_name": "hyacinth", "botonical_name": "hyacinthus", "meaning": "Sport, Play, Constancy"},
{"common_name": "hydrangea", "botonical_name": "hydrangea", "meaning": "Thank you for understanding, Boastfulness"},
{"common_name": "iris", "botonical_name": "iris", "meaning": "Fleur de Lys - Emblem of France. Wisdom, Faith, Valour, Promise"},
{"common_name": "jersey lily", "botonical_name": "alstroemeria", "meaning": ""},
{"common_name": "kangaroo paw", "botonical_name": "anigozanthos", "meaning": ""},
{"common_name": "kansas feather", "botonical_name": "liatris", "meaning": ""},
{"common_name": "lady's mantle", "botonical_name": "alchemilla", "meaning": ""},
{"common_name": "lady's slipper orchid", "botonical_name": "paphiopedilum", "meaning": ""},
{"common_name": "Lantana", "botonical_name": "lantana camera", "meaning": ""},
{"common_name": "larkspur", "botonical_name": "delphinium consolida", "meaning": "Fickleness"},
{"common_name": "lavender", "botonical_name": "lavandula", "meaning": ""},
{"common_name": "lilac", "botonical_name": "syringa", "meaning": "Youthful Humility, First Affection of Love, First Emotion of Life, Purity, Modesty"},
{"common_name": "lily", "botonical_name": "lilium", "meaning": "Pride, Purity, Flirting"},
{"common_name": "lily of the valley", "botonical_name": "convallaria", "meaning": "Sweetness, Humility, Return of Happiness, Tears of the Virgin Mary"},
{"common_name": "lisianthus", "botonical_name": "eustoma", "meaning": ""},
{"common_name": "lobster claw", "botonical_name": "heliconia", "meaning": ""},
{"common_name": "loose strife", "botonical_name": "lysimachia", "meaning": ""},
{"common_name": "love lies bleeding", "botonical_name": "amaranthus", "meaning": "Immortality"},
{"common_name": "love-in-a-mist", "botonical_name": "nigella", "meaning": ""},
{"common_name": "lupin", "botonical_name": "lupinus", "meaning": ""},
{"common_name": "marguerite", "botonical_name": "chrysanthemum frutescens", "meaning": ""},
{"common_name": "marigold", "botonical_name": "calendula", "meaning": ""},
{"common_name": "masterwort", "botonical_name": "astrantia", "meaning": ""},
{"common_name": "michaelmas daisy", "botonical_name": "aster", "meaning": ""},
{"common_name": "mimosa", "botonical_name": "acacia", "meaning": "Friendship, Secret Love, Beauty in Retirement"},
{"common_name": "monkshood", "botonical_name": "aconitum", "meaning": "Beware, Chivalry"},
{"common_name": "montbretia", "botonical_name": "crocosmia", "meaning": ""},
{"common_name": "moth orchid", "botonical_name": "phalenopsis", "meaning": ""},
{"common_name": "mum", "botonical_name": "chrysanthemum", "meaning": ""},
{"common_name": "obedient plant", "botonical_name": "physostegia", "meaning": ""},
{"common_name": "orchid", "botonical_name": "Phalaenopsis", "meaning": "Ecstasy, Love, Beauty, Refinement"},
{"common_name": "ox-eye daisy", "botonical_name": "leucanthemum vulgare aka chrysanthemum leucanthemum", "meaning": ""},
{"common_name": "painter's palette", "botonical_name": "anthurium", "meaning": ""},
{"common_name": "peony", "botonical_name": "paeonia", "meaning": "Bashfulness, Compassion, Happy Marriage, Prosperity"},
{"common_name": "peruvian lily", "botonical_name": "alstroemeria", "meaning": "Devotion, Wealth, Prosperity, Fortune."},
{"common_name": "pincushion protea", "botonical_name": "leucospermum", "meaning": ""},
{"common_name": "plumed thistle", "botonical_name": "cirsium", "meaning": ""},
{"common_name": "poppy", "botonical_name": "papaver", "meaning": "Eternal Sleep, Consolation, Pleasure, Wealth, Success, Imagination"},
{"common_name": "prairie gentian", "botonical_name": "lisianthus", "meaning": ""},
{"common_name": "prince of Wales feather", "botonical_name": "amaranthus", "meaning": ""},
{"common_name": "queen Anne's lace", "botonical_name": "ammi", "meaning": "Haven"},
{"common_name": "queen Fabiola lily", "botonical_name": "triteleia (syn brodiaea)", "meaning": ""},
{"common_name": "ranunculus", "botonical_name": "ranunculus", "meaning": "Radiant, Charming"},
{"common_name": "red-hot poker", "botonical_name": "kniphofia", "meaning": ""},
{"common_name": "rose", "botonical_name": "rosa", "meaning": "General - LoveWhite - Charm, Innocence, Purity, SecrecyPink - Grace, Gladness, Thankfulness, Joy, Perfect Happiness, Admiration Yellow - Joy, FriendshipRed - Love, I Love You, Passion, Desire, Courage, RespectOrange - Fascination, PassionPeach - Enthusiasm, Desire"},
{"common_name": "safari sunset", "botonical_name": "leucadendron", "meaning": ""},
{"common_name": "safflower", "botonical_name": "carthamus", "meaning": ""},
{"common_name": "scabious", "botonical_name": "scabiosa", "meaning": ""},
{"common_name": "scarlet plume", "botonical_name": "euphorbia fulgens", "meaning": ""},
{"common_name": "scorpion orchid", "botonical_name": "aranthera", "meaning": ""},
{"common_name": "sea holly", "botonical_name": "eryngium", "meaning": ""},
{"common_name": "sea lavender", "botonical_name": "limonium", "meaning": ""},
{"common_name": "september flower", "botonical_name": "aster", "meaning": "Innocence, Loyal Love, Daintiness, Gentleness, Purity, Variety."},
{"common_name": "singapore orchid", "botonical_name": "dendrobium", "meaning": "Refinement, Beautiful Lady"},
{"common_name": "slipper orchid", "botonical_name": "paphiopedilum", "meaning": ""},
{"common_name": "snake head", "botonical_name": "chelone", "meaning": ""},
{"common_name": "snapdragon", "botonical_name": "antirrhinum", "meaning": "Deception, Gracious Lady, Strength, Presumption"},
{"common_name": "sneezeweed", "botonical_name": "helenium", "meaning": ""},
{"common_name": "snow berry", "botonical_name": "symphoricarpos", "meaning": ""},
{"common_name": "snow on the mountain", "botonical_name": "eurphorbia marginata", "meaning": ""},
{"common_name": "speedwell", "botonical_name": "veronica", "meaning": ""},
{"common_name": "spider orchid", "botonical_name": "arachnis", "meaning": ""},
{"common_name": "spray carnation", "botonical_name": "dianthus", "meaning": ""},
{"common_name": "spurge", "botonical_name": "euphorbia", "meaning": ""},
{"common_name": "st john's wort", "botonical_name": "hypericum", "meaning": ""},
{"common_name": "star of bethlehem", "botonical_name": "ornithogalum", "meaning": "Purity"},
{"common_name": "statice", "botonical_name": "limonium", "meaning": ""},
{"common_name": "stock", "botonical_name": "matthiola", "meaning": "Lasting Beauty, Bond of Affection, Promptness"},
{"common_name": "stonecrop", "botonical_name": "sedum", "meaning": ""},
{"common_name": "sugarbush", "botonical_name": "protea", "meaning": ""},
{"common_name": "sunflower", "botonical_name": "helianthus", "meaning": "Adoration, Pride"},
{"common_name": "sweet pea", "botonical_name": "lathyrus", "meaning": "Lasting and Blissful Pleasure, Departure, Goodbye"},
{"common_name": "sweet sultan", "botonical_name": "centaurea", "meaning": ""},
{"common_name": "sweet William", "botonical_name": "dianthus barbatus", "meaning": "Gallantry"},
{"common_name": "sword lily", "botonical_name": "gladiolus", "meaning": "Strength of Character, Generosity, Sincerity"},
{"common_name": "tansy", "botonical_name": "tanacetum", "meaning": ""},
{"common_name": "tazetta", "botonical_name": "narcissus", "meaning": ""},
{"common_name": "thistle", "botonical_name": "eryngium", "meaning": ""},
{"common_name": "tjenkenrientjee", "botonical_name": "ornithogalum", "meaning": ""},
{"common_name": "transvaal daisy", "botonical_name": "gerbera", "meaning": ""},
{"common_name": "tuberose", "botonical_name": "polianthes tuberosa", "meaning": "Dangerous Pleasure"},
{"common_name": "tulip", "botonical_name": "tulipa", "meaning": "General - Love and Passion, Perfect Lover, Fame, LuckRed - Believe Me, Declaration of Love\nVariegated - Beautiful EyesYellow - Hopeless LoveViolet - Modesty"},
{"common_name": "buttercup", "botonical_name": "ranunculus", "meaning": ""},
{"common_name": "turtle head", "botonical_name": "chelone", "meaning": ""},
{"common_name": "ulster mary", "botonical_name": "alstroemeria", "meaning": ""},
{"common_name": "waxflower", "botonical_name": "chamaelaucium", "meaning": "Riches"},
{"common_name": "windflower", "botonical_name": "anemone", "meaning": "Forsaken, Sincerity, Expectations."},
{"common_name": "wormwood", "botonical_name": "artemesia", "meaning": ""},
{"common_name": "yarrow", "botonical_name": "achillea", "meaning": "Healing"}]

