add_edit_issues_and_relations = 'Add/edit issues and relations'
view_issue_dealer = 'View Issue Dealer'
manage_issue_dealer = 'Manage Issue Dealer'
publish_issues = 'Publish Issues'
edit_publishers = 'Edit Publishers'
