__version__ = "0.1.9"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.9)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a25a4f9ba6ede1314d051ef056cdf38253b45d2d'
__git_head_subject__ = 'Finished release v0.1.9.'
__git_head_message__ = '* release/v0.1.9:\n  HPT-1468 using repr() and not str() for items in sys.path\n  HPT-1468 adding a text for collecting Scripts'
__git_dirty_diff__ = ''