
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.65'
version_full = '18ce7591e1d20eb4a100c9a88418837e606dcd20'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

