RPT_COLUMN_META = {
    'age': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Patient age in years'},
    'ageday': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Patient age in days, if younger than one year'},
    'agemonth': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Patient age in months, if younger than eleven years'},
    'ahaid': {'category': 'HOSPITAL',
        'extract_by_default': False,
        'is_filter_option': False},
    'amonth': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True},
    'asource': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Admission source'},
    'ccsmgn1': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn2': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn3': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn4': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn5': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn6': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn7': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn8': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmgn9': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp1': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp2': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp3': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp4': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp5': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp6': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp7': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp8': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'ccsmsp9': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron1': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron10': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron11': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron12': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron13': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron14': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron15': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron16': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron17': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron18': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron19': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron2': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron20': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron21': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron22': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron23': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron24': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron25': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron3': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron4': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron5': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron6': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron7': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron8': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chron9': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb1': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb10': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb11': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb12': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb13': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb14': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb15': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb16': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb17': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb18': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb19': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb2': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb20': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb21': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb22': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb23': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb24': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb25': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb3': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb4': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb5': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb6': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb7': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb8': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'chronb9': {'category': 'CCI',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_aids': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_alcohol': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_anemdef': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_arth': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_bldloss': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_chf': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_chrnlung': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_coag': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_depress': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_dm': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_dmcx': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_drug': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_htn_c': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_hypothy': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_liver': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_lymph': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_lytes': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_mets': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_neuro': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_obese': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_para': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_perivasc': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_psych': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_pulmcirc': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_renlfail': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_tumor': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_ulcer': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_valve': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'cm_wghtloss': {'category': 'COMORBIDITY',
        'extract_by_default': False,
        'is_filter_option': False},
    'daystoevent': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': False,
        'label': 'Offset for linked visits'},
    'died': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Patient expired in hospital'},
    'dispub04': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Universal Bill 04 disposition'},
    'dispub92': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Universal Bill 92 disposition'},
    'drg': {'category': 'DX_EXTRA',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Diagnosis Related Group'},
    'drgver': {'category': 'DX_EXTRA',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'DRG version used on discharge'},
    'tran_in': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Transfer in flag'},
    'tran_out': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Transfer out flag'},
    'group_number': {
        'extract_by_default': False,
        'is_filter_option': True,
        'label': 'E.g., 1 for dx1 or pr1'},
    'dx': {'category': 'DX_BASIC',
        'is_filter_option': True,
        'label': 'Any diagnosis field'},
    'dx1': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Primary diagnosis'},
    'dx10': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx11': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx12': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx13': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx14': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx15': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx16': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx17': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx18': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx19': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx2': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx20': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx21': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx22': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx23': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx24': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx25': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx3': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx4': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx5': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx6': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx7': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx8': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dx9': {'category': 'DX_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'dxccs1': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs10': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs11': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs12': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs13': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs14': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs15': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs16': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs17': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs18': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs19': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs2': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs20': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs21': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs22': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs23': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs24': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs25': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs3': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs4': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs5': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs6': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs7': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs8': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxccs9': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs1': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs10': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs11': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs12': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs13': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs14': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs15': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs16': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs17': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs18': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs19': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs2': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs20': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs21': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs22': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs23': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs24': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs25': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs3': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs4': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs5': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs6': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs7': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs8': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxmccs9': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa1': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa10': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa11': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa12': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa13': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa14': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa15': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa16': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa17': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa18': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa19': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa2': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa20': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa21': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa22': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa23': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa24': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa25': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa3': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa4': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa5': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa6': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa7': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa8': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'dxpoa9': {'category': 'DX_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'e_mccs1': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'e_mccs2': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'e_mccs3': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'e_mccs4': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'e_mccs5': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'e_mccs6': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'eccsmgn1': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'eccsmgn2': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'eccsmgn3': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'eccsmgn4': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'eccsmgn5': {'category': 'CCS_MHSA',
        'extract_by_default': False,
        'is_filter_option': False},
    'female': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Sex; 1 for female, 0 for male'},
    'hospid': {'category': 'HOSPITAL',
        'extract_by_default': False,
        'is_filter_option': False,
        'label': 'Hospital ID assigned by HCUP'},
    'dshospid': {'category': 'HOSPITAL',
        'extract_by_default': False,
        'is_filter_option': False,
        'label': 'Hospital ID from data source'},
    'hospstco': {'category': 'HOSPITAL',
        'extract_by_default': False,
        'is_filter_option': False},
    'key': {'category': 'REC_ID',
        'extract_by_default': True,
        'is_filter_option': False,
        'label': 'Unique record ID'},
    'los': {'category': 'VISIT',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Length of stay in days'},
    'pay1': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Primary payer category'},
    'pay2': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Secondary payer category'},
    'pclass1': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass10': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass11': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass12': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass2': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass3': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass4': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass5': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass6': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass7': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass8': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pclass9': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pr1': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Primary procedure'},
    'pr10': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr11': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr12': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr13': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr14': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr15': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr16': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr17': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr18': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr19': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr2': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr20': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr21': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr22': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr23': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr24': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr25': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr3': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr4': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr5': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr6': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr7': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr8': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'pr9': {'category': 'PR_BASIC',
        'extract_by_default': True,
        'is_filter_option': False},
    'prccs1': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs10': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs11': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs12': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs13': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs14': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs15': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs16': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs17': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs18': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs19': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs2': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs20': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs21': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs22': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs23': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs24': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs25': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs3': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs4': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs5': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs6': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs7': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs8': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prccs9': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday1': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday10': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday11': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday12': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday13': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday14': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday15': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday16': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday17': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday18': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday19': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday2': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday20': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday21': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday22': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday23': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday24': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday25': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday3': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday4': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday5': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday6': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday7': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday8': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prday9': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs1': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs10': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs11': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs12': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs13': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs14': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs15': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs16': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs17': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs18': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs19': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs2': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs20': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs21': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs22': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs23': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs24': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs25': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs3': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs4': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs5': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs6': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs7': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs8': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmccs9': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth1': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth10': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth11': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth12': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth13': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth14': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth15': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth16': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth17': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth18': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth19': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth2': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth20': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth21': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth22': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth23': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth24': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth25': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth3': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth4': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth5': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth6': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth7': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth8': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'prmonth9': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear1': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear10': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear11': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear12': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear13': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear14': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear15': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear16': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear17': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear18': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear19': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear2': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear20': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear21': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear22': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear23': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear24': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear25': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear3': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear4': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear5': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear6': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear7': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear8': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'pryear9': {'category': 'PR_EXTRA',
        'extract_by_default': False,
        'is_filter_option': False},
    'race': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'Race and ethnicity, HCUP coding'},
    'state': {'category': 'REC_ID',
        'extract_by_default': True,
        'is_filter_option': True,
        'label': 'State or territory'},
    'u_blood': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_cath': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_ccu': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_chestxray': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_ctscan': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_dialysis': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_echo': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_ed': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_eeg': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_ekg': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_epo': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_icu': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_lithotripsy': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_mhsa': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_mrt': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_newbn2l': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_newbn3l': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_newbn4l': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_nucmed': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_observation': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_occtherapy': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_organacq': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_othimplants': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_pacemaker': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_phytherapy': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_radtherapy': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_resptherapy': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_speechtherapy': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_stress': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'u_ultrasound': {'category': 'UFLAG',
        'extract_by_default': False,
        'is_filter_option': False},
    'visitlink': {'category': 'REC_ID',
        'extract_by_default': True,
        'is_filter_option': False,
        'label': 'Patient in-state shared identifier'},
    'year': {'category': 'REC_ID',
        'extract_by_default': True,
        'is_filter_option': True},
    'zip': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True},
    'zip3': {'category': 'DEMO',
        'extract_by_default': True,
        'is_filter_option': True}
    }
