# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transferfunctiondlg.ui'
#
# Created: Wed May 14 15:26:23 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TransferFunctionDlg(object):
    def setupUi(self, TransferFunctionDlg):
        TransferFunctionDlg.setObjectName(_fromUtf8("TransferFunctionDlg"))
        TransferFunctionDlg.resize(793, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/palette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TransferFunctionDlg.setWindowIcon(icon)
        self.vboxlayout = QtGui.QVBoxLayout(TransferFunctionDlg)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.fctViewer = QTransferFunctionViewer(TransferFunctionDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fctViewer.sizePolicy().hasHeightForWidth())
        self.fctViewer.setSizePolicy(sizePolicy)
        self.fctViewer.setMinimumSize(QtCore.QSize(0, 100))
        self.fctViewer.setAutoFillBackground(True)
        self.fctViewer.setObjectName(_fromUtf8("fctViewer"))
        self.vboxlayout.addWidget(self.fctViewer)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.groupBox = QtGui.QGroupBox(TransferFunctionDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.useRGB = QtGui.QRadioButton(self.groupBox)
        self.useRGB.setChecked(False)
        self.useRGB.setObjectName(_fromUtf8("useRGB"))
        self.vboxlayout1.addWidget(self.useRGB)
        self.useHSV = QtGui.QRadioButton(self.groupBox)
        self.useHSV.setChecked(True)
        self.useHSV.setObjectName(_fromUtf8("useHSV"))
        self.vboxlayout1.addWidget(self.useHSV)
        self.useCyclicHSV = QtGui.QRadioButton(self.groupBox)
        self.useCyclicHSV.setObjectName(_fromUtf8("useCyclicHSV"))
        self.vboxlayout1.addWidget(self.useCyclicHSV)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.vboxlayout1.addItem(spacerItem)
        self.hboxlayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(TransferFunctionDlg)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(9)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.useChecks = QtGui.QRadioButton(self.groupBox_3)
        self.useChecks.setChecked(True)
        self.useChecks.setObjectName(_fromUtf8("useChecks"))
        self.vboxlayout2.addWidget(self.useChecks)
        self.useWhite = QtGui.QRadioButton(self.groupBox_3)
        self.useWhite.setObjectName(_fromUtf8("useWhite"))
        self.vboxlayout2.addWidget(self.useWhite)
        self.useBlack = QtGui.QRadioButton(self.groupBox_3)
        self.useBlack.setObjectName(_fromUtf8("useBlack"))
        self.vboxlayout2.addWidget(self.useBlack)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.vboxlayout2.addItem(spacerItem1)
        self.hboxlayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(TransferFunctionDlg)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridlayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridlayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.tickWidth = QtGui.QSpinBox(self.groupBox_4)
        self.tickWidth.setProperty("value", 5)
        self.tickWidth.setObjectName(_fromUtf8("tickWidth"))
        self.gridlayout.addWidget(self.tickWidth, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkSize = QtGui.QSpinBox(self.groupBox_4)
        self.checkSize.setProperty("value", 20)
        self.checkSize.setObjectName(_fromUtf8("checkSize"))
        self.gridlayout.addWidget(self.checkSize, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.selectionColor = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectionColor.sizePolicy().hasHeightForWidth())
        self.selectionColor.setSizePolicy(sizePolicy)
        self.selectionColor.setMinimumSize(QtCore.QSize(31, 31))
        self.selectionColor.setMaximumSize(QtCore.QSize(31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.selectionColor.setPalette(palette)
        self.selectionColor.setAutoFillBackground(True)
        self.selectionColor.setFrameShape(QtGui.QFrame.Box)
        self.selectionColor.setText(_fromUtf8(""))
        self.selectionColor.setMargin(0)
        self.selectionColor.setObjectName(_fromUtf8("selectionColor"))
        self.hboxlayout1.addWidget(self.selectionColor)
        self.selectSelectionColor = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSelectionColor.sizePolicy().hasHeightForWidth())
        self.selectSelectionColor.setSizePolicy(sizePolicy)
        self.selectSelectionColor.setMinimumSize(QtCore.QSize(31, 31))
        self.selectSelectionColor.setMaximumSize(QtCore.QSize(31, 31))
        self.selectSelectionColor.setObjectName(_fromUtf8("selectSelectionColor"))
        self.hboxlayout1.addWidget(self.selectSelectionColor)
        self.gridlayout.addLayout(self.hboxlayout1, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.hboxlayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(TransferFunctionDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setMargin(9)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        spacerItem4 = QtGui.QSpacerItem(163, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.vboxlayout3.addItem(spacerItem4)
        self.functionList = QtGui.QComboBox(self.groupBox_2)
        self.functionList.setEditable(True)
        self.functionList.setObjectName(_fromUtf8("functionList"))
        self.vboxlayout3.addWidget(self.functionList)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        spacerItem5 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem5)
        self.saveFunction = QtGui.QPushButton(self.groupBox_2)
        self.saveFunction.setObjectName(_fromUtf8("saveFunction"))
        self.hboxlayout2.addWidget(self.saveFunction)
        self.deleteFunction = QtGui.QPushButton(self.groupBox_2)
        self.deleteFunction.setObjectName(_fromUtf8("deleteFunction"))
        self.hboxlayout2.addWidget(self.deleteFunction)
        self.renameFunction = QtGui.QPushButton(self.groupBox_2)
        self.renameFunction.setObjectName(_fromUtf8("renameFunction"))
        self.hboxlayout2.addWidget(self.renameFunction)
        spacerItem6 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem6)
        self.vboxlayout3.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        spacerItem7 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem7)
        self.importFunction = QtGui.QPushButton(self.groupBox_2)
        self.importFunction.setObjectName(_fromUtf8("importFunction"))
        self.hboxlayout3.addWidget(self.importFunction)
        self.exportFunction = QtGui.QPushButton(self.groupBox_2)
        self.exportFunction.setObjectName(_fromUtf8("exportFunction"))
        self.hboxlayout3.addWidget(self.exportFunction)
        spacerItem8 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem8)
        self.vboxlayout3.addLayout(self.hboxlayout3)
        spacerItem9 = QtGui.QSpacerItem(163, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.vboxlayout3.addItem(spacerItem9)
        self.hboxlayout.addWidget(self.groupBox_2)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.buttonBox = QtGui.QDialogButtonBox(TransferFunctionDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(TransferFunctionDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TransferFunctionDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TransferFunctionDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(TransferFunctionDlg)

    def retranslateUi(self, TransferFunctionDlg):
        TransferFunctionDlg.setWindowTitle(_translate("TransferFunctionDlg", "Transfer function editor", None))
        self.groupBox.setTitle(_translate("TransferFunctionDlg", "Color space", None))
        self.useRGB.setText(_translate("TransferFunctionDlg", "RGB", None))
        self.useHSV.setText(_translate("TransferFunctionDlg", "HSV", None))
        self.useCyclicHSV.setText(_translate("TransferFunctionDlg", "Cyclic HSV", None))
        self.groupBox_3.setTitle(_translate("TransferFunctionDlg", "Background", None))
        self.useChecks.setText(_translate("TransferFunctionDlg", "Checks", None))
        self.useWhite.setText(_translate("TransferFunctionDlg", "White", None))
        self.useBlack.setText(_translate("TransferFunctionDlg", "Black", None))
        self.groupBox_4.setTitle(_translate("TransferFunctionDlg", "Interface", None))
        self.label.setText(_translate("TransferFunctionDlg", "Tick width", None))
        self.label_2.setText(_translate("TransferFunctionDlg", "Checks size", None))
        self.selectSelectionColor.setText(_translate("TransferFunctionDlg", "...", None))
        self.label_3.setText(_translate("TransferFunctionDlg", "Selection color", None))
        self.groupBox_2.setTitle(_translate("TransferFunctionDlg", "Predefined color maps", None))
        self.saveFunction.setText(_translate("TransferFunctionDlg", "Save", None))
        self.deleteFunction.setText(_translate("TransferFunctionDlg", "Delete", None))
        self.renameFunction.setText(_translate("TransferFunctionDlg", "Rename", None))
        self.importFunction.setText(_translate("TransferFunctionDlg", "Import", None))
        self.exportFunction.setText(_translate("TransferFunctionDlg", "Export", None))

from point_tracker.qtransferfunctionviewer import QTransferFunctionViewer
