__version__ = "0.1.37"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.37)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'b881064f0e6edff9c2a49ec3853f47499e1f7847'
__git_head_subject__ = 'HPT-1269 another fix'
__git_head_message__ = ''
__git_dirty_diff__ = ''