__version__ = "0.1.4"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'cd31486f90076003dc6f5181129041a0dec9b344'
__git_head_subject__ = 'Finished release v0.1.4.'
__git_head_message__ = '* release/v0.1.4:\n  HOSTDEV-1949 fixing previous commit\n  HOSTDEV-1949 removing the git hash from the version string'
__git_dirty_diff__ = ''