__version__ = "0.3.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '6512b75f3f8f2afabe0eabb57a70c1ba2705eb72'
__git_head_subject__ = 'STORAGEMODEL-323 POWER ON, RESET, OR BUS DEVICE RESET OCCURRED'
__git_head_message__ = ''
__git_dirty_diff__ = ''