# -*- coding: utf-8 -*-

# AUTOMATICALLY GENERATED FILE, DO NOT EDIT

tz_locations = {
    'Canada': u'Canada',
    'Asia': u'Asia',
    'America/Indiana/Tell_City': u'Tell City',
    'America/North_Dakota/New_Salem': u'New Salem',
    'Pacific': u'Pacific',
    'Indiana': u'Indiana',
    'Argentina': u'Argentina',
    'Europe': u'Europe',
    'Australia': u'Australia',
    'America/Indiana/Vevay': u'Vevay',
    'Arctic': u'Arctic',
    'America/Indiana/Marengo': u'Marengo',
    'America/Indiana/Vincennes': u'Vincennes',
    'Atlantic': u'Atlantic',
    'America/Indiana/Petersburg': u'Petersburg',
    'America/North_Dakota/Center': u'Center',
    'Kentucky': u'Kentucky',
    'America/Kentucky/Monticello': u'Monticello',
    'North_Dakota': u'North Dakota',
    'America/Indiana/Knox': u'Knox',
    'America/North_Dakota/Beulah': u'Beulah',
    'America': u'America',
    'Africa': u'Africa',
    'US': u'United States',
    'Antarctica': u'Antarctica',
    'Indian': u'Indian',
    'America/Indiana/Winamac': u'Winamac',
}

tz_cities = {
    'Atlantic/Canary': u'Canary',
    'Australia/Melbourne': u'Melbourne',
    'Europe/Lisbon': u'Lisbon',
    'America/Nipigon': u'Nipigon',
    'America/Miquelon': u'Miquelon',
    'Pacific/Wallis': u'Wallis',
    'Antarctica/Davis': u'Davis',
    'Atlantic/Stanley': u'Stanley',
    'Asia/Dhaka': u'Dhaka',
    'America/St_Lucia': u'St. Lucia',
    'America/Phoenix': u'Phoenix',
    'Asia/Kuwait': u'Kuwait',
    'Asia/Hong_Kong': u'Hong Kong',
    'Arctic/Longyearbyen': u'Longyearbyen',
    'Europe/Guernsey': u'Guernsey',
    'Europe/Paris': u'Paris',
    'Europe/Stockholm': u'Stockholm',
    'Pacific/Fiji': u'Fiji',
    'Pacific/Apia': u'Apia',
    'Pacific/Pago_Pago': u'Pago Pago',
    'Asia/Rangoon': u'Rangoon',
    'America/Mexico_City': u'Mexico City',
    'America/Puerto_Rico': u'Puerto Rico',
    'Indian/Mauritius': u'Mauritius',
    'Europe/Berlin': u'Berlin',
    'Europe/Zurich': u'Zurich',
    'Africa/Casablanca': u'Casablanca',
    'Antarctica/Macquarie': u'Macquarie Island',
    'Asia/Krasnoyarsk': u'Krasnoyarsk',
    'Atlantic/Bermuda': u'Bermuda',
    'America/Araguaina': u'Araguaina',
    'Asia/Tehran': u'Tehran',
    'Asia/Baku': u'Baku',
    'America/St_Barthelemy': u'St. Barthelemy',
    'America/Santarem': u'Santarem',
    'America/Danmarkshavn': u'Danmarkshavn',
    'America/Scoresbysund': u'Ittoqqortoormiit',
    'America/Eirunepe': u'Eirunepe',
    'America/St_Kitts': u'St. Kitts',
    'Asia/Baghdad': u'Baghdad',
    'Africa/Monrovia': u'Monrovia',
    'America/St_Vincent': u'St. Vincent',
    'America/Vancouver': u'Vancouver',
    'Asia/Ho_Chi_Minh': u'Ho Chi Minh',
    'Europe/Busingen': u'Busingen',
    'Asia/Thimphu': u'Thimphu',
    'Africa/Ouagadougou': u'Ouagadougou',
    'America/Belize': u'Belize',
    'America/Edmonton': u'Edmonton',
    'Asia/Tashkent': u'Tashkent',
    'Asia/Tokyo': u'Tokyo',
    'Pacific/Kiritimati': u'Kiritimati',
    'Australia/Sydney': u'Sydney',
    'Europe/Riga': u'Riga',
    'Asia/Dili': u'Dili',
    'Africa/Mbabane': u'Mbabane',
    'Asia/Oral': u'Oral',
    'Asia/Aden': u'Aden',
    'Europe/Isle_of_Man': u'Isle of Man',
    'Europe/Istanbul': u'Istanbul',
    'Africa/Abidjan': u'Abidjan',
    'Australia/Lindeman': u'Lindeman',
    'Pacific/Galapagos': u'Galapagos',
    'America/Bogota': u'Bogota',
    'Africa/Asmara': u'Asmara',
    'America/Chicago': u'Chicago',
    'Pacific/Kwajalein': u'Kwajalein',
    'Australia/Broken_Hill': u'Broken Hill',
    'America/Cuiaba': u'Cuiaba',
    'Indian/Christmas': u'Christmas',
    'Asia/Jayapura': u'Jayapura',
    'Europe/Brussels': u'Brussels',
    'America/Argentina/Cordoba': u'Cordoba',
    'Canada/Pacific': u'Pacific',
    'America/Noronha': u'Noronha',
    'Europe/Madrid': u'Madrid',
    'Africa/Algiers': u'Algiers',
    'Africa/Harare': u'Harare',
    'Africa/Ndjamena': u'Ndjamena',
    'America/Costa_Rica': u'Costa Rica',
    'Europe/Ljubljana': u'Ljubljana',
    'Indian/Mayotte': u'Mayotte',
    'Asia/Phnom_Penh': u'Phnom Penh',
    'America/Managua': u'Managua',
    'America/Pangnirtung': u'Pangnirtung',
    'America/Tijuana': u'Tijuana',
    'Pacific/Fakaofo': u'Fakaofo',
    'America/Adak': u'Adak',
    'America/Antigua': u'Antigua',
    'America/Indiana/Indianapolis': u'Indianapolis',
    'America/Argentina/La_Rioja': u'La Rioja',
    'Pacific/Tahiti': u'Tahiti',
    'Asia/Brunei': u'Brunei',
    'Europe/Zagreb': u'Zagreb',
    'America/Asuncion': u'Asuncion',
    'Europe/Vienna': u'Vienna',
    'Australia/Hobart': u'Hobart',
    'America/Juneau': u'Juneau',
    'America/Inuvik': u'Inuvik',
    'America/Ojinaga': u'Ojinaga',
    'America/Montreal': u'Montreal',
    'Asia/Seoul': u'Seoul',
    'Indian/Comoro': u'Comoro',
    'Antarctica/Rothera': u'Rothera',
    'Europe/Tallinn': u'Tallinn',
    'Indian/Mahe': u'Mahe',
    'America/Argentina/Jujuy': u'Jujuy',
    'America/Creston': u'Creston',
    'America/Martinique': u'Martinique',
    'Asia/Singapore': u'Singapore',
    'Africa/Nairobi': u'Nairobi',
    'America/Maceio': u'Maceio',
    'Africa/Cairo': u'Cairo',
    'Europe/Moscow': u'Moscow',
    'Antarctica/Palmer': u'Palmer',
    'Asia/Ulaanbaatar': u'Ulaanbaatar',
    'America/Rainy_River': u'Rainy River',
    'Africa/Kampala': u'Kampala',
    'Asia/Colombo': u'Colombo',
    'Australia/Adelaide': u'Adelaide',
    'America/Cambridge_Bay': u'Cambridge Bay',
    'Africa/Luanda': u'Luanda',
    'Pacific/Chatham': u'Chatham',
    'America/Indiana/Winamac': u'Winamac, Indiana',
    'Asia/Tbilisi': u'Tbilisi',
    'Europe/Gibraltar': u'Gibraltar',
    'Asia/Karachi': u'Karachi',
    'Australia/Lord_Howe': u'Lord Howe',
    'America/Bahia_Banderas': u'Bahia Banderas',
    'America/Boa_Vista': u'Boa Vista',
    'Africa/Tripoli': u'Tripoli',
    'Indian/Reunion': u'Reunion',
    'Canada/Mountain': u'Mountain',
    'Asia/Srednekolymsk': u'Srednekolymsk',
    'America/Blanc-Sablon': u'Blanc-Sablon',
    'America/Santo_Domingo': u'Santo Domingo',
    'Antarctica/Syowa': u'Syowa',
    'America/Jamaica': u'Jamaica',
    'Europe/Kiev': u'Kiev',
    'Europe/Budapest': u'Budapest',
    'Canada/Eastern': u'Eastern',
    'Pacific/Midway': u'Midway',
    'America/Goose_Bay': u'Goose Bay',
    'Asia/Amman': u'Amman',
    'Asia/Sakhalin': u'Sakhalin',
    'Africa/Windhoek': u'Windhoek',
    'America/Sitka': u'Sitka',
    'America/Guyana': u'Guyana',
    'Pacific/Pohnpei': u'Pohnpei',
    'America/Sao_Paulo': u'Sao Paulo',
    'America/Lower_Princes': u'Lower Prince’s Quarter',
    'Australia/Perth': u'Perth',
    'Africa/Djibouti': u'Djibouti',
    'Asia/Jakarta': u'Jakarta',
    'Asia/Pyongyang': u'Pyongyang',
    'Africa/Johannesburg': u'Johannesburg',
    'Antarctica/Troll': u'Troll',
    'Asia/Irkutsk': u'Irkutsk',
    'US/Pacific': u'Pacific',
    'Africa/Niamey': u'Niamey',
    'America/Belem': u'Belem',
    'America/Indiana/Marengo': u'Marengo, Indiana',
    'Africa/Nouakchott': u'Nouakchott',
    'Europe/Vilnius': u'Vilnius',
    'America/Cayenne': u'Cayenne',
    'Africa/Mogadishu': u'Mogadishu',
    'America/Kentucky/Monticello': u'Monticello, Kentucky',
    'America/Rio_Branco': u'Rio Branco',
    'America/Cancun': u'Cancun',
    'America/Havana': u'Havana',
    'Pacific/Guam': u'Guam',
    'Pacific/Kosrae': u'Kosrae',
    'Canada/Atlantic': u'Atlantic',
    'US/Arizona': u'Arizona',
    'Atlantic/Azores': u'Azores',
    'Australia/Eucla': u'Eucla',
    'Asia/Shanghai': u'Shanghai',
    'US/Alaska': u'Alaska',
    'America/Rankin_Inlet': u'Rankin Inlet',
    'America/Iqaluit': u'Iqaluit',
    'Africa/Maputo': u'Maputo',
    'Asia/Bahrain': u'Bahrain',
    'Asia/Ashgabat': u'Ashgabat',
    'Asia/Riyadh': u'Riyadh',
    'Europe/London': u'London',
    'America/Montevideo': u'Montevideo',
    'America/Anguilla': u'Anguilla',
    'Asia/Damascus': u'Damascus',
    'America/North_Dakota/Center': u'Center, North Dakota',
    'America/Indiana/Vevay': u'Vevay, Indiana',
    'Atlantic/St_Helena': u'St. Helena',
    'America/Barbados': u'Barbados',
    'Europe/Vatican': u'Vatican',
    'America/Indiana/Vincennes': u'Vincennes, Indiana',
    'Asia/Almaty': u'Almaty',
    'Africa/Lome': u'Lome',
    'Africa/Brazzaville': u'Brazzaville',
    'America/Nome': u'Nome',
    'Europe/Dublin': u'Dublin',
    'America/Yakutat': u'Yakutat',
    'America/Argentina/Mendoza': u'Mendoza',
    'America/Tortola': u'Tortola',
    'Europe/Vaduz': u'Vaduz',
    'Antarctica/Mawson': u'Mawson',
    'Asia/Kolkata': u'Kolkata',
    'Africa/Maseru': u'Maseru',
    'America/Atikokan': u'Atikokan',
    'America/Santa_Isabel': u'Santa Isabel',
    'Asia/Kuching': u'Kuching',
    'Africa/Libreville': u'Libreville',
    'Africa/Freetown': u'Freetown',
    'Africa/Bissau': u'Bissau',
    'Europe/Samara': u'Samara',
    'Europe/Amsterdam': u'Amsterdam',
    'Europe/Tirane': u'Tirane',
    'Pacific/Saipan': u'Saipan',
    'Asia/Magadan': u'Magadan',
    'Europe/Zaporozhye': u'Zaporozhye',
    'America/El_Salvador': u'El Salvador',
    'Europe/Podgorica': u'Podgorica',
    'Africa/Juba': u'Juba',
    'America/Santiago': u'Santiago',
    'America/Argentina/Buenos_Aires': u'Buenos Aires',
    'America/Argentina/San_Luis': u'San Luis',
    'Europe/Skopje': u'Skopje',
    'America/Aruba': u'Aruba',
    'America/Regina': u'Regina',
    'Pacific/Chuuk': u'Chuuk',
    'Asia/Khandyga': u'Khandyga',
    'Pacific/Funafuti': u'Funafuti',
    'America/Merida': u'Merida',
    'America/Guatemala': u'Guatemala',
    'Africa/Sao_Tome': u'Sao Tome',
    'Asia/Makassar': u'Makassar',
    'Africa/Bujumbura': u'Bujumbura',
    'Europe/Chisinau': u'Chisinau',
    'Europe/Warsaw': u'Warsaw',
    'Asia/Yekaterinburg': u'Yekaterinburg',
    'US/Hawaii': u'Hawaii',
    'Antarctica/Casey': u'Casey',
    'Pacific/Enderbury': u'Enderbury',
    'America/Thule': u'Thule',
    'America/St_Johns': u'St. John’s',
    'America/Moncton': u'Moncton',
    'Europe/Helsinki': u'Helsinki',
    'Atlantic/Cape_Verde': u'Cape Verde',
    'America/Tegucigalpa': u'Tegucigalpa',
    'Indian/Cocos': u'Cocos',
    'America/Boise': u'Boise',
    'America/Guadeloupe': u'Guadeloupe',
    'America/Nassau': u'Nassau',
    'Europe/Prague': u'Prague',
    'America/Halifax': u'Halifax',
    'Asia/Hovd': u'Hovd',
    'America/Manaus': u'Manaus',
    'America/Godthab': u'Nuuk',
    'America/North_Dakota/Beulah': u'Beulah, North Dakota',
    'America/Chihuahua': u'Chihuahua',
    'Asia/Beirut': u'Beirut',
    'America/Argentina/Rio_Gallegos': u'Rio Gallegos',
    'Pacific/Gambier': u'Gambier',
    'Europe/Volgograd': u'Volgograd',
    'Africa/Bamako': u'Bamako',
    'Asia/Novokuznetsk': u'Novokuznetsk',
    'Europe/Uzhgorod': u'Uzhgorod',
    'Africa/Banjul': u'Banjul',
    'Asia/Aqtau': u'Aqtau',
    'Africa/Malabo': u'Malabo',
    'Europe/Minsk': u'Minsk',
    'Atlantic/Madeira': u'Madeira',
    'Pacific/Noumea': u'Noumea',
    'Africa/Kinshasa': u'Kinshasa',
    'Europe/Malta': u'Malta',
    'America/Argentina/Ushuaia': u'Ushuaia',
    'Asia/Bangkok': u'Bangkok',
    'Pacific/Niue': u'Niue',
    'Australia/Brisbane': u'Brisbane',
    'America/Recife': u'Recife',
    'Asia/Yerevan': u'Yerevan',
    'America/La_Paz': u'La Paz',
    'Asia/Urumqi': u'Urumqi',
    'Africa/Lusaka': u'Lusaka',
    'Pacific/Guadalcanal': u'Guadalcanal',
    'America/Yellowknife': u'Yellowknife',
    'Canada/Newfoundland': u'Newfoundland',
    'Asia/Vientiane': u'Vientiane',
    'Europe/Kaliningrad': u'Kaliningrad',
    'Africa/Conakry': u'Conakry',
    'America/Argentina/Tucuman': u'Tucuman',
    'Asia/Chita': u'Chita',
    'Asia/Hebron': u'Hebron',
    'Europe/Oslo': u'Oslo',
    'Australia/Currie': u'Currie',
    'America/Caracas': u'Caracas',
    'America/Panama': u'Panama',
    'America/Hermosillo': u'Hermosillo',
    'Pacific/Palau': u'Palau',
    'America/Guayaquil': u'Guayaquil',
    'Asia/Kuala_Lumpur': u'Kuala Lumpur',
    'America/Menominee': u'Menominee',
    'Asia/Kamchatka': u'Kamchatka',
    'Asia/Vladivostok': u'Vladivostok',
    'America/Matamoros': u'Matamoros',
    'Asia/Qatar': u'Qatar',
    'Asia/Dubai': u'Dubai',
    'Asia/Yakutsk': u'Yakutsk',
    'Asia/Omsk': u'Omsk',
    'Africa/Bangui': u'Bangui',
    'UTC': u'UTC',
    'America/Paramaribo': u'Paramaribo',
    'Africa/Lubumbashi': u'Lubumbashi',
    'Pacific/Marquesas': u'Marquesas',
    'US/Central': u'Central',
    'Europe/Bratislava': u'Bratislava',
    'Asia/Anadyr': u'Anadyr',
    'America/New_York': u'New York',
    'Pacific/Norfolk': u'Norfolk',
    'Pacific/Rarotonga': u'Rarotonga',
    'America/Dominica': u'Dominica',
    'Africa/Porto-Novo': u'Porto-Novo',
    'Asia/Samarkand': u'Samarkand',
    'Asia/Dushanbe': u'Dushanbe',
    'America/Kentucky/Louisville': u'Louisville',
    'America/Toronto': u'Toronto',
    'America/Bahia': u'Bahia',
    'Indian/Maldives': u'Maldives',
    'Africa/Accra': u'Accra',
    'Asia/Muscat': u'Muscat',
    'America/Port_of_Spain': u'Port of Spain',
    'Pacific/Wake': u'Wake',
    'America/Indiana/Tell_City': u'Tell City, Indiana',
    'Australia/Darwin': u'Darwin',
    'America/Whitehorse': u'Whitehorse',
    'America/Swift_Current': u'Swift Current',
    'Europe/Copenhagen': u'Copenhagen',
    'America/Argentina/Salta': u'Salta',
    'America/Montserrat': u'Montserrat',
    'Europe/Simferopol': u'Simferopol',
    'Africa/Blantyre': u'Blantyre',
    'America/Detroit': u'Detroit',
    'America/Grenada': u'Grenada',
    'Atlantic/Faroe': u'Faroe',
    'America/Indiana/Petersburg': u'Petersburg, Indiana',
    'Asia/Kathmandu': u'Kathmandu',
    'Asia/Pontianak': u'Pontianak',
    'Europe/Athens': u'Athens',
    'America/Port-au-Prince': u'Port-au-Prince',
    'America/Cayman': u'Cayman',
    'Africa/Dar_es_Salaam': u'Dar es Salaam',
    'America/Curacao': u'Curacao',
    'Indian/Kerguelen': u'Kerguelen',
    'Africa/Khartoum': u'Khartoum',
    'Asia/Manila': u'Manila',
    'Europe/Sarajevo': u'Sarajevo',
    'Africa/Douala': u'Douala',
    'Europe/Rome': u'Rome',
    'America/Argentina/San_Juan': u'San Juan',
    'America/North_Dakota/New_Salem': u'New Salem, North Dakota',
    'America/Kralendijk': u'Kralendijk',
    'Pacific/Port_Moresby': u'Port Moresby',
    'Europe/Jersey': u'Jersey',
    'Europe/Andorra': u'Andorra',
    'Europe/Luxembourg': u'Luxembourg',
    'Pacific/Honolulu': u'Honolulu',
    'America/St_Thomas': u'St. Thomas',
    'Pacific/Majuro': u'Majuro',
    'America/Mazatlan': u'Mazatlan',
    'Asia/Macau': u'Macau',
    'Europe/Belgrade': u'Belgrade',
    'Asia/Choibalsan': u'Choibalsan',
    'Europe/Mariehamn': u'Mariehamn',
    'Antarctica/McMurdo': u'McMurdo',
    'America/Thunder_Bay': u'Thunder Bay',
    'America/Los_Angeles': u'Los Angeles',
    'Asia/Kabul': u'Kabul',
    'Indian/Antananarivo': u'Antananarivo',
    'Atlantic/Reykjavik': u'Reykjavik',
    'Asia/Nicosia': u'Nicosia',
    'Pacific/Tongatapu': u'Tongatapu',
    'America/Marigot': u'Marigot',
    'Pacific/Pitcairn': u'Pitcairn',
    'Pacific/Easter': u'Easter Island',
    'Atlantic/South_Georgia': u'South Georgia',
    'Africa/El_Aaiun': u'El Aaiun',
    'America/Campo_Grande': u'Campo Grande',
    'America/Dawson_Creek': u'Dawson Creek',
    'Antarctica/Vostok': u'Vostok',
    'Europe/Bucharest': u'Bucharest',
    'America/Porto_Velho': u'Porto Velho',
    'Europe/Monaco': u'Monaco',
    'Asia/Bishkek': u'Bishkek',
    'Africa/Ceuta': u'Ceuta',
    'America/Winnipeg': u'Winnipeg',
    'Asia/Aqtobe': u'Aqtobe',
    'Africa/Dakar': u'Dakar',
    'America/Fortaleza': u'Fortaleza',
    'Pacific/Tarawa': u'Tarawa',
    'America/Dawson': u'Dawson',
    'Africa/Addis_Ababa': u'Addis Ababa',
    'Pacific/Efate': u'Efate',
    'Pacific/Johnston': u'Johnston',
    'GMT': u'GMT',
    'Asia/Qyzylorda': u'Qyzylorda',
    'Europe/San_Marino': u'San Marino',
    'Asia/Jerusalem': u'Jerusalem',
    'Pacific/Auckland': u'Auckland',
    'America/Metlakatla': u'Metlakatla',
    'America/Denver': u'Denver',
    'Indian/Chagos': u'Chagos',
    'America/Glace_Bay': u'Glace Bay',
    'Pacific/Bougainville': u'Bougainville Island',
    'Africa/Gaborone': u'Gaborone',
    'Africa/Tunis': u'Tunis',
    'Asia/Ust-Nera': u'Ust-Nera',
    'America/Resolute': u'Resolute',
    'Asia/Gaza': u'Gaza',
    'Asia/Taipei': u'Taipei',
    'US/Mountain': u'Mountain',
    'Antarctica/DumontDUrville': u'Dumont d’Urville',
    'America/Argentina/Catamarca': u'Catamarca',
    'America/Indiana/Knox': u'Knox, Indiana',
    'Asia/Novosibirsk': u'Novosibirsk',
    'Africa/Kigali': u'Kigali',
    'US/Eastern': u'Eastern',
    'America/Grand_Turk': u'Grand Turk',
    'Canada/Central': u'Central',
    'Africa/Lagos': u'Lagos',
    'Europe/Sofia': u'Sofia',
    'America/Lima': u'Lima',
    'America/Anchorage': u'Anchorage',
    'America/Monterrey': u'Monterrey',
    'Pacific/Nauru': u'Nauru',
}

territories = {
    'BD': u'Bangladesh',
    'BE': u'Belgium',
    'BF': u'Burkina Faso',
    'BG': u'Bulgaria',
    'VE': u'Venezuela',
    'BA': u'Bosnia & Herzegovina',
    'BB': u'Barbados',
    'WF': u'Wallis & Futuna',
    'BL': u'St. Barthélemy',
    'BM': u'Bermuda',
    'BN': u'Brunei',
    'BO': u'Bolivia',
    'BH': u'Bahrain',
    'BI': u'Burundi',
    'BJ': u'Benin',
    'BT': u'Bhutan',
    '011': u'Western Africa',
    'BV': u'Bouvet Island',
    'BW': u'Botswana',
    '014': u'Eastern Africa',
    '015': u'Northern Africa',
    'BR': u'Brazil',
    '017': u'Middle Africa',
    '018': u'Southern Africa',
    '019': u'Americas',
    'BY': u'Belarus',
    'BZ': u'Belize',
    'LV': u'Latvia',
    'RW': u'Rwanda',
    'RS': u'Serbia',
    'TL': u'Timor-Leste',
    'RE': u'Réunion',
    'TM': u'Turkmenistan',
    'OM': u'Oman',
    'TJ': u'Tajikistan',
    'RO': u'Romania',
    'TK': u'Tokelau',
    'GW': u'Guinea-Bissau',
    'GU': u'Guam',
    'GT': u'Guatemala',
    'GS': u'South Georgia & South Sandwich Islands',
    'GR': u'Greece',
    'GQ': u'Equatorial Guinea',
    'GP': u'Guadeloupe',
    'JP': u'Japan',
    'KI': u'Kiribati',
    'GY': u'Guyana',
    'GG': u'Guernsey',
    'GF': u'French Guiana',
    'GE': u'Georgia',
    'GD': u'Grenada',
    '021': u'Northern America',
    'GB': u'United Kingdom',
    'GA': u'Gabon',
    'SV': u'El Salvador',
    'GN': u'Guinea',
    'GM': u'Gambia',
    'GL': u'Greenland',
    '029': u'Caribbean',
    'GI': u'Gibraltar',
    'GH': u'Ghana',
    'JE': u'Jersey',
    'TN': u'Tunisia',
    'JM': u'Jamaica',
    '013': u'Central America',
    'WS': u'Samoa',
    'TA': u'Tristan da Cunha',
    '419': u'Latin America',
    'BQ': u'Caribbean Netherlands',
    'HR': u'Croatia',
    'BS': u'Bahamas',
    'HT': u'Haiti',
    'HU': u'Hungary',
    'HK': u'Hong Kong SAR China',
    '039': u'Southern Europe',
    'HN': u'Honduras',
    'FI': u'Finland',
    '142': u'Asia',
    '030': u'Eastern Asia',
    '034': u'Southern Asia',
    '035': u'Southeast Asia',
    'PR': u'Puerto Rico',
    'PS': u'Palestinian Territories',
    'FK': u'Falkland Islands',
    'IO': u'British Indian Ocean Territory',
    'PW': u'Palau',
    'PT': u'Portugal',
    'SJ': u'Svalbard & Jan Mayen',
    'MD': u'Moldova',
    'IQ': u'Iraq',
    'PA': u'Panama',
    'PF': u'French Polynesia',
    'PG': u'Papua New Guinea',
    'PE': u'Peru',
    'PK': u'Pakistan',
    'PH': u'Philippines',
    'FO': u'Faroe Islands',
    'PN': u'Pitcairn Islands',
    'PL': u'Poland',
    'PM': u'St. Pierre & Miquelon',
    'ZM': u'Zambia',
    'EH': u'Western Sahara',
    'RU': u'Russia',
    'EE': u'Estonia',
    'EG': u'Egypt',
    'EA': u'Ceuta & Melilla',
    'ZA': u'South Africa',
    'EC': u'Ecuador',
    'IT': u'Italy',
    'VN': u'Vietnam',
    'ZZ': u'Unknown Region',
    'SB': u'Solomon Islands',
    'EU': u'European Union',
    'ET': u'Ethiopia',
    'SO': u'Somalia',
    'ZW': u'Zimbabwe',
    'SA': u'Saudi Arabia',
    'ES': u'Spain',
    'ER': u'Eritrea',
    'ME': u'Montenegro',
    'AQ': u'Antarctica',
    'MG': u'Madagascar',
    'MF': u'St. Martin',
    'MA': u'Morocco',
    'MC': u'Monaco',
    'UZ': u'Uzbekistan',
    'MM': u'Myanmar (Burma)',
    'ML': u'Mali',
    'MO': u'Macau SAR China',
    'MN': u'Mongolia',
    'HM': u'Heard & McDonald Islands',
    'AS': u'American Samoa',
    'MK': u'Macedonia',
    'MU': u'Mauritius',
    'MT': u'Malta',
    'MW': u'Malawi',
    'MV': u'Maldives',
    'MQ': u'Martinique',
    'MP': u'Northern Mariana Islands',
    'MS': u'Montserrat',
    'MR': u'Mauritania',
    'IM': u'Isle of Man',
    'UG': u'Uganda',
    'TZ': u'Tanzania',
    'MY': u'Malaysia',
    'MX': u'Mexico',
    'IL': u'Israel',
    'IC': u'Canary Islands',
    'FR': u'France',
    'AW': u'Aruba',
    'DO': u'Dominican Republic',
    'SH': u'St. Helena',
    'VC': u'St. Vincent & Grenadines',
    '054': u'Melanesia',
    'DJ': u'Djibouti',
    'FJ': u'Fiji',
    '057': u'Micronesian Region',
    'FM': u'Micronesia',
    '053': u'Australasia',
    'NI': u'Nicaragua',
    'NL': u'Netherlands',
    'NO': u'Norway',
    'NA': u'Namibia',
    'VU': u'Vanuatu',
    'NC': u'New Caledonia',
    'NE': u'Niger',
    'NF': u'Norfolk Island',
    'NG': u'Nigeria',
    'NZ': u'New Zealand',
    'NP': u'Nepal',
    'NR': u'Nauru',
    'NU': u'Niue',
    '061': u'Polynesia',
    'XK': u'Kosovo',
    'CI': u'Côte d’Ivoire',
    'CH': u'Switzerland',
    'CO': u'Colombia',
    'CN': u'China',
    'CM': u'Cameroon',
    'CL': u'Chile',
    'CC': u'Cocos (Keeling) Islands',
    'CA': u'Canada',
    'CG': u'Congo - Brazzaville',
    'CF': u'Central African Republic',
    'CD': u'Congo - Kinshasa',
    'CZ': u'Czech Republic',
    'CY': u'Cyprus',
    'CX': u'Christmas Island',
    'CR': u'Costa Rica',
    'PY': u'Paraguay',
    'CP': u'Clipperton Island',
    'CW': u'Curaçao',
    'CV': u'Cape Verde',
    'CU': u'Cuba',
    'SZ': u'Swaziland',
    'SY': u'Syria',
    'SX': u'Sint Maarten',
    'KG': u'Kyrgyzstan',
    'KE': u'Kenya',
    'SS': u'South Sudan',
    'SR': u'Suriname',
    '143': u'Central Asia',
    'KH': u'Cambodia',
    'KN': u'St. Kitts & Nevis',
    'KM': u'Comoros',
    'ST': u'São Tomé & Príncipe',
    'SK': u'Slovakia',
    'KR': u'South Korea',
    'SI': u'Slovenia',
    'KP': u'North Korea',
    'KW': u'Kuwait',
    'SN': u'Senegal',
    'SM': u'San Marino',
    'SL': u'Sierra Leone',
    'SC': u'Seychelles',
    'KZ': u'Kazakhstan',
    'KY': u'Cayman Islands',
    'SG': u'Singapore',
    'SE': u'Sweden',
    'SD': u'Sudan',
    '151': u'Eastern Europe',
    '150': u'Europe',
    'DM': u'Dominica',
    '155': u'Western Europe',
    '154': u'Northern Europe',
    'VG': u'British Virgin Islands',
    'DG': u'Diego Garcia',
    'DE': u'Germany',
    'YE': u'Yemen',
    'MH': u'Marshall Islands',
    'DZ': u'Algeria',
    'US': u'United States',
    'UY': u'Uruguay',
    'YT': u'Mayotte',
    'UM': u'U.S. Outlying Islands',
    'LB': u'Lebanon',
    'LC': u'St. Lucia',
    'LA': u'Laos',
    'TV': u'Tuvalu',
    'TW': u'Taiwan',
    'TT': u'Trinidad & Tobago',
    'TR': u'Turkey',
    'LK': u'Sri Lanka',
    'LI': u'Liechtenstein',
    'CK': u'Cook Islands',
    'TO': u'Tonga',
    'LT': u'Lithuania',
    'LU': u'Luxembourg',
    'LR': u'Liberia',
    'LS': u'Lesotho',
    'TH': u'Thailand',
    'TF': u'French Southern Territories',
    'TG': u'Togo',
    'TD': u'Chad',
    'TC': u'Turks & Caicos Islands',
    'LY': u'Libya',
    'VA': u'Vatican City',
    'AC': u'Ascension Island',
    '145': u'Western Asia',
    'AE': u'United Arab Emirates',
    'AD': u'Andorra',
    'AG': u'Antigua & Barbuda',
    'AF': u'Afghanistan',
    'AI': u'Anguilla',
    'VI': u'U.S. Virgin Islands',
    'IS': u'Iceland',
    'IR': u'Iran',
    'AM': u'Armenia',
    'AL': u'Albania',
    'AO': u'Angola',
    'AN': u'Netherlands Antilles',
    '003': u'North America',
    '002': u'Africa',
    '001': u'World',
    'AR': u'Argentina',
    'AU': u'Australia',
    'AT': u'Austria',
    '005': u'South America',
    'IN': u'India',
    'AX': u'Åland Islands',
    '009': u'Oceania',
    'AZ': u'Azerbaijan',
    'IE': u'Ireland',
    'ID': u'Indonesia',
    'JO': u'Jordan',
    'UA': u'Ukraine',
    'QA': u'Qatar',
    'DK': u'Denmark',
    'MZ': u'Mozambique',
    'QO': u'Outlying Oceania',
}