
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(/Users/wickman/clients/commons/src/python/twitter/common/java/BUILD, java))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'Utilities for interacting with Java classes and JVM internals.',
    'install_requires': ['twitter.common.lang==0.3.3'],
    'license': 'Apache License, Version 2.0',
    'name': 'twitter.common.java',
    'namespace_packages': ['twitter', 'twitter.common'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': [   'twitter',
                    'twitter.common',
                    'twitter.common.java',
                    'twitter.common.java.perfdata',
                    'twitter.common.java.perfdata.builders'],
    'url': 'https://github.com/twitter/commons',
    'version': '0.3.3',
    'zip_safe': True}
)
