
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1'
version_full = '6c86c419cb73c53a2ea6b04855f597ad8f9738a7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

