
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.1'
version_full = 'c2e4f32aae98d1c33a4ec748e4b4a080fda48efc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

