
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.3'
version_full = '27a31ab3215dd54fe192f12d4b7b8c8159c9bf76'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

