
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.1b1'
version_full = 'a46e11d8410c2b3a9e81fda142a21a82f4f8d1dd'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
