# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hell.ui'
#
# Created: Fri Jan 30 01:48:17 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from ..qt import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 615)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar = QtGui.QFrame(self.centralwidget)
        self.toolbar.setObjectName("toolbar")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.toolbar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pageControls = QtGui.QWidget(self.toolbar)
        self.pageControls.setObjectName("pageControls")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pageControls)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backButton = QtGui.QPushButton(self.pageControls)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_2.addWidget(self.backButton)
        self.horizontalLayout.addWidget(self.pageControls)
        self.listControls = QtGui.QWidget(self.toolbar)
        self.listControls.setObjectName("listControls")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.listControls)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchEdit = QtGui.QLineEdit(self.listControls)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_3.addWidget(self.searchEdit)
        self.horizontalLayout.addWidget(self.listControls)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.updateButton = QtGui.QPushButton(self.toolbar)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.settingsButton = QtGui.QPushButton(self.toolbar)
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout.addWidget(self.settingsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.toolbar)
        self.tabButtons = QtGui.QWidget(self.centralwidget)
        self.tabButtons.setObjectName("tabButtons")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabButtons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.installedButton = QtGui.QToolButton(self.tabButtons)
        self.installedButton.setCheckable(True)
        self.installedButton.setAutoRaise(True)
        self.installedButton.setObjectName("installedButton")
        self.horizontalLayout_4.addWidget(self.installedButton)
        self.availableButton = QtGui.QToolButton(self.tabButtons)
        self.availableButton.setCheckable(True)
        self.availableButton.setAutoRaise(True)
        self.availableButton.setObjectName("availableButton")
        self.horizontalLayout_4.addWidget(self.availableButton)
        self.updatesButton = QtGui.QToolButton(self.tabButtons)
        self.updatesButton.setCheckable(True)
        self.updatesButton.setAutoRaise(True)
        self.updatesButton.setObjectName("updatesButton")
        self.horizontalLayout_4.addWidget(self.updatesButton)
        self.progressButton = QtGui.QToolButton(self.tabButtons)
        self.progressButton.setCheckable(True)
        self.progressButton.setAutoRaise(True)
        self.progressButton.setObjectName("progressButton")
        self.horizontalLayout_4.addWidget(self.progressButton)
        self.verticalLayout.addWidget(self.tabButtons)
        self.webView = QtWebKit.QWebView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout.addWidget(self.webView)
        self.progressInfo = QtGui.QWidget(self.centralwidget)
        self.progressInfo.setObjectName("progressInfo")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.progressInfo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressLabel = QtGui.QLabel(self.progressInfo)
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.verticalLayout_2.addWidget(self.progressLabel)
        self.progressBar = QtGui.QProgressBar(self.progressInfo)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.progressInfo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Knossos", None, QtGui.QApplication.UnicodeUTF8))
        self.backButton.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.searchEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("MainWindow", "Update List", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.installedButton.setText(QtGui.QApplication.translate("MainWindow", "Installed", None, QtGui.QApplication.UnicodeUTF8))
        self.availableButton.setText(QtGui.QApplication.translate("MainWindow", "Available", None, QtGui.QApplication.UnicodeUTF8))
        self.updatesButton.setText(QtGui.QApplication.translate("MainWindow", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.progressButton.setText(QtGui.QApplication.translate("MainWindow", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.progressLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

from ..qt import QtWebKit
