# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mod_settings.ui'
#
# Created: Fri Jan 30 01:48:16 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from ..qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(457, 552)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modTitle = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.modTitle.setFont(font)
        self.modTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.modTitle.setObjectName("modTitle")
        self.verticalLayout.addWidget(self.modTitle)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modLogo = QtGui.QLabel(self.tab)
        self.modLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.modLogo.setObjectName("modLogo")
        self.verticalLayout_2.addWidget(self.modLogo)
        self.modDesc = QtGui.QPlainTextEdit(self.tab)
        self.modDesc.setReadOnly(True)
        self.modDesc.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.modDesc.setObjectName("modDesc")
        self.verticalLayout_2.addWidget(self.modDesc)
        self.tabWidget.addTab(self.tab, "")
        self.flagsTab = QtGui.QWidget()
        self.flagsTab.setObjectName("flagsTab")
        self.tabWidget.addTab(self.flagsTab, "")
        self.pkgTab = QtGui.QWidget()
        self.pkgTab.setObjectName("pkgTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pkgTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pkgsLayout = QtGui.QVBoxLayout()
        self.pkgsLayout.setObjectName("pkgsLayout")
        self.verticalLayout_3.addLayout(self.pkgsLayout)
        self.dlSizeLabel = QtGui.QLabel(self.pkgTab)
        self.dlSizeLabel.setObjectName("dlSizeLabel")
        self.verticalLayout_3.addWidget(self.dlSizeLabel)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.applyPkgChanges = QtGui.QPushButton(self.pkgTab)
        self.applyPkgChanges.setObjectName("applyPkgChanges")
        self.verticalLayout_3.addWidget(self.applyPkgChanges)
        self.tabWidget.addTab(self.pkgTab, "")
        self.versionsTab = QtGui.QWidget()
        self.versionsTab.setObjectName("versionsTab")
        self.tabWidget.addTab(self.versionsTab, "")
        self.troubleTab = QtGui.QWidget()
        self.troubleTab.setObjectName("troubleTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.troubleTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkFiles = QtGui.QPushButton(self.troubleTab)
        self.checkFiles.setObjectName("checkFiles")
        self.horizontalLayout.addWidget(self.checkFiles)
        self.delLoose = QtGui.QPushButton(self.troubleTab)
        self.delLoose.setObjectName("delLoose")
        self.horizontalLayout.addWidget(self.delLoose)
        self.replaceFiles = QtGui.QPushButton(self.troubleTab)
        self.replaceFiles.setObjectName("replaceFiles")
        self.horizontalLayout.addWidget(self.replaceFiles)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.logDisplay = QtGui.QTextBrowser(self.troubleTab)
        self.logDisplay.setObjectName("logDisplay")
        self.verticalLayout_4.addWidget(self.logDisplay)
        self.tabWidget.addTab(self.troubleTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Mod settings", None, QtGui.QApplication.UnicodeUTF8))
        self.modTitle.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.modLogo.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Infos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flagsTab), QtGui.QApplication.translate("Dialog", "Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.dlSizeLabel.setText(QtGui.QApplication.translate("Dialog", "Download size: {DL_SIZE}", None, QtGui.QApplication.UnicodeUTF8))
        self.applyPkgChanges.setText(QtGui.QApplication.translate("Dialog", "Apply changes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pkgTab), QtGui.QApplication.translate("Dialog", "Packages", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.versionsTab), QtGui.QApplication.translate("Dialog", "Versions", None, QtGui.QApplication.UnicodeUTF8))
        self.checkFiles.setText(QtGui.QApplication.translate("Dialog", "Check Files", None, QtGui.QApplication.UnicodeUTF8))
        self.delLoose.setText(QtGui.QApplication.translate("Dialog", "Delete loose files", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceFiles.setText(QtGui.QApplication.translate("Dialog", "Replace corrupted files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.troubleTab), QtGui.QApplication.translate("Dialog", "Troubleshoot", None, QtGui.QApplication.UnicodeUTF8))

