
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.2'
version_full = '15f43136052abadbd5b7f09d5c5fca473f721e2a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

