complete --command slpkg --long-option help --short-option h --description 'show this help message and exit'
complete --command slpkg --long-option version --short-option v --description 'print version and exit'
complete --command slpkg --long-option '' --short-option a --description 'auto build SBo packages'
complete --command slpkg --long-option '' --short-option b --description 'add, remove packages in blacklist'
complete --command slpkg --long-option '' --short-option q --description 'add, remove SBo packages in queue'
complete --command slpkg --long-option '' --short-option g --description 'configuration file management'
complete --command slpkg --long-option '' --short-option l --description 'list of repositories packages'
complete --command slpkg --long-option '' --short-option c --description 'check for updated packages'
complete --command slpkg --long-option '' --short-option s --description 'download, build & install packages'
complete --command slpkg --long-option '' --short-option t --description 'package tracking dependencies'
complete --command slpkg --long-option '' --short-option p --description 'print package description'
complete --command slpkg --long-option '' --short-option n --description 'view SBo packages through network'
complete --command slpkg --long-option '' --short-option f --description 'find installed packages'
complete --command slpkg --long-option '' --short-option i --description 'install binary packages'
complete --command slpkg --long-option '' --short-option u --description 'upgrade binary packages'
complete --command slpkg --long-option '' --short-option o --description 'reinstall binary packages'
complete --command slpkg --long-option '' --short-option r --description 'remove binary packages'
complete --command slpkg --long-option '' --short-option d --description 'display the contents'
complete --command slpkg --long-option add --short-option '' --description 'additional options for blacklist and queue'
complete --command slpkg --long-option remove --short-option '' --description 'additional options for blacklist and queue'
complete --command slpkg --long-option list --short-option '' --description 'additional options for blacklist and queue'
complete --command slpkg --long-option build --short-option '' --description 'additional options for queue'
complete --command slpkg --long-option install --short-option '' --description 'additional options for queue'
complete --command slpkg --long-option build-install --short-option '' --description 'additional options for queue'
complete --command slpkg --long-option config --short-option '' --description 'additional options for configuration file management'
