__version__ = "0.0.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.0.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'eb92f00be80869942f819bac9e0add75affce114'
__git_head_subject__ = 'doctsring update'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2015-04-07 14:50:55'
