__version__ = "0.3.33"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.33)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '0da6a856515dceda080acc2482bc65bb54f95add'
__git_head_subject__ = 'Finished release v0.3.33.'
__git_head_message__ = '* release/v0.3.33:\n  log_sense\n  Update documentation about Python 3\n  Python 3 compatibility'
__git_dirty_diff__ = ''