
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.0'
version_full = 'b21fbb2b926f8c12a02e23a17f5f239f7b9d173c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

