__version__ = "0.3.8"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd7b64e97bfe573fc780e4aa71c4f75557cd51189'
__git_head_subject__ = 'Finished release v0.3.8.'
__git_head_message__ = '* release/v0.3.8:\n  STORAGEMODEL-310 MountManager._iter_volume_mount_points should ignore inavlid volumes (veritas)\n  buildout.cfg: changed isolated python version to v2.7.6.21\n  buildout.cfg: changed isolated python version to v2.7.6.20\n  buildout.cfg: changed isolated python version to v2.7.6.19'
__git_dirty_diff__ = ''