
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.2'
version_full = 'c6e72f55cb10bccdcba2f31e9d52c528b12c5a0e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

