# This file was auto-generated by salt's setup on Wednesday, 25 March 2015 @ 19:03:24 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2014, 7, 3, 0, 0, 0, None)
