__version__ = "0.2.1"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.2.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'cc66cf8c94e0938735be9f1bfba9d0fef39c4d90'
__git_head_subject__ = 'buildout.cfg: adding python-cjson to requirements'
__git_head_message__ = ''
__git_dirty_diff__ = ''