
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.9'
version_full = 'af01817e96e02103d2b460c5da489cde7ea5302b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

