
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.1'
version_full = 'cf4d3efd8d37e5cac626137a360e0a5d1e8cc49c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

