
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.2'
version_full = '3b7ecb309e61555a2d37187d61254bf9e49a2a1f'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
