
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.1'
version_full = 'cb733b134b5a79c0801c8cc2096aa34b3fc97f65'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

