# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspace\dev\projex\projexui\src\projexui\widgets\xorbquerywidget\ui\xorbqueryentrywidget.ui'
#
# Created: Wed Dec 31 14:09:29 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 32)
        Form.setMinimumSize(QtCore.QSize(550, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 32))
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiSelectBTN = QtGui.QToolButton(Form)
        self.uiSelectBTN.setMinimumSize(QtCore.QSize(12, 28))
        self.uiSelectBTN.setMaximumSize(QtCore.QSize(14, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default/img/query/radio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSelectBTN.setIcon(icon)
        self.uiSelectBTN.setAutoRaise(True)
        self.uiSelectBTN.setObjectName("uiSelectBTN")
        self.horizontalLayout.addWidget(self.uiSelectBTN)
        self.uiRemoveBTN = QtGui.QToolButton(Form)
        self.uiRemoveBTN.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/default/img/query/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiRemoveBTN.setIcon(icon1)
        self.uiRemoveBTN.setIconSize(QtCore.QSize(24, 24))
        self.uiRemoveBTN.setAutoRaise(True)
        self.uiRemoveBTN.setObjectName("uiRemoveBTN")
        self.horizontalLayout.addWidget(self.uiRemoveBTN)
        self.uiColumnDDL = XOrbColumnNavigatorBox(Form)
        self.uiColumnDDL.setMinimumSize(QtCore.QSize(125, 28))
        self.uiColumnDDL.setMaximumSize(QtCore.QSize(16777215, 28))
        self.uiColumnDDL.setObjectName("uiColumnDDL")
        self.horizontalLayout.addWidget(self.uiColumnDDL)
        self.uiOperatorDDL = XComboBox(Form)
        self.uiOperatorDDL.setMinimumSize(QtCore.QSize(100, 28))
        self.uiOperatorDDL.setMaximumSize(QtCore.QSize(16777215, 28))
        self.uiOperatorDDL.setObjectName("uiOperatorDDL")
        self.horizontalLayout.addWidget(self.uiOperatorDDL)
        self.uiEditorAREA = QtGui.QScrollArea(Form)
        self.uiEditorAREA.setMinimumSize(QtCore.QSize(0, 28))
        self.uiEditorAREA.setMaximumSize(QtCore.QSize(16777215, 28))
        self.uiEditorAREA.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.uiEditorAREA.setFrameShape(QtGui.QFrame.NoFrame)
        self.uiEditorAREA.setFrameShadow(QtGui.QFrame.Plain)
        self.uiEditorAREA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.uiEditorAREA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.uiEditorAREA.setWidgetResizable(True)
        self.uiEditorAREA.setObjectName("uiEditorAREA")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 163, 28))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.uiEditorAREA.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.uiEditorAREA)
        spacerItem = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiJoinSBTN = XSplitButton(Form)
        self.uiJoinSBTN.setMinimumSize(QtCore.QSize(80, 28))
        self.uiJoinSBTN.setMaximumSize(QtCore.QSize(80, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 141, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(215, 233, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 130, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 141, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(215, 233, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 130, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 130, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.uiJoinSBTN.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setWeight(75)
        font.setBold(True)
        self.uiJoinSBTN.setFont(font)
        self.uiJoinSBTN.setProperty("x_actionTexts", ['AND', 'OR'])
        self.uiJoinSBTN.setObjectName("uiJoinSBTN")
        self.horizontalLayout.addWidget(self.uiJoinSBTN)
        self.uiEnterBTN = QtGui.QToolButton(Form)
        self.uiEnterBTN.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/default/img/query/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiEnterBTN.setIcon(icon2)
        self.uiEnterBTN.setIconSize(QtCore.QSize(24, 24))
        self.uiEnterBTN.setAutoRaise(True)
        self.uiEnterBTN.setObjectName("uiEnterBTN")
        self.horizontalLayout.addWidget(self.uiEnterBTN)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.uiSelectBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiRemoveBTN.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Remove Query</span></p><p>Removes this query item from the compound.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.uiRemoveBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiColumnDDL.setProperty("x_hint", QtGui.QApplication.translate("Form", "column", None, QtGui.QApplication.UnicodeUTF8))
        self.uiOperatorDDL.setProperty("x_hint", QtGui.QApplication.translate("Form", "operator", None, QtGui.QApplication.UnicodeUTF8))
        self.uiEnterBTN.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Edit Compound</span></p><p>Make this query a compound object. With compounds, you can create additional groups for joins.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.uiEnterBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))

from projexui.widgets.xsplitbutton import XSplitButton
from projexui.widgets.xorbcolumnnavigator import XOrbColumnNavigatorBox
from projexui.widgets.xcombobox import XComboBox

