__version__ = "0.1.9"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.9)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e2abf5f4c4e1099f6d92cf3bac4a79e7d1730071'
__git_head_subject__ = 'Finished release v0.1.9.'
__git_head_message__ = '* release/v0.1.9:\n  HIPVM-706 fixing _get_list_or_object_to_update for _merge_property_change__add\n  HIPVM-706 handling the case we need to update a property in an object by shallow-copying it and changing the pointer in its parent\n  HIPVM-706 getting rid of the deepcopy in the cached property collector, it takes a long time and consumes a lot of memory\n  TRIVIAL fixing call to _create_traversal_spec in CachedPropertyCollector broken in 6267cdc'
__git_dirty_diff__ = ''