
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(/Users/wickman/clients/commons/src/python/twitter/common/threading/BUILD, threading))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'twitter.common python threading libs.',
    'install_requires': [],
    'license': 'Apache License, Version 2.0',
    'name': 'twitter.common.threading',
    'namespace_packages': ['twitter', 'twitter.common'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': ['twitter', 'twitter.common', 'twitter.common.threading'],
    'url': 'https://github.com/twitter/commons',
    'version': '0.3.3',
    'zip_safe': True}
)
