__version__ = "0.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '661b901ae063abb6a181fed9aba74bf088bb4b16'
__git_head_subject__ = 'Finished release v0.2.'
__git_head_message__ = '* release/v0.2:\n  TRIVIAL adding src/infi/hbaapi/generators/hbaapi/_hbaapi_aix.so to .gitignore\n  fix\n  HOSTDEV-1810 returning the target wwn instead of the  target number in solaris\n  HOSTDEV-1809 Implement hbaapi for AIX'
__git_dirty_diff__ = ''