# Autogenerated by Astropy's setup.py on 2015-02-12 00:55:22.007579
from __future__ import unicode_literals
import datetime

version = "1.0rc2"
githash = ""


major = 1
minor = 0
bugfix = 0

release = True
timestamp = datetime.datetime(2015, 2, 12, 0, 55, 22, 7579)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
