class QueryState:
    QUERY_MASTER_INIT = 0
    QUERY_MASTER_LAUNCHED = 1
    QUERY_NEW = 2
    QUERY_INIT = 3
    QUERY_RUNNING = 4
    QUERY_SUCCEEDED = 5
    QUERY_FAILED = 6
    QUERY_KILLED = 7
    QUERY_KILL_WAIT = 8
    QUERY_ERROR = 9
    QUERY_NOT_ASSIGNED = 10
