from distutils.core import setup

setup(
      name='germline_filter',
      version='1.2',
      description='Python tool for detecting the number of germline calls in a vcf file generated by a somatic snv caller.',
      author='Cristian Caloian',
      author_email='cristian.caloian@oicr.on.ca',
      url='http://oicr.on.ca',
      package_dir = {'': 'lib'},    
      packages=[ 'germline_filter'],
      scripts=['germline_filter']
     )
