
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.8'
version_full = '8013d0796c8f6ed65359d42174f115cb84476d33'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

