__version__ = "0.2.7"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'bc9f9fe2d0caeba1bc1e2da4fcc619744fa7802a'
__git_head_subject__ = 'Finished release v0.2.7.'
__git_head_message__ = '* release/v0.2.7:\n  TRIVIAL update_page_contents: keeping the page in the same place\n  notify_related_tickets: handling unicode characters in ticket summary\n  notify_related_tickets: chekcing both directions\n  fixing jirelnotes fetch'
__git_dirty_diff__ = ''