
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1'
version_full = 'd140612820b48687e2a1f405c9fcef7c9f459d5d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

