# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspace\dev\projex\projexui\src\projexui\widgets\xorbbrowserwidget\ui\xorbbrowserwidget.ui'
#
# Created: Wed Dec 31 14:09:29 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(439, 333)
        self.gridLayout_4 = QtGui.QGridLayout(Form)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.uiControlsWGT = QtGui.QWidget(Form)
        self.uiControlsWGT.setObjectName("uiControlsWGT")
        self.horizontalLayout = QtGui.QHBoxLayout(self.uiControlsWGT)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiRefreshBTN = QtGui.QToolButton(self.uiControlsWGT)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default/img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiRefreshBTN.setIcon(icon)
        self.uiRefreshBTN.setAutoRaise(True)
        self.uiRefreshBTN.setObjectName("uiRefreshBTN")
        self.horizontalLayout.addWidget(self.uiRefreshBTN)
        self.uiSearchTXT = XLineEdit(self.uiControlsWGT)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/default/img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSearchTXT.setProperty("x_icon", icon1)
        self.uiSearchTXT.setProperty("x_cornerRadius", 8)
        self.uiSearchTXT.setObjectName("uiSearchTXT")
        self.horizontalLayout.addWidget(self.uiSearchTXT)
        self.uiQueryBTN = XPopupButton(self.uiControlsWGT)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/default/img/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiQueryBTN.setIcon(icon2)
        self.uiQueryBTN.setAutoRaise(True)
        self.uiQueryBTN.setObjectName("uiQueryBTN")
        self.horizontalLayout.addWidget(self.uiQueryBTN)
        spacerItem = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiViewModeWGT = XActionGroupWidget(self.uiControlsWGT)
        self.uiViewModeWGT.setMinimumSize(QtCore.QSize(90, 20))
        self.uiViewModeWGT.setMaximumSize(QtCore.QSize(90, 20))
        self.uiViewModeWGT.setObjectName("uiViewModeWGT")
        self.horizontalLayout.addWidget(self.uiViewModeWGT)
        spacerItem1 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.uiGroupBTN = QtGui.QToolButton(self.uiControlsWGT)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/default/img/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiGroupBTN.setIcon(icon3)
        self.uiGroupBTN.setCheckable(True)
        self.uiGroupBTN.setAutoRaise(True)
        self.uiGroupBTN.setObjectName("uiGroupBTN")
        self.horizontalLayout.addWidget(self.uiGroupBTN)
        self.uiGroupOptionsBTN = QtGui.QToolButton(self.uiControlsWGT)
        self.uiGroupOptionsBTN.setMaximumSize(QtCore.QSize(12, 16777215))
        self.uiGroupOptionsBTN.setAutoRaise(True)
        self.uiGroupOptionsBTN.setArrowType(QtCore.Qt.RightArrow)
        self.uiGroupOptionsBTN.setObjectName("uiGroupOptionsBTN")
        self.horizontalLayout.addWidget(self.uiGroupOptionsBTN)
        self.gridLayout_4.addWidget(self.uiControlsWGT, 0, 0, 1, 1)
        self.uiModeSTACK = QtGui.QStackedWidget(Form)
        self.uiModeSTACK.setObjectName("uiModeSTACK")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.uiRecordsTREE = XOrbTreeWidget(self.page)
        self.uiRecordsTREE.setProperty("x_arrowStyle", True)
        self.uiRecordsTREE.setObjectName("uiRecordsTREE")
        self.uiRecordsTREE.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.uiRecordsTREE, 0, 0, 1, 1)
        self.uiModeSTACK.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.uiCardTREE = XTreeWidget(self.page_2)
        self.uiCardTREE.setProperty("x_arrowStyle", True)
        self.uiCardTREE.setProperty("x_showGrid", False)
        self.uiCardTREE.setObjectName("uiCardTREE")
        self.uiCardTREE.headerItem().setText(0, "1")
        self.uiCardTREE.header().setVisible(False)
        self.gridLayout_2.addWidget(self.uiCardTREE, 0, 0, 1, 1)
        self.uiModeSTACK.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.uiThumbLIST = QtGui.QListWidget(self.page_3)
        self.uiThumbLIST.setMovement(QtGui.QListView.Static)
        self.uiThumbLIST.setResizeMode(QtGui.QListView.Adjust)
        self.uiThumbLIST.setSpacing(3)
        self.uiThumbLIST.setViewMode(QtGui.QListView.IconMode)
        self.uiThumbLIST.setSelectionRectVisible(False)
        self.uiThumbLIST.setObjectName("uiThumbLIST")
        self.gridLayout_3.addWidget(self.uiThumbLIST, 0, 0, 1, 1)
        self.uiModeSTACK.addWidget(self.page_3)
        self.gridLayout_4.addWidget(self.uiModeSTACK, 1, 0, 1, 1)
        self.uiDetailsACT = QtGui.QAction(Form)
        self.uiDetailsACT.setCheckable(True)
        self.uiDetailsACT.setChecked(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/default/img/view_details.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiDetailsACT.setIcon(icon4)
        self.uiDetailsACT.setObjectName("uiDetailsACT")
        self.uiCardACT = QtGui.QAction(Form)
        self.uiCardACT.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/default/img/view_card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCardACT.setIcon(icon5)
        self.uiCardACT.setObjectName("uiCardACT")
        self.uiThumbnailACT = QtGui.QAction(Form)
        self.uiThumbnailACT.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/default/img/view_thumbnail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiThumbnailACT.setIcon(icon6)
        self.uiThumbnailACT.setObjectName("uiThumbnailACT")
        self.uiQueryACT = QtGui.QAction(Form)
        self.uiQueryACT.setIcon(icon2)
        self.uiQueryACT.setObjectName("uiQueryACT")

        self.retranslateUi(Form)
        self.uiModeSTACK.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.uiSearchTXT, self.uiQueryBTN)
        Form.setTabOrder(self.uiQueryBTN, self.uiGroupBTN)
        Form.setTabOrder(self.uiGroupBTN, self.uiRecordsTREE)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.uiRefreshBTN.setToolTip(QtGui.QApplication.translate("Form", "Refresh Results", None, QtGui.QApplication.UnicodeUTF8))
        self.uiRefreshBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiSearchTXT.setProperty("x_hint", QtGui.QApplication.translate("Form", "quick search", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryBTN.setToolTip(QtGui.QApplication.translate("Form", "Edit Advanced Query", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGroupBTN.setToolTip(QtGui.QApplication.translate("Form", "Group Results", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGroupBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGroupOptionsBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiDetailsACT.setText(QtGui.QApplication.translate("Form", "View Details", None, QtGui.QApplication.UnicodeUTF8))
        self.uiDetailsACT.setToolTip(QtGui.QApplication.translate("Form", "View Details", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCardACT.setText(QtGui.QApplication.translate("Form", "View Cards", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCardACT.setToolTip(QtGui.QApplication.translate("Form", "View Cards", None, QtGui.QApplication.UnicodeUTF8))
        self.uiThumbnailACT.setText(QtGui.QApplication.translate("Form", "View Thumbnail", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryACT.setText(QtGui.QApplication.translate("Form", "Edit Query", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryACT.setToolTip(QtGui.QApplication.translate("Form", "Edit Query", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryACT.setShortcut(QtGui.QApplication.translate("Form", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))

from projexui.widgets.xactiongroupwidget import XActionGroupWidget
from projexui.widgets.xpopupbutton import XPopupButton
from projexui.widgets.xtreewidget import XTreeWidget
from projexui.widgets.xorbtreewidget import XOrbTreeWidget
from projexui.widgets.xlineedit import XLineEdit

