__version__ = "0.4.27"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.4.27)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '4c6eec3416ea84038d5ee2335328024aaa9cac88'
__git_head_subject__ = 'rebuild_package script'
__git_head_message__ = ''
__git_dirty_diff__ = ''