'''
This file contains the piecetypes configuration.
'''

PIECETYPES = [
    PieceType('1,5-Springer', '15'),
    PieceType('1,6-Springer', '16'),
    PieceType('2,4-Springer', '24'),
    PieceType('2,5-Springer', '25'),
    PieceType('3,5-Springer', '35'),
    PieceType('3,6-Springer', '36'),
    PieceType('3,7-Springer', '37'),
    PieceType('Adler', 'ad'),
    PieceType('Andernachgrasshuepfer', 'ag'),
    PieceType('Alfil', 'al'),
    PieceType('Amazone', 'am'),
    PieceType('Antilope', 'an'),
    PieceType('MaoReiter', 'ao'),
    PieceType('Bouncer', 'b1'),
    PieceType('Turmbouncer', 'b2'),
    PieceType('Laeuferbouncer', 'b3'),
    PieceType('Berolina Bauer', 'bb'),
    PieceType('Bison', 'bi'),
    PieceType('Bob', 'bo'),
    PieceType('Berolina Superbauer', 'bs'),
    PieceType('Wurzel-25-Springer (Bucephale)', 'bu'),
    PieceType('Kamel', 'ca'),
    PieceType('Chinesischer Bauer', 'cb'),
    PieceType('Kamelreiterhuepfer', 'ch'),
    PieceType('Kamelreiter', 'cr'),
    PieceType('CAT (cavalier trojan)', 'ct'),
    PieceType('Charybdis', 'cy'),
    PieceType('Dabbaba', 'da'),
    PieceType('Delphin', 'de'),
    PieceType('Doppelgrashuepfer', 'dg'),
    PieceType('Doppellaeuferhuepfer', 'dl'),
    PieceType('Drache', 'dr'),
    PieceType('Diagonalspiralspringer', 'ds'),
    PieceType('Doppelturmhuepfer', 'dt'),
    PieceType('Dummy', 'du'),
    PieceType('Eichhoernchen', 'ei'),
    PieceType('Erlkoenig', 'ek'),
    PieceType('Elch', 'el'),
    PieceType('Equihopper', 'eq'),
    PieceType('Erzbischof', 'er'),
    PieceType('Elefant				', 'et'),
    PieceType('Freund', 'f'),
    PieceType('Fers', 'fe'),
    PieceType('Fersreiter', 'fr'),
    PieceType('Grashuepfer', 'g'),
    PieceType('Grashuepfer-2', 'g2'),
    PieceType('Grashuepfer-3', 'g3'),
    PieceType('Gnureiterhuepfer', 'gh'),
    PieceType('Giraffe', 'gi'),
    PieceType('Gral', 'gl'),
    PieceType('Gnu', 'gn'),
    PieceType('Gnureiter', 'gr'),
    PieceType('Heuschrecke', 'h'),
    PieceType('Hamster', 'ha'),
    PieceType('Hase', 'he'),
    PieceType('Laeuferheuschrecke', 'hl'),
    PieceType('Nachtreiterheuschrecke', 'hn'),
    PieceType('Turmheuschrecke', 'ht'),
    PieceType('Kaenguruh', 'ka'),
    PieceType('KontraGrashuepfer', 'kg'),
    PieceType('Koenigshuepfer', 'kh'),
    PieceType('Kardinal', 'kl'),
    PieceType('Kaiserin', 'kn'),
    PieceType('Laeuferadler', 'la'),
    PieceType('Laeuferelch', 'lc'),
    PieceType('Leo', 'le'),
    PieceType('Laeuferhuepfer', 'lh'),
    PieceType('Lion', 'li'),
    PieceType('Laeufer/Turm-Jaeger', 'lj'),
    PieceType('Laeufer-Lion', 'll'),
    PieceType('Rosen-Heuschrecke', 'lr'),
    PieceType('Laeuferspatz', 'ls'),
    PieceType('Mao', 'ma'),
    PieceType('Marguerite', 'mg'),
    PieceType('Maoreiterlion', 'ml'),
    PieceType('Moareiterlion', 'mm'),
    PieceType('Moa', 'mo'),
    PieceType('Nachtreiter', 'n'),
    PieceType('Nao				', 'na'),
    PieceType('Nereide', 'nd'),
    PieceType('Non-stop Equihopper', 'ne'),
    PieceType('Nachtreiterhuepfer', 'nh'),
    PieceType('Nachtreiterlion', 'nl'),
    PieceType('Reflektierender Nachtreiter', 'nr'),
    PieceType('Orphan', 'o'),
    PieceType('MoaReiter', 'oa'),
    PieceType('Odysseus', 'od'),
    PieceType('Okapi', 'ok'),
    PieceType('Orix', 'or'),
    PieceType('Pao', 'pa'),
    PieceType('Pfadfinder', 'pf'),
    PieceType('Pfadfinderin', 'pn'),
    PieceType('Prinzessin', 'pr'),
    PieceType('EquiEnglisch', 'qe'),
    PieceType('EquiFranzoesisch', 'qf'),
    PieceType('Quintessence', 'qn'),
    PieceType('Rao', 'ra'),
    PieceType('ReversBauer', 'rb'),
    PieceType('Randschwein', 'rd'),
    PieceType('RosenHuepfer', 'rh'),
    PieceType('Reflektierender Laeufer', 'rl'),
    PieceType('RosenLioN', 'rn'),
    PieceType('Rose', 'ro'),
    PieceType('RadialsPringer', 'rp'),
    PieceType('Reflektierender Springer', 'rs'),
    PieceType('(1,1)-Zigzag Nachtreiter', 's1'),
    PieceType('(2,0)-Zigzag Nachtreiter', 's2'),
    PieceType('(3,3)-Zigzag Nachtreiter', 's3'),
    PieceType('(4,0)-Zigzag Nachtreiter', 's4'),
    PieceType('Superbauer', 'sb'),
    PieceType('Sirene', 'si'),
    PieceType('Skylla', 'sk'),
    PieceType('Skorpion			', 'so'),
    PieceType('Spatz', 'sp'),
    PieceType('Spiralspringer', 'ss'),
    PieceType('Turmadler', 'ta'),
    PieceType('Turmelch', 'tc'),
    PieceType('Turmhuepfer', 'th'),
    PieceType('Turm/Laeufer-Jaeger', 'tj'),
    PieceType('Turm-Lion', 'tl'),
    PieceType('Triton', 'tr'),
    PieceType('Turmspatz', 'ts'),
    PieceType('UbiUbi', 'uu'),
    PieceType('Vao', 'va'),
    PieceType('Waran', 'wa'),
    PieceType('Wesir', 'we'),
    PieceType('Wesirreiter', 'wr'),
    PieceType('Wurzel-50-Springer', 'wf'),
    PieceType('Zebra', 'z'),
    PieceType('Zebu', 'ze'),
    PieceType('Zebrareiterhuepfer', 'zh'),
    PieceType('Zebrareiter', 'zr'),
]

