# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parametersdlg.ui'
#
# Created: Wed May 14 15:26:23 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParametersDlg(object):
    def setupUi(self, ParametersDlg):
        ParametersDlg.setObjectName(_fromUtf8("ParametersDlg"))
        ParametersDlg.resize(609, 776)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/options.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ParametersDlg.setWindowIcon(icon)
        self.gridLayout_8 = QtGui.QGridLayout(ParametersDlg)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox = QtGui.QGroupBox(ParametersDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.templateSizeSlider = QtGui.QSlider(self.groupBox)
        self.templateSizeSlider.setMinimum(1)
        self.templateSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.templateSizeSlider.setObjectName(_fromUtf8("templateSizeSlider"))
        self.gridLayout_4.addWidget(self.templateSizeSlider, 0, 1, 1, 1)
        self.templateSize = QtGui.QSpinBox(self.groupBox)
        self.templateSize.setMinimum(1)
        self.templateSize.setObjectName(_fromUtf8("templateSize"))
        self.gridLayout_4.addWidget(self.templateSize, 0, 2, 1, 1)
        self.templateColorView = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateColorView.sizePolicy().hasHeightForWidth())
        self.templateColorView.setSizePolicy(sizePolicy)
        self.templateColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.templateColorView.setPalette(palette)
        self.templateColorView.setAutoFillBackground(True)
        self.templateColorView.setFrameShape(QtGui.QFrame.Box)
        self.templateColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.templateColorView.setText(_fromUtf8(""))
        self.templateColorView.setObjectName(_fromUtf8("templateColorView"))
        self.gridLayout_4.addWidget(self.templateColorView, 0, 3, 1, 1)
        self.changeTemplateColor = QtGui.QPushButton(self.groupBox)
        self.changeTemplateColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeTemplateColor.setObjectName(_fromUtf8("changeTemplateColor"))
        self.gridLayout_4.addWidget(self.changeTemplateColor, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.searchSizeSlider = QtGui.QSlider(self.groupBox)
        self.searchSizeSlider.setMinimum(2)
        self.searchSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.searchSizeSlider.setObjectName(_fromUtf8("searchSizeSlider"))
        self.gridLayout_4.addWidget(self.searchSizeSlider, 1, 1, 1, 1)
        self.searchSize = QtGui.QSpinBox(self.groupBox)
        self.searchSize.setMinimum(2)
        self.searchSize.setObjectName(_fromUtf8("searchSize"))
        self.gridLayout_4.addWidget(self.searchSize, 1, 2, 1, 1)
        self.searchColorView = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchColorView.sizePolicy().hasHeightForWidth())
        self.searchColorView.setSizePolicy(sizePolicy)
        self.searchColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.searchColorView.setPalette(palette)
        self.searchColorView.setAutoFillBackground(True)
        self.searchColorView.setFrameShape(QtGui.QFrame.Box)
        self.searchColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.searchColorView.setText(_fromUtf8(""))
        self.searchColorView.setObjectName(_fromUtf8("searchColorView"))
        self.gridLayout_4.addWidget(self.searchColorView, 1, 3, 1, 1)
        self.changeSearchColor = QtGui.QPushButton(self.groupBox)
        self.changeSearchColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeSearchColor.setObjectName(_fromUtf8("changeSearchColor"))
        self.gridLayout_4.addWidget(self.changeSearchColor, 1, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.filterSizeSlider = QtGui.QSlider(self.groupBox)
        self.filterSizeSlider.setMinimum(0)
        self.filterSizeSlider.setMaximum(100)
        self.filterSizeSlider.setProperty("value", 50)
        self.filterSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.filterSizeSlider.setObjectName(_fromUtf8("filterSizeSlider"))
        self.gridLayout_4.addWidget(self.filterSizeSlider, 2, 1, 1, 1)
        self.filterSize = QtGui.QSpinBox(self.groupBox)
        self.filterSize.setMaximum(100)
        self.filterSize.setProperty("value", 50)
        self.filterSize.setObjectName(_fromUtf8("filterSize"))
        self.gridLayout_4.addWidget(self.filterSize, 2, 2, 1, 3)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(ParametersDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.pointsSize = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.pointsSize.setDecimals(1)
        self.pointsSize.setSingleStep(0.5)
        self.pointsSize.setObjectName(_fromUtf8("pointsSize"))
        self.gridLayout_2.addWidget(self.pointsSize, 0, 1, 1, 2)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.pointsThickness = QtGui.QSpinBox(self.groupBox_2)
        self.pointsThickness.setSingleStep(1)
        self.pointsThickness.setProperty("decimals", 1)
        self.pointsThickness.setObjectName(_fromUtf8("pointsThickness"))
        self.gridLayout_2.addWidget(self.pointsThickness, 1, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.pointsColorView = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointsColorView.sizePolicy().hasHeightForWidth())
        self.pointsColorView.setSizePolicy(sizePolicy)
        self.pointsColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pointsColorView.setPalette(palette)
        self.pointsColorView.setAutoFillBackground(True)
        self.pointsColorView.setFrameShape(QtGui.QFrame.Box)
        self.pointsColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.pointsColorView.setText(_fromUtf8(""))
        self.pointsColorView.setObjectName(_fromUtf8("pointsColorView"))
        self.gridLayout_2.addWidget(self.pointsColorView, 2, 1, 1, 1)
        self.changePointsColor = QtGui.QPushButton(self.groupBox_2)
        self.changePointsColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changePointsColor.setObjectName(_fromUtf8("changePointsColor"))
        self.gridLayout_2.addWidget(self.changePointsColor, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.selectedPointsColorView = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedPointsColorView.sizePolicy().hasHeightForWidth())
        self.selectedPointsColorView.setSizePolicy(sizePolicy)
        self.selectedPointsColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.selectedPointsColorView.setPalette(palette)
        self.selectedPointsColorView.setAutoFillBackground(True)
        self.selectedPointsColorView.setFrameShape(QtGui.QFrame.Box)
        self.selectedPointsColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.selectedPointsColorView.setText(_fromUtf8(""))
        self.selectedPointsColorView.setObjectName(_fromUtf8("selectedPointsColorView"))
        self.gridLayout_2.addWidget(self.selectedPointsColorView, 3, 1, 1, 1)
        self.changeSelectedPointsColor = QtGui.QPushButton(self.groupBox_2)
        self.changeSelectedPointsColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeSelectedPointsColor.setObjectName(_fromUtf8("changeSelectedPointsColor"))
        self.gridLayout_2.addWidget(self.changeSelectedPointsColor, 3, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.newPointsColorView = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newPointsColorView.sizePolicy().hasHeightForWidth())
        self.newPointsColorView.setSizePolicy(sizePolicy)
        self.newPointsColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.newPointsColorView.setPalette(palette)
        self.newPointsColorView.setAutoFillBackground(True)
        self.newPointsColorView.setFrameShape(QtGui.QFrame.Box)
        self.newPointsColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.newPointsColorView.setText(_fromUtf8(""))
        self.newPointsColorView.setObjectName(_fromUtf8("newPointsColorView"))
        self.gridLayout_2.addWidget(self.newPointsColorView, 4, 1, 1, 1)
        self.changeNewPointsColor = QtGui.QPushButton(self.groupBox_2)
        self.changeNewPointsColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeNewPointsColor.setObjectName(_fromUtf8("changeNewPointsColor"))
        self.gridLayout_2.addWidget(self.changeNewPointsColor, 4, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(ParametersDlg)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.arrowsLineSize = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.arrowsLineSize.setDecimals(1)
        self.arrowsLineSize.setSingleStep(0.5)
        self.arrowsLineSize.setObjectName(_fromUtf8("arrowsLineSize"))
        self.gridLayout_6.addWidget(self.arrowsLineSize, 0, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.arrowHeadSize = QtGui.QSpinBox(self.groupBox_3)
        self.arrowHeadSize.setMaximum(100)
        self.arrowHeadSize.setObjectName(_fromUtf8("arrowHeadSize"))
        self.gridLayout_6.addWidget(self.arrowHeadSize, 1, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.arrowsColorView = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrowsColorView.sizePolicy().hasHeightForWidth())
        self.arrowsColorView.setSizePolicy(sizePolicy)
        self.arrowsColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.arrowsColorView.setPalette(palette)
        self.arrowsColorView.setAutoFillBackground(True)
        self.arrowsColorView.setFrameShape(QtGui.QFrame.Box)
        self.arrowsColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.arrowsColorView.setText(_fromUtf8(""))
        self.arrowsColorView.setObjectName(_fromUtf8("arrowsColorView"))
        self.gridLayout_6.addWidget(self.arrowsColorView, 2, 1, 1, 1)
        self.changeArrowsColor = QtGui.QPushButton(self.groupBox_3)
        self.changeArrowsColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeArrowsColor.setObjectName(_fromUtf8("changeArrowsColor"))
        self.gridLayout_6.addWidget(self.changeArrowsColor, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 3, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(ParametersDlg)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.cacheSize = QtGui.QSpinBox(self.groupBox_5)
        self.cacheSize.setMaximum(9999)
        self.cacheSize.setSingleStep(50)
        self.cacheSize.setObjectName(_fromUtf8("cacheSize"))
        self.gridLayout_7.addWidget(self.cacheSize, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(30, 255, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 1, 3, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(ParametersDlg)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.oldPointsSize = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.oldPointsSize.setDecimals(1)
        self.oldPointsSize.setSingleStep(0.5)
        self.oldPointsSize.setObjectName(_fromUtf8("oldPointsSize"))
        self.gridLayout_3.addWidget(self.oldPointsSize, 0, 1, 1, 2)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.oldPointsThickness = QtGui.QSpinBox(self.groupBox_4)
        self.oldPointsThickness.setSingleStep(1)
        self.oldPointsThickness.setProperty("decimals", 1)
        self.oldPointsThickness.setObjectName(_fromUtf8("oldPointsThickness"))
        self.gridLayout_3.addWidget(self.oldPointsThickness, 1, 1, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.oldPointsColorView = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPointsColorView.sizePolicy().hasHeightForWidth())
        self.oldPointsColorView.setSizePolicy(sizePolicy)
        self.oldPointsColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.oldPointsColorView.setPalette(palette)
        self.oldPointsColorView.setAutoFillBackground(True)
        self.oldPointsColorView.setFrameShape(QtGui.QFrame.Box)
        self.oldPointsColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.oldPointsColorView.setText(_fromUtf8(""))
        self.oldPointsColorView.setObjectName(_fromUtf8("oldPointsColorView"))
        self.gridLayout_3.addWidget(self.oldPointsColorView, 2, 1, 1, 1)
        self.changeOldPointsColor = QtGui.QPushButton(self.groupBox_4)
        self.changeOldPointsColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeOldPointsColor.setObjectName(_fromUtf8("changeOldPointsColor"))
        self.gridLayout_3.addWidget(self.changeOldPointsColor, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.oldPointsMatchingColorView = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPointsMatchingColorView.sizePolicy().hasHeightForWidth())
        self.oldPointsMatchingColorView.setSizePolicy(sizePolicy)
        self.oldPointsMatchingColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.oldPointsMatchingColorView.setPalette(palette)
        self.oldPointsMatchingColorView.setAutoFillBackground(True)
        self.oldPointsMatchingColorView.setFrameShape(QtGui.QFrame.Box)
        self.oldPointsMatchingColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.oldPointsMatchingColorView.setText(_fromUtf8(""))
        self.oldPointsMatchingColorView.setObjectName(_fromUtf8("oldPointsMatchingColorView"))
        self.gridLayout_3.addWidget(self.oldPointsMatchingColorView, 3, 1, 1, 1)
        self.changeOldPointsMatchingColor = QtGui.QPushButton(self.groupBox_4)
        self.changeOldPointsMatchingColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeOldPointsMatchingColor.setObjectName(_fromUtf8("changeOldPointsMatchingColor"))
        self.gridLayout_3.addWidget(self.changeOldPointsMatchingColor, 3, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(ParametersDlg)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.cellsSize = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.cellsSize.setDecimals(1)
        self.cellsSize.setSingleStep(0.5)
        self.cellsSize.setObjectName(_fromUtf8("cellsSize"))
        self.gridLayout.addWidget(self.cellsSize, 0, 1, 1, 2)
        self.label_18 = QtGui.QLabel(self.groupBox_7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1)
        self.cellsThickness = QtGui.QSpinBox(self.groupBox_7)
        self.cellsThickness.setSingleStep(1)
        self.cellsThickness.setProperty("decimals", 1)
        self.cellsThickness.setObjectName(_fromUtf8("cellsThickness"))
        self.gridLayout.addWidget(self.cellsThickness, 1, 1, 1, 2)
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.cellsColorView = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cellsColorView.sizePolicy().hasHeightForWidth())
        self.cellsColorView.setSizePolicy(sizePolicy)
        self.cellsColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.cellsColorView.setPalette(palette)
        self.cellsColorView.setAutoFillBackground(True)
        self.cellsColorView.setFrameShape(QtGui.QFrame.Box)
        self.cellsColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.cellsColorView.setText(_fromUtf8(""))
        self.cellsColorView.setObjectName(_fromUtf8("cellsColorView"))
        self.gridLayout.addWidget(self.cellsColorView, 2, 1, 1, 1)
        self.changeCellsColor = QtGui.QPushButton(self.groupBox_7)
        self.changeCellsColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeCellsColor.setObjectName(_fromUtf8("changeCellsColor"))
        self.gridLayout.addWidget(self.changeCellsColor, 2, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.selectedCellsColorView = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedCellsColorView.sizePolicy().hasHeightForWidth())
        self.selectedCellsColorView.setSizePolicy(sizePolicy)
        self.selectedCellsColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.selectedCellsColorView.setPalette(palette)
        self.selectedCellsColorView.setAutoFillBackground(True)
        self.selectedCellsColorView.setFrameShape(QtGui.QFrame.Box)
        self.selectedCellsColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.selectedCellsColorView.setText(_fromUtf8(""))
        self.selectedCellsColorView.setObjectName(_fromUtf8("selectedCellsColorView"))
        self.gridLayout.addWidget(self.selectedCellsColorView, 3, 1, 1, 1)
        self.changeSelectedCellsColor = QtGui.QPushButton(self.groupBox_7)
        self.changeSelectedCellsColor.setMaximumSize(QtCore.QSize(32, 32))
        self.changeSelectedCellsColor.setObjectName(_fromUtf8("changeSelectedCellsColor"))
        self.gridLayout.addWidget(self.changeSelectedCellsColor, 3, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 4, 0, 1, 1)
        self.divisionWallColorView = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.divisionWallColorView.sizePolicy().hasHeightForWidth())
        self.divisionWallColorView.setSizePolicy(sizePolicy)
        self.divisionWallColorView.setMinimumSize(QtCore.QSize(32, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.divisionWallColorView.setPalette(palette)
        self.divisionWallColorView.setAutoFillBackground(True)
        self.divisionWallColorView.setFrameShape(QtGui.QFrame.Box)
        self.divisionWallColorView.setFrameShadow(QtGui.QFrame.Sunken)
        self.divisionWallColorView.setText(_fromUtf8(""))
        self.divisionWallColorView.setObjectName(_fromUtf8("divisionWallColorView"))
        self.gridLayout.addWidget(self.divisionWallColorView, 4, 1, 1, 1)
        self.divisionWallColor = QtGui.QPushButton(self.groupBox_7)
        self.divisionWallColor.setMaximumSize(QtCore.QSize(32, 32))
        self.divisionWallColor.setObjectName(_fromUtf8("divisionWallColor"))
        self.gridLayout.addWidget(self.divisionWallColor, 4, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_7, 2, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(ParametersDlg)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.useOpenGL = QtGui.QCheckBox(self.groupBox_6)
        self.useOpenGL.setObjectName(_fromUtf8("useOpenGL"))
        self.gridLayout_5.addWidget(self.useOpenGL, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_6, 2, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(30, 265, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 2, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ParametersDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_8.addWidget(self.buttonBox, 3, 0, 1, 3)

        self.retranslateUi(ParametersDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ParametersDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ParametersDlg.reject)
        QtCore.QObject.connect(self.templateSizeSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.templateSize.setValue)
        QtCore.QObject.connect(self.searchSizeSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.searchSize.setValue)
        QtCore.QObject.connect(self.templateSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.templateSizeSlider.setValue)
        QtCore.QObject.connect(self.searchSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.searchSizeSlider.setValue)
        QtCore.QObject.connect(self.filterSizeSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.filterSize.setValue)
        QtCore.QObject.connect(self.filterSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.filterSizeSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(ParametersDlg)
        ParametersDlg.setTabOrder(self.templateSizeSlider, self.templateSize)
        ParametersDlg.setTabOrder(self.templateSize, self.changeTemplateColor)
        ParametersDlg.setTabOrder(self.changeTemplateColor, self.searchSizeSlider)
        ParametersDlg.setTabOrder(self.searchSizeSlider, self.searchSize)
        ParametersDlg.setTabOrder(self.searchSize, self.changeSearchColor)
        ParametersDlg.setTabOrder(self.changeSearchColor, self.filterSizeSlider)
        ParametersDlg.setTabOrder(self.filterSizeSlider, self.filterSize)
        ParametersDlg.setTabOrder(self.filterSize, self.oldPointsSize)
        ParametersDlg.setTabOrder(self.oldPointsSize, self.oldPointsThickness)
        ParametersDlg.setTabOrder(self.oldPointsThickness, self.changeOldPointsColor)
        ParametersDlg.setTabOrder(self.changeOldPointsColor, self.changeOldPointsMatchingColor)
        ParametersDlg.setTabOrder(self.changeOldPointsMatchingColor, self.pointsSize)
        ParametersDlg.setTabOrder(self.pointsSize, self.pointsThickness)
        ParametersDlg.setTabOrder(self.pointsThickness, self.changePointsColor)
        ParametersDlg.setTabOrder(self.changePointsColor, self.changeSelectedPointsColor)
        ParametersDlg.setTabOrder(self.changeSelectedPointsColor, self.changeNewPointsColor)
        ParametersDlg.setTabOrder(self.changeNewPointsColor, self.arrowsLineSize)
        ParametersDlg.setTabOrder(self.arrowsLineSize, self.arrowHeadSize)
        ParametersDlg.setTabOrder(self.arrowHeadSize, self.changeArrowsColor)
        ParametersDlg.setTabOrder(self.changeArrowsColor, self.cacheSize)
        ParametersDlg.setTabOrder(self.cacheSize, self.useOpenGL)
        ParametersDlg.setTabOrder(self.useOpenGL, self.buttonBox)

    def retranslateUi(self, ParametersDlg):
        ParametersDlg.setWindowTitle(_translate("ParametersDlg", "Parameters", None))
        self.groupBox.setTitle(_translate("ParametersDlg", "Search parameters", None))
        self.label.setText(_translate("ParametersDlg", "Template size", None))
        self.templateSize.setSuffix(_translate("ParametersDlg", " px", None))
        self.changeTemplateColor.setText(_translate("ParametersDlg", "...", None))
        self.label_2.setText(_translate("ParametersDlg", "Search area size", None))
        self.searchSize.setSuffix(_translate("ParametersDlg", " px", None))
        self.changeSearchColor.setText(_translate("ParametersDlg", "...", None))
        self.label_13.setText(_translate("ParametersDlg", "Filter size", None))
        self.filterSize.setSuffix(_translate("ParametersDlg", "%", None))
        self.groupBox_2.setTitle(_translate("ParametersDlg", "Points", None))
        self.label_3.setText(_translate("ParametersDlg", "Size", None))
        self.pointsSize.setSuffix(_translate("ParametersDlg", " px", None))
        self.label_15.setText(_translate("ParametersDlg", "Thickness", None))
        self.pointsThickness.setSuffix(_translate("ParametersDlg", " px", None))
        self.label_4.setText(_translate("ParametersDlg", "Color", None))
        self.changePointsColor.setText(_translate("ParametersDlg", "...", None))
        self.label_5.setText(_translate("ParametersDlg", "Selected", None))
        self.changeSelectedPointsColor.setText(_translate("ParametersDlg", "...", None))
        self.label_16.setText(_translate("ParametersDlg", "New points", None))
        self.changeNewPointsColor.setText(_translate("ParametersDlg", "...", None))
        self.groupBox_3.setTitle(_translate("ParametersDlg", "Arrows", None))
        self.label_9.setText(_translate("ParametersDlg", "Thickness", None))
        self.arrowsLineSize.setSuffix(_translate("ParametersDlg", " px", None))
        self.label_7.setText(_translate("ParametersDlg", "Head size", None))
        self.arrowHeadSize.setSuffix(_translate("ParametersDlg", "%", None))
        self.label_8.setText(_translate("ParametersDlg", "Color", None))
        self.changeArrowsColor.setText(_translate("ParametersDlg", "...", None))
        self.groupBox_5.setTitle(_translate("ParametersDlg", "Image cache", None))
        self.label_12.setText(_translate("ParametersDlg", "Size", None))
        self.cacheSize.setSuffix(_translate("ParametersDlg", " MB", None))
        self.groupBox_4.setTitle(_translate("ParametersDlg", "Old points", None))
        self.label_10.setText(_translate("ParametersDlg", "Size", None))
        self.oldPointsSize.setSuffix(_translate("ParametersDlg", " px", None))
        self.label_14.setText(_translate("ParametersDlg", "Thickness", None))
        self.oldPointsThickness.setSuffix(_translate("ParametersDlg", " px", None))
        self.label_11.setText(_translate("ParametersDlg", "Color", None))
        self.changeOldPointsColor.setText(_translate("ParametersDlg", "...", None))
        self.label_6.setText(_translate("ParametersDlg", "Matching", None))
        self.changeOldPointsMatchingColor.setText(_translate("ParametersDlg", "...", None))
        self.groupBox_7.setTitle(_translate("ParametersDlg", "Cells", None))
        self.label_17.setText(_translate("ParametersDlg", "Size", None))
        self.cellsSize.setSuffix(_translate("ParametersDlg", " px", None))
        self.label_18.setText(_translate("ParametersDlg", "Thickness", None))
        self.cellsThickness.setSuffix(_translate("ParametersDlg", " px", None))
        self.label_19.setText(_translate("ParametersDlg", "Color", None))
        self.changeCellsColor.setText(_translate("ParametersDlg", "...", None))
        self.label_20.setText(_translate("ParametersDlg", "Selected", None))
        self.changeSelectedCellsColor.setText(_translate("ParametersDlg", "...", None))
        self.label_21.setText(_translate("ParametersDlg", "Division", None))
        self.divisionWallColor.setText(_translate("ParametersDlg", "...", None))
        self.groupBox_6.setTitle(_translate("ParametersDlg", "Rendering", None))
        self.useOpenGL.setText(_translate("ParametersDlg", "use OpenGL", None))

from . import icons_rc
