__version__ = "0.0.14"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.0.14)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7139fa33625a6c518910c47d9e024c353577aad8'
__git_head_subject__ = 'Finished release v0.0.14.'
__git_head_message__ = '* release/v0.0.14:\n  protect against None cwd\n  fix last commits\n  fix tests\n  getcwd from psutil is deprecated, use cwd\n  buildout.cfg: changed isolated python version to v2.7.6.21\n  buildout.cfg: changed isolated python version to v2.7.6.20\n  buildout.cfg: changed isolated python version to v2.7.6.19'
__git_dirty_diff__ = ''