# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2015-02-18 12:03:57.150554
from __future__ import unicode_literals
import datetime

version = "0.4.7"
githash = "c5cd5b785bd2e6cb96ce824a318cac09d36955e4"


major = 0
minor = 4
bugfix = 7

release = True
timestamp = datetime.datetime(2015, 2, 18, 12, 3, 57, 150554)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
