# -*- coding: utf-8 -*-

### Generated Code. DO NOT Modify it manually!
### Generated by bluelake-gen-py. Generator version: v0.0.1
### Generated at 2015-03-05 16:00:36
### Original interface:  me.ele.coffee.hr.iservice.IBuService

from bluelake.client import JsonService, JsonMethod

@JsonService(name=u'buService')
class IBuService(object):

    def __init__(self, server):
        self.server = server

    @JsonMethod()
    def updateBu(self, context, bu):
        '''

        :param context:    Context
        :param bu:    BusinessUnit
        :return:
        '''
        pass


    @JsonMethod()
    def addBu(self, context, bu):
        '''

        :param context:    Context
        :param bu:    BusinessUnit
        :return:
        '''
        pass


    @JsonMethod()
    def getVisibleUserBuMap(self, context):
        '''

        :param context:    Context
        :return:
        '''
        pass


    @JsonMethod()
    def getBuById(self, context, buId):
        '''

        :param context:    Context
        :param buId:    int
        :return:
        '''
        pass


    @JsonMethod()
    def updateBuManager(self, context, userBuRole):
        '''

        :param context:    Context
        :param userBuRole:    UserBuRole
        :return:
        '''
        pass


    @JsonMethod()
    def removeBuManager(self, context, buId):
        '''

        :param context:    Context
        :param buId:    int
        :return:
        '''
        pass


    @JsonMethod()
    def getAllBuTypesMap(self, context):
        '''

        :param context:    Context
        :return:
        '''
        pass


    @JsonMethod()
    def getParentBu(self, context, bu):
        '''

        :param context:    Context
        :param bu:    BusinessUnit
        :return:
        '''
        pass


    @JsonMethod()
    def getSiblingsBuMap(self, context, bu):
        '''

        :param context:    Context
        :param bu:    BusinessUnit
        :return:
        '''
        pass


    @JsonMethod()
    def getSubordinateBuMap(self, context, bu):
        '''

        :param context:    Context
        :param bu:    BusinessUnit
        :return:
        '''
        pass


    @JsonMethod()
    def getRecursiveSubordinateBuMap(self, context, bu):
        '''

        :param context:    Context
        :param bu:    BusinessUnit
        :return:
        '''
        pass


    @JsonMethod()
    def getParentsMap(self, context, bu):
        '''

        :param context:    Context
        :param bu:    BusinessUnit
        :return:
        '''
        pass


    @JsonMethod()
    def getByInnerWalleId(self, context, walleId):
        '''

        :param context:    Context
        :param walleId:    int
        :return:
        '''
        pass


    @JsonMethod()
    def transToWalleIds(self, context, buIdList):
        '''

        :param context:    Context
        :param buIdList:    List
        :return:
        '''
        pass


    @JsonMethod()
    def getRGIdListByCityId(self, context, cityId):
        '''

        :param context:    Context
        :param cityId:    int
        :return:
        '''
        pass


    @JsonMethod()
    def getVisibleCityIds(self, context):
        '''

        :param context:    Context
        :return:
        '''
        pass

