#credit in dream7 challenge model1
#-------------------------------------
# see python code here below

first = ['array_mod_2_over_p11_low.tab',
 'array_mod_2_over_p9_low.tab',
 'array_mod_2_over_p5_2_low.tab',
 'array_mod_2_del_p7_high.tab',
 'p1_p11_mod_2_wildtype.tab',
 'array_mod_2_over_p7_low.tab',
 'array_mod_2_over_p6_low.tab',
 'p6_p7_mod_2_wildtype.tab',
 'p8_p9_mod_2_wildtype.tab',
 'p4_p5_mod_2_wildtype.tab',
 'p2_p3_mod_2_wildtype.tab',
 'array_mod_2_dwn_p7_low.tab',
 'array_mod_2_over_p10_low.tab',
 'model_1_rs1b.tab',
 'model_1_rs1a.tab',
 'p3_p5_mod_1_dwn_rbs8.tab',
 'p3_p6_mod_1_dwn_v4_mrna.tab',
 'array_mod_1_dwn_v6_mrna_low.tab',
 'p2_p3_mod_1_dwn_v3_mrna.tab',
 'p4_p9_mod_1_dwn_v9_mrna.tab',
 'p1_p2_mod_1_del_pro6.tab',
 'p1_p2_mod_1_wildtype.tab',
 'p8_p9_mod_1_wildtype.tab',
 'p5_p7_mod_1_wildtype.tab',
 'p3_p4_mod_1_wildtype.tab']

second = ['p7_p8_mod_1_dwn_v7_mrna.tab',
 'p3_p5_mod_1_dwn_v7_mrna.tab',
 'p5_p7_mod_2_wildtype.tab',
 'array_mod_1_dwn_v9_mrna_low.tab',
 'array_mod_2_over_p3_low.tab',
 'array_mod_2_over_p10_low.tab',
 'p8_p9_mod_1_dwn_v9_mrna.tab',
 'array_mod_2_del_p1_low.tab',
 'array_mod_2_over_p7_low.tab',
 'array_mod_2_over_p11_low.tab',
 'array_mod_2_del_p11_low.tab',
 'array_mod_2_over_p9_low.tab',
 'model_1_as1.tab',
 'p1_p2_mod_1_del_pro3.tab',
 'p1_p2_mod_1_del_pro6.tab',
 'array_mod_1_del_pro6_low.tab',
 'array_mod_2_dwn_p8_low.tab',
 'array_mod_2_del_p7_high.tab',
 'p4_p5_mod_1_wildtype.tab',
 'p2_p3_mod_1_wildtype.tab',
 'p6_p7_mod_1_wildtype.tab',
 'p1_p9_mod_1_wildtype.tab']

third = ['array_mod_2_del_p3_low.tab',
 'array_mod_2_over_p8_low.tab',
 'array_mod_2_over_p3_low.tab',
 'array_mod_2_over_p11_low.tab',
 'array_mod_2_del_p8_low.tab',
 'array_mod_2_del_p7_low.tab',
 'array_mod_2_del_p11_low.tab',
 'model_1_rs7.tab',
 'array_mod_1_del_pro5_low.tab',
 'array_mod_1_del_pro7_low.tab',
 'model_1_as9.tab',
 'p6_p7_mod_1_del_pro6.tab',
 'model_1_as1.tab',
 'array_mod_1_del_pro6_low.tab']

