copy_types = [
        {'visibility': 'Global',
         'interfaces': [],
         'action': 'manage_add_issue',
         'permission': 'Add Issues',
         'name': 'Issue',
         'product': 'Issue Dealer',
         'instance': ''},
        {'visibility': 'Global',
         'interfaces': [],
         'action': 'manage_add_relation',
         'permission': 'Add Relations',
         'name': 'Relation',
         'product': 'Issue Dealer',
         'instance': ''},
        {'visibility': 'Global',
         'interfaces': [],
         'action': 'add_laf_object',
         'permission': 'Add LAF object',
         'name': 'ID LAF Object',
         'product': 'Issue Dealer',
         'instance': ''},
]