
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1'
version_full = '165f0c812a6d9bf764b02178135ba24e3e1de782'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

