
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.4'
version_full = '753f7b269ad86f08321fd4a2f4d500db7ab7ac76'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

