
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.0.post.dev2'
version_full = '676a553efa70f07a2532e2d9b0387da3e54513f3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

