__version__ = "0.3"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '2922123bb30a3ecca51f5c730e48f190d254875f'
__git_head_subject__ = 'Finished release v0.3.'
__git_head_message__ = ''
__git_dirty_diff__ = ''