__version__ = "0.1.10"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.10)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '19f15bad9fb1f124ce6a2333036b1a6fdddbf817'
__git_head_subject__ = 'Finished release v0.1.10.'
__git_head_message__ = '* release/v0.1.10:\n  HIP-1375 added basic support for solaris (only querying)\n  TRIVIAL fixed package removal in suse'
__git_dirty_diff__ = ''