__version__ = "0.2.9"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.9)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'c65473d00498ca7e3bc10f33720aa01f6e760fa8'
__git_head_subject__ = 'HIP-1433 fixing the blkid regex'
__git_head_message__ = ''
__git_dirty_diff__ = ''