
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(/Users/ity/workspace/commons/pants-plugins/src/python/twitter/common/pants/BUILD, plugins))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'twitter.common plugins for the pants build system.',
    'install_requires': [   'pantsbuild.pants>=0.0.28,<0.1.0',
                            'twitter.common.contextutil==0.3.3'],
    'license': 'Apache License, Version 2.0',
    'long_description': 'RELEASE HISTORY\n===============\n\n0.8.1 (2/17/2015)\n-----------------\n\nBugfixes\n~~~~~~~~\n\n* Allow non-jar resources on the classpath.\n  `RB #1752 <https://rbcommons.com/s/twitter/r/1752/>`_\n\n0.8.0 (2/2/2015)\n----------------\n\nAPI Changes\n~~~~~~~~~~~\n\n* Update to ``pantsbuild.pants`` 0.0.28 api changes\n  `RB #1698 <https://rbcommons.com/s/twitter/r/1698/>`_\n\n0.7.0 (12/18/2014)\n------------------\n\nAPI Changes\n~~~~~~~~~~~\n\n* Update to ``pantsbuild.pants`` 0.0.26 api changes\n  `RB #1513 <https://rbcommons.com/s/twitter/r/1513/>`_\n\n0.6.0 (11/12/2014)\n------------------\n\nAPI Changes\n~~~~~~~~~~~\n\n* Depend on latest release ``twitter.common.*`` deps.\n  `RB #1329 <https://rbcommons.com/s/twitter/r/1329/>`_\n\n* Update to ``pantsbuild.pants`` 0.0.24 api changes\n  `RB #1071 <https://rbcommons.com/s/twitter/r/1071/>`_\n\n0.5.0 (8/11/2014)\n------------------\n\nAPI Changes\n~~~~~~~~~~~\n\n* Update to ``pantsbuild.pants`` 0.0.23 api changes\n  `RB #864 <https://rbcommons.com/s/twitter/r/864/>`_\n\n0.4.0 (7/28/2014)\n------------------\n\nAPI Changes\n~~~~~~~~~~~\n\n* Update to ``pantsbuild.pants`` 0.0.21 api changes\n  `RB #763 <https://rbcommons.com/s/twitter/r/763/>`_\n\n0.3.3 (7/21/2014)\n-----------------\n\nBugfixes\n~~~~~~~~\n\n* Loosen up t.c.pants constraints.\n  `RB #712 <https://rbcommons.com/s/twitter/r/712/>`_\n\n0.3.2 (7/18/2014)\n-----------------\n\nBugfixes\n~~~~~~~~\n\n* Maintain line set type throughout branches that populate it in the args-apt task.\n  `RB #702 <https://rbcommons.com/s/twitter/r/702/>`_\n\n0.3.1 (7/15/2014)\n-----------------\n\n* Initial published version of ``twitter.common.pants``.\n',
    'name': 'twitter.common.pants',
    'namespace_packages': ['twitter', 'twitter.common'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': [   'twitter',
                    'twitter.common',
                    'twitter.common.pants',
                    'twitter.common.pants.jvm',
                    'twitter.common.pants.jvm.args',
                    'twitter.common.pants.jvm.args.tasks'],
    'url': 'https://github.com/twitter/commons',
    'version': '0.8.1',
    'zip_safe': True}
)
