"""__init__ module for pygeprocessing, imports all the geoprocessing functions
    into the pygeoprocessing namespace"""

import unittest
import logging
import os

from pygeoprocessing.geoprocessing import *

LOGGER = logging.getLogger('pygeoprocessing')
LOGGER.setLevel(logging.DEBUG)

def test():
    """run modulewide tests"""
    LOGGER.info('running tests on %s', os.path.dirname(__file__))
    suite = unittest.TestLoader().discover(os.path.dirname(__file__))
    unittest.TextTestRunner(verbosity=2).run(suite)
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-38ff84a887c6'
py_arch = '32bit'
release = '0.1.4'
version_str = '0.1.4'
__version__ = "0.1.4.dev2"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-eeab470e6397'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-eeab470e6397'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.4.dev3"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'hotfix/0.1.5'
build_id = 'hotfix/0.1.5-72340b5601df'
py_arch = '32bit'
release = '0.1.4'
version_str = 'hotfix/0.1.5-72340b5601df'
__version__ = "0.1.5"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-1f9a40d81534'
py_arch = '32bit'
release = '0.1.5'
version_str = '0.1.5'
__version__ = "0.1.5.dev8"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'feature/get_nodata_from_uri_nodata_fix'
build_id = 'feature/get_nodata_from_uri_nodata_fix-641620b20780'
py_arch = '32bit'
release = '0.1.5'
version_str = 'feature/get_nodata_from_uri_nodata_fix-641620b20780'
__version__ = "0.1.5.dev8"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'feature/get_nodata_from_uri_nodata_fix'
build_id = 'feature/get_nodata_from_uri_nodata_fix-641620b20780'
py_arch = '32bit'
release = '0.1.5'
version_str = 'feature/get_nodata_from_uri_nodata_fix-641620b20780'
__version__ = "0.1.5.dev8"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'feature/get_nodata_from_uri_nodata_fix'
build_id = 'feature/get_nodata_from_uri_nodata_fix-641620b20780'
py_arch = '32bit'
release = '0.1.5'
version_str = 'feature/get_nodata_from_uri_nodata_fix-641620b20780'
__version__ = "0.1.5.dev9"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'feature/get_nodata_from_uri_nodata_fix'
build_id = 'feature/get_nodata_from_uri_nodata_fix-44c9abdca2c9'
py_arch = '32bit'
release = '0.1.5'
version_str = 'feature/get_nodata_from_uri_nodata_fix-44c9abdca2c9'
__version__ = "0.1.7"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-908d5099be8d'
py_arch = '32bit'
release = '0.1.7'
version_str = '0.1.7'
__version__ = "0.1.7"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-908d5099be8d'
py_arch = '32bit'
release = '0.1.7'
version_str = '0.1.7'
__version__ = "0.1.7"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-908d5099be8d'
py_arch = '32bit'
release = '0.1.7'
version_str = '0.1.7'
__version__ = "0.1.7"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-908d5099be8d'
py_arch = '32bit'
release = '0.1.7'
version_str = '0.1.7'
__version__ = "0.1.5.dev26"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'develop'
build_id = 'develop-15a04d77082a'
py_arch = '32bit'
release = '0.1.5'
version_str = 'develop-15a04d77082a'
__version__ = "0.1.8"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-81533c9a15dc'
py_arch = '32bit'
release = '0.1.8'
version_str = '0.1.8'
__version__ = "0.1.8"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-81533c9a15dc'
py_arch = '32bit'
release = '0.1.8'
version_str = '0.1.8'
__version__ = "0.1.8"
build_data = ['release', 'build_id', 'py_arch', 'branch', 'version_str']
branch = 'master'
build_id = 'master-81533c9a15dc'
py_arch = '32bit'
release = '0.1.8'
version_str = '0.1.8'
