# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspace\dev\projex\projexui\src\projexui\widgets\xrichtextedit\ui\xrichtextedit.ui'
#
# Created: Wed Dec 31 14:09:29 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(435, 253)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiFontBTN = XPopupButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default/img/richtext/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFontBTN.setIcon(icon)
        self.uiFontBTN.setAutoRaise(True)
        self.uiFontBTN.setObjectName("uiFontBTN")
        self.horizontalLayout.addWidget(self.uiFontBTN)
        self.uiBoldBTN = QtGui.QToolButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/default/img/richtext/bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBoldBTN.setIcon(icon1)
        self.uiBoldBTN.setCheckable(True)
        self.uiBoldBTN.setAutoRaise(True)
        self.uiBoldBTN.setObjectName("uiBoldBTN")
        self.horizontalLayout.addWidget(self.uiBoldBTN)
        self.uiItalicBTN = QtGui.QToolButton(Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/default/img/richtext/italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiItalicBTN.setIcon(icon2)
        self.uiItalicBTN.setCheckable(True)
        self.uiItalicBTN.setAutoRaise(True)
        self.uiItalicBTN.setObjectName("uiItalicBTN")
        self.horizontalLayout.addWidget(self.uiItalicBTN)
        self.uiUnderlineBTN = QtGui.QToolButton(Form)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/default/img/richtext/underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiUnderlineBTN.setIcon(icon3)
        self.uiUnderlineBTN.setCheckable(True)
        self.uiUnderlineBTN.setAutoRaise(True)
        self.uiUnderlineBTN.setObjectName("uiUnderlineBTN")
        self.horizontalLayout.addWidget(self.uiUnderlineBTN)
        self.uiStrikeoutBTN = QtGui.QToolButton(Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/default/img/richtext/strikethrough.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiStrikeoutBTN.setIcon(icon4)
        self.uiStrikeoutBTN.setCheckable(True)
        self.uiStrikeoutBTN.setAutoRaise(True)
        self.uiStrikeoutBTN.setObjectName("uiStrikeoutBTN")
        self.horizontalLayout.addWidget(self.uiStrikeoutBTN)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.uiUnorderedBTN = QtGui.QToolButton(Form)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/default/img/richtext/list_unordered.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiUnorderedBTN.setIcon(icon5)
        self.uiUnorderedBTN.setAutoRaise(True)
        self.uiUnorderedBTN.setObjectName("uiUnorderedBTN")
        self.horizontalLayout.addWidget(self.uiUnorderedBTN)
        self.uiOrderedBTN = QtGui.QToolButton(Form)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/default/img/richtext/list_ordered.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiOrderedBTN.setIcon(icon6)
        self.uiOrderedBTN.setAutoRaise(True)
        self.uiOrderedBTN.setObjectName("uiOrderedBTN")
        self.horizontalLayout.addWidget(self.uiOrderedBTN)
        self.uiTableBTN = QtGui.QToolButton(Form)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/default/img/richtext/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiTableBTN.setIcon(icon7)
        self.uiTableBTN.setAutoRaise(True)
        self.uiTableBTN.setObjectName("uiTableBTN")
        self.horizontalLayout.addWidget(self.uiTableBTN)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.uiAlignLeftBTN = QtGui.QToolButton(Form)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/default/img/richtext/left_align.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAlignLeftBTN.setIcon(icon8)
        self.uiAlignLeftBTN.setCheckable(True)
        self.uiAlignLeftBTN.setAutoRaise(True)
        self.uiAlignLeftBTN.setObjectName("uiAlignLeftBTN")
        self.horizontalLayout.addWidget(self.uiAlignLeftBTN)
        self.uiAlignCenterBTN = QtGui.QToolButton(Form)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/default/img/richtext/center_align.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAlignCenterBTN.setIcon(icon9)
        self.uiAlignCenterBTN.setCheckable(True)
        self.uiAlignCenterBTN.setAutoRaise(True)
        self.uiAlignCenterBTN.setObjectName("uiAlignCenterBTN")
        self.horizontalLayout.addWidget(self.uiAlignCenterBTN)
        self.uiAlignRightBTN = QtGui.QToolButton(Form)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/default/img/richtext/right_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAlignRightBTN.setIcon(icon10)
        self.uiAlignRightBTN.setCheckable(True)
        self.uiAlignRightBTN.setAutoRaise(True)
        self.uiAlignRightBTN.setObjectName("uiAlignRightBTN")
        self.horizontalLayout.addWidget(self.uiAlignRightBTN)
        self.uiAlignJustifyBTN = QtGui.QToolButton(Form)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/default/img/richtext/justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAlignJustifyBTN.setIcon(icon11)
        self.uiAlignJustifyBTN.setCheckable(True)
        self.uiAlignJustifyBTN.setAutoRaise(True)
        self.uiAlignJustifyBTN.setObjectName("uiAlignJustifyBTN")
        self.horizontalLayout.addWidget(self.uiAlignJustifyBTN)
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.uiFontColorBTN = QtGui.QToolButton(Form)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/default/img/richtext/font_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFontColorBTN.setIcon(icon12)
        self.uiFontColorBTN.setAutoRaise(True)
        self.uiFontColorBTN.setObjectName("uiFontColorBTN")
        self.horizontalLayout.addWidget(self.uiFontColorBTN)
        self.uiBackgroundColorBTN = QtGui.QToolButton(Form)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/default/img/richtext/background_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBackgroundColorBTN.setIcon(icon13)
        self.uiBackgroundColorBTN.setAutoRaise(True)
        self.uiBackgroundColorBTN.setObjectName("uiBackgroundColorBTN")
        self.horizontalLayout.addWidget(self.uiBackgroundColorBTN)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.uiFindWGT = XFindWidget(Form)
        self.uiFindWGT.setObjectName("uiFindWGT")
        self.gridLayout.addWidget(self.uiFindWGT, 2, 0, 1, 1)
        self.uiEditTXT = XTextEdit(Form)
        self.uiEditTXT.setObjectName("uiEditTXT")
        self.gridLayout.addWidget(self.uiEditTXT, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFontBTN.setToolTip(QtGui.QApplication.translate("Form", "Change Font Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBoldBTN.setToolTip(QtGui.QApplication.translate("Form", "Toggle Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBoldBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiItalicBTN.setToolTip(QtGui.QApplication.translate("Form", "Toggle Italics", None, QtGui.QApplication.UnicodeUTF8))
        self.uiItalicBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiUnderlineBTN.setToolTip(QtGui.QApplication.translate("Form", "Toggle Underline", None, QtGui.QApplication.UnicodeUTF8))
        self.uiUnderlineBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiStrikeoutBTN.setToolTip(QtGui.QApplication.translate("Form", "Toggle Strikeout", None, QtGui.QApplication.UnicodeUTF8))
        self.uiStrikeoutBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiUnorderedBTN.setToolTip(QtGui.QApplication.translate("Form", "Toggle Unordered List", None, QtGui.QApplication.UnicodeUTF8))
        self.uiUnorderedBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiOrderedBTN.setToolTip(QtGui.QApplication.translate("Form", "Toggle Ordered List", None, QtGui.QApplication.UnicodeUTF8))
        self.uiOrderedBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiTableBTN.setToolTip(QtGui.QApplication.translate("Form", "Toggle Ordered List", None, QtGui.QApplication.UnicodeUTF8))
        self.uiTableBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignLeftBTN.setToolTip(QtGui.QApplication.translate("Form", "Align Left", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignLeftBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignCenterBTN.setToolTip(QtGui.QApplication.translate("Form", "Align Center", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignCenterBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignRightBTN.setToolTip(QtGui.QApplication.translate("Form", "Align Right", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignRightBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignJustifyBTN.setToolTip(QtGui.QApplication.translate("Form", "Align Right", None, QtGui.QApplication.UnicodeUTF8))
        self.uiAlignJustifyBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFontColorBTN.setToolTip(QtGui.QApplication.translate("Form", "Font Color", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFontColorBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBackgroundColorBTN.setToolTip(QtGui.QApplication.translate("Form", "Background Color", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBackgroundColorBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))

from projexui.widgets.xtextedit import XTextEdit
from projexui.widgets.xpopupbutton import XPopupButton
from projexui.widgets.xfindwidget import XFindWidget

