
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.4'
version_full = '428424cc8b09bab98133e69bc88d0e7752b2a933'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
