# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspace\dev\projex\projexui\src\projexui\windows\xdkwindow\ui\xdkwindow.ui'
#
# Created: Wed Dec 31 14:09:29 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../resources/default/img/sdk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.uiBrowserTAB = QtGui.QTabWidget(self.splitter)
        self.uiBrowserTAB.setMinimumSize(QtCore.QSize(200, 0))
        self.uiBrowserTAB.setObjectName("uiBrowserTAB")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uiContentSearchTXT = XLineEdit(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/default/img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiContentSearchTXT.setProperty("x_icon", icon1)
        self.uiContentSearchTXT.setProperty("x_cornerRadius", 8)
        self.uiContentSearchTXT.setObjectName("uiContentSearchTXT")
        self.verticalLayout_2.addWidget(self.uiContentSearchTXT)
        self.uiContentsTREE = XTreeWidget(self.tab)
        self.uiContentsTREE.setProperty("x_arrowStyle", True)
        self.uiContentsTREE.setProperty("x_showGrid", False)
        self.uiContentsTREE.setObjectName("uiContentsTREE")
        self.verticalLayout_2.addWidget(self.uiContentsTREE)
        self.uiBrowserTAB.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.uiIndexTXT = XLineEdit(self.tab_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../resources/default/img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiIndexTXT.setProperty("x_icon", icon2)
        self.uiIndexTXT.setProperty("x_cornerRadius", 8)
        self.uiIndexTXT.setObjectName("uiIndexTXT")
        self.gridLayout_2.addWidget(self.uiIndexTXT, 0, 0, 1, 1)
        self.uiIndexTREE = XTreeWidget(self.tab_2)
        self.uiIndexTREE.setAlternatingRowColors(True)
        self.uiIndexTREE.setRootIsDecorated(False)
        self.uiIndexTREE.setProperty("x_showGridColumns", False)
        self.uiIndexTREE.setObjectName("uiIndexTREE")
        self.gridLayout_2.addWidget(self.uiIndexTREE, 1, 0, 1, 1)
        self.uiBrowserTAB.addTab(self.tab_2, "")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiContentsTAB = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.uiContentsTAB.sizePolicy().hasHeightForWidth())
        self.uiContentsTAB.setSizePolicy(sizePolicy)
        self.uiContentsTAB.setTabsClosable(True)
        self.uiContentsTAB.setObjectName("uiContentsTAB")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiSearchLBL = QtGui.QLabel(self.tab_3)
        self.uiSearchLBL.setObjectName("uiSearchLBL")
        self.horizontalLayout.addWidget(self.uiSearchLBL)
        self.uiSearchTXT = QtGui.QLineEdit(self.tab_3)
        self.uiSearchTXT.setObjectName("uiSearchTXT")
        self.horizontalLayout.addWidget(self.uiSearchTXT)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.uiSearchFRAME = QtGui.QFrame(self.tab_3)
        self.uiSearchFRAME.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uiSearchFRAME.setFrameShadow(QtGui.QFrame.Raised)
        self.uiSearchFRAME.setObjectName("uiSearchFRAME")
        self.gridLayout_5 = QtGui.QGridLayout(self.uiSearchFRAME)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.uiSearchWEB = QtWebKit.QWebView(self.uiSearchFRAME)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchWEB.sizePolicy().hasHeightForWidth())
        self.uiSearchWEB.setSizePolicy(sizePolicy)
        self.uiSearchWEB.setUrl(QtCore.QUrl("about:blank"))
        self.uiSearchWEB.setObjectName("uiSearchWEB")
        self.gridLayout_5.addWidget(self.uiSearchWEB, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.uiSearchFRAME, 1, 0, 1, 1)
        self.uiContentsTAB.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.uiContentsTAB)
        self.uiFindWIDGET = QtGui.QWidget(self.layoutWidget)
        self.uiFindWIDGET.setObjectName("uiFindWIDGET")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.uiFindWIDGET)
        self.horizontalLayout_2.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiFindCloseBTN = QtGui.QToolButton(self.uiFindWIDGET)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../resources/default/img/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFindCloseBTN.setIcon(icon3)
        self.uiFindCloseBTN.setAutoRaise(True)
        self.uiFindCloseBTN.setObjectName("uiFindCloseBTN")
        self.horizontalLayout_2.addWidget(self.uiFindCloseBTN)
        self.uiFindTXT = QtGui.QLineEdit(self.uiFindWIDGET)
        self.uiFindTXT.setObjectName("uiFindTXT")
        self.horizontalLayout_2.addWidget(self.uiFindTXT)
        self.uiFindPrevBTN = QtGui.QToolButton(self.uiFindWIDGET)
        self.uiFindPrevBTN.setAutoRaise(True)
        self.uiFindPrevBTN.setObjectName("uiFindPrevBTN")
        self.horizontalLayout_2.addWidget(self.uiFindPrevBTN)
        self.uiFindNextBTN = QtGui.QToolButton(self.uiFindWIDGET)
        self.uiFindNextBTN.setAutoRaise(True)
        self.uiFindNextBTN.setObjectName("uiFindNextBTN")
        self.horizontalLayout_2.addWidget(self.uiFindNextBTN)
        self.uiCaseSensitiveCHK = QtGui.QCheckBox(self.uiFindWIDGET)
        self.uiCaseSensitiveCHK.setObjectName("uiCaseSensitiveCHK")
        self.horizontalLayout_2.addWidget(self.uiCaseSensitiveCHK)
        self.verticalLayout.addWidget(self.uiFindWIDGET)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 21))
        self.menubar.setObjectName("menubar")
        self.uiFileMENU = QtGui.QMenu(self.menubar)
        self.uiFileMENU.setObjectName("uiFileMENU")
        self.uiEditMENU = QtGui.QMenu(self.menubar)
        self.uiEditMENU.setObjectName("uiEditMENU")
        self.uiViewMENU = QtGui.QMenu(self.menubar)
        self.uiViewMENU.setObjectName("uiViewMENU")
        self.uiGoMENU = QtGui.QMenu(self.menubar)
        self.uiGoMENU.setObjectName("uiGoMENU")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.uiLoadACT = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/default/img/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiLoadACT.setIcon(icon4)
        self.uiLoadACT.setObjectName("uiLoadACT")
        self.uiNewTabACT = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/default/img/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNewTabACT.setIcon(icon5)
        self.uiNewTabACT.setObjectName("uiNewTabACT")
        self.uiCloseTabACT = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/default/img/remove_dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCloseTabACT.setIcon(icon6)
        self.uiCloseTabACT.setObjectName("uiCloseTabACT")
        self.uiQuitACT = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/default/img/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiQuitACT.setIcon(icon7)
        self.uiQuitACT.setObjectName("uiQuitACT")
        self.uiFindACT = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/default/img/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFindACT.setIcon(icon8)
        self.uiFindACT.setObjectName("uiFindACT")
        self.uiFindNextACT = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../resources/default/img/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFindNextACT.setIcon(icon9)
        self.uiFindNextACT.setObjectName("uiFindNextACT")
        self.uiFindPrevACT = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../resources/default/img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFindPrevACT.setIcon(icon10)
        self.uiFindPrevACT.setObjectName("uiFindPrevACT")
        self.uiZoomInACT = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/default/img/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiZoomInACT.setIcon(icon11)
        self.uiZoomInACT.setObjectName("uiZoomInACT")
        self.uiZoomOutACT = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/default/img/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiZoomOutACT.setIcon(icon12)
        self.uiZoomOutACT.setObjectName("uiZoomOutACT")
        self.uiZoomResetACT = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/default/img/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiZoomResetACT.setIcon(icon13)
        self.uiZoomResetACT.setObjectName("uiZoomResetACT")
        self.uiHomeACT = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/default/img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiHomeACT.setIcon(icon14)
        self.uiHomeACT.setObjectName("uiHomeACT")
        self.uiBackACT = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/default/img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBackACT.setIcon(icon15)
        self.uiBackACT.setObjectName("uiBackACT")
        self.uiForwardACT = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/default/img/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiForwardACT.setIcon(icon16)
        self.uiForwardACT.setObjectName("uiForwardACT")
        self.uiCopyTextACT = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/default/img/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCopyTextACT.setIcon(icon17)
        self.uiCopyTextACT.setObjectName("uiCopyTextACT")
        self.uiFileMENU.addAction(self.uiLoadACT)
        self.uiFileMENU.addSeparator()
        self.uiFileMENU.addAction(self.uiNewTabACT)
        self.uiFileMENU.addAction(self.uiCloseTabACT)
        self.uiFileMENU.addSeparator()
        self.uiFileMENU.addAction(self.uiQuitACT)
        self.uiEditMENU.addAction(self.uiCopyTextACT)
        self.uiEditMENU.addSeparator()
        self.uiEditMENU.addAction(self.uiFindACT)
        self.uiEditMENU.addAction(self.uiFindNextACT)
        self.uiEditMENU.addAction(self.uiFindPrevACT)
        self.uiViewMENU.addAction(self.uiZoomInACT)
        self.uiViewMENU.addAction(self.uiZoomOutACT)
        self.uiViewMENU.addAction(self.uiZoomResetACT)
        self.uiGoMENU.addAction(self.uiHomeACT)
        self.uiGoMENU.addAction(self.uiBackACT)
        self.uiGoMENU.addAction(self.uiForwardACT)
        self.menubar.addAction(self.uiFileMENU.menuAction())
        self.menubar.addAction(self.uiEditMENU.menuAction())
        self.menubar.addAction(self.uiViewMENU.menuAction())
        self.menubar.addAction(self.uiGoMENU.menuAction())
        self.toolBar.addAction(self.uiBackACT)
        self.toolBar.addAction(self.uiForwardACT)
        self.toolBar.addAction(self.uiHomeACT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiCopyTextACT)
        self.toolBar.addAction(self.uiFindACT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiZoomInACT)
        self.toolBar.addAction(self.uiZoomOutACT)
        self.toolBar.addAction(self.uiZoomResetACT)

        self.retranslateUi(MainWindow)
        self.uiBrowserTAB.setCurrentIndex(0)
        self.uiContentsTAB.setCurrentIndex(0)
        QtCore.QObject.connect(self.uiContentSearchTXT, QtCore.SIGNAL("textChanged(QString)"), self.uiContentsTREE.filterItems)
        QtCore.QObject.connect(self.uiIndexTXT, QtCore.SIGNAL("textChanged(QString)"), self.uiIndexTREE.filterItems)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "XDK Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.uiContentSearchTXT.setProperty("x_hint", QtGui.QApplication.translate("MainWindow", "filter contents", None, QtGui.QApplication.UnicodeUTF8))
        self.uiContentsTREE.setProperty("x_hint", QtGui.QApplication.translate("MainWindow", "No XDK files have been loaded.", None, QtGui.QApplication.UnicodeUTF8))
        self.uiContentsTREE.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBrowserTAB.setTabText(self.uiBrowserTAB.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.uiIndexTXT.setProperty("x_hint", QtGui.QApplication.translate("MainWindow", "filter index", None, QtGui.QApplication.UnicodeUTF8))
        self.uiIndexTREE.setProperty("x_hint", QtGui.QApplication.translate("MainWindow", "No XDK files have been loaded.", None, QtGui.QApplication.UnicodeUTF8))
        self.uiIndexTREE.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBrowserTAB.setTabText(self.uiBrowserTAB.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.uiSearchLBL.setText(QtGui.QApplication.translate("MainWindow", "Search for:", None, QtGui.QApplication.UnicodeUTF8))
        self.uiContentsTAB.setTabText(self.uiContentsTAB.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindCloseBTN.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindPrevBTN.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindNextBTN.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCaseSensitiveCHK.setText(QtGui.QApplication.translate("MainWindow", "Case Sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFileMENU.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.uiEditMENU.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.uiViewMENU.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGoMENU.setTitle(QtGui.QApplication.translate("MainWindow", "&Go", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Navigation Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.uiLoadACT.setText(QtGui.QApplication.translate("MainWindow", "Open XDK File...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiLoadACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.uiNewTabACT.setText(QtGui.QApplication.translate("MainWindow", "&New Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.uiNewTabACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCloseTabACT.setText(QtGui.QApplication.translate("MainWindow", "&Close Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCloseTabACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQuitACT.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQuitACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindACT.setText(QtGui.QApplication.translate("MainWindow", "Find in Text", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindNextACT.setText(QtGui.QApplication.translate("MainWindow", "Find Next", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindNextACT.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindPrevACT.setText(QtGui.QApplication.translate("MainWindow", "Find Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindPrevACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F3", None, QtGui.QApplication.UnicodeUTF8))
        self.uiZoomInACT.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.uiZoomInACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl++", None, QtGui.QApplication.UnicodeUTF8))
        self.uiZoomOutACT.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.uiZoomOutACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.uiZoomResetACT.setText(QtGui.QApplication.translate("MainWindow", "Normal Size", None, QtGui.QApplication.UnicodeUTF8))
        self.uiZoomResetACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+0", None, QtGui.QApplication.UnicodeUTF8))
        self.uiHomeACT.setText(QtGui.QApplication.translate("MainWindow", "&Home", None, QtGui.QApplication.UnicodeUTF8))
        self.uiHomeACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Home", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBackACT.setText(QtGui.QApplication.translate("MainWindow", "&Back", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBackACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.uiForwardACT.setText(QtGui.QApplication.translate("MainWindow", "&Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.uiForwardACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCopyTextACT.setText(QtGui.QApplication.translate("MainWindow", "Copy selected Text", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCopyTextACT.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
from projexui.widgets.xtreewidget import XTreeWidget
from projexui.widgets.xlineedit import XLineEdit

