# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspace\dev\projex\projexui\src\projexui\widgets\xorbrecordsetedit\ui\xorbrecordsetedit.ui'
#
# Created: Wed Dec 31 14:09:29 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 402)
        Form.setMinimumSize(QtCore.QSize(400, 400))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiFindAllCHK = QtGui.QRadioButton(Form)
        self.uiFindAllCHK.setObjectName("uiFindAllCHK")
        self.verticalLayout.addWidget(self.uiFindAllCHK)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiQueryCHK = QtGui.QRadioButton(Form)
        self.uiQueryCHK.setChecked(True)
        self.uiQueryCHK.setObjectName("uiQueryCHK")
        self.horizontalLayout.addWidget(self.uiQueryCHK)
        self.uiQueryTXT = XLineEdit(Form)
        self.uiQueryTXT.setObjectName("uiQueryTXT")
        self.horizontalLayout.addWidget(self.uiQueryTXT)
        self.uiQueryBTN = QtGui.QToolButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default/img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiQueryBTN.setIcon(icon)
        self.uiQueryBTN.setCheckable(True)
        self.uiQueryBTN.setChecked(True)
        self.uiQueryBTN.setAutoRaise(True)
        self.uiQueryBTN.setObjectName("uiQueryBTN")
        self.horizontalLayout.addWidget(self.uiQueryBTN)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.uiQueryTREE = XTreeWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.uiQueryTREE.sizePolicy().hasHeightForWidth())
        self.uiQueryTREE.setSizePolicy(sizePolicy)
        self.uiQueryTREE.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.uiQueryTREE.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.uiQueryTREE.setIndentation(10)
        self.uiQueryTREE.setObjectName("uiQueryTREE")
        self.verticalLayout.addWidget(self.uiQueryTREE)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uiGroupingLBL = QtGui.QLabel(Form)
        self.uiGroupingLBL.setMinimumSize(QtCore.QSize(90, 0))
        self.uiGroupingLBL.setObjectName("uiGroupingLBL")
        self.horizontalLayout_4.addWidget(self.uiGroupingLBL)
        self.uiGroupingTXT = XLineEdit(Form)
        self.uiGroupingTXT.setObjectName("uiGroupingTXT")
        self.horizontalLayout_4.addWidget(self.uiGroupingTXT)
        self.uiGroupingBTN = QtGui.QToolButton(Form)
        self.uiGroupingBTN.setIcon(icon)
        self.uiGroupingBTN.setCheckable(True)
        self.uiGroupingBTN.setAutoRaise(True)
        self.uiGroupingBTN.setObjectName("uiGroupingBTN")
        self.horizontalLayout_4.addWidget(self.uiGroupingBTN)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uiSortingLBL = QtGui.QLabel(Form)
        self.uiSortingLBL.setMinimumSize(QtCore.QSize(90, 0))
        self.uiSortingLBL.setObjectName("uiSortingLBL")
        self.horizontalLayout_3.addWidget(self.uiSortingLBL)
        self.uiSortingTXT = XLineEdit(Form)
        self.uiSortingTXT.setObjectName("uiSortingTXT")
        self.horizontalLayout_3.addWidget(self.uiSortingTXT)
        self.uiSortingBTN = QtGui.QToolButton(Form)
        self.uiSortingBTN.setIcon(icon)
        self.uiSortingBTN.setCheckable(True)
        self.uiSortingBTN.setAutoRaise(True)
        self.uiSortingBTN.setObjectName("uiSortingBTN")
        self.horizontalLayout_3.addWidget(self.uiSortingBTN)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiPagedCHK = QtGui.QCheckBox(Form)
        self.uiPagedCHK.setMinimumSize(QtCore.QSize(90, 0))
        self.uiPagedCHK.setObjectName("uiPagedCHK")
        self.horizontalLayout_2.addWidget(self.uiPagedCHK)
        self.uiPagedSPN = QtGui.QSpinBox(Form)
        self.uiPagedSPN.setMaximum(10000)
        self.uiPagedSPN.setProperty("value", 100)
        self.uiPagedSPN.setObjectName("uiPagedSPN")
        self.horizontalLayout_2.addWidget(self.uiPagedSPN)
        self.uiPagedLBL = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPagedLBL.sizePolicy().hasHeightForWidth())
        self.uiPagedLBL.setSizePolicy(sizePolicy)
        self.uiPagedLBL.setObjectName("uiPagedLBL")
        self.horizontalLayout_2.addWidget(self.uiPagedLBL)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.uiQueryCHK, QtCore.SIGNAL("toggled(bool)"), self.uiQueryTXT.setEnabled)
        QtCore.QObject.connect(self.uiQueryCHK, QtCore.SIGNAL("toggled(bool)"), self.uiQueryTREE.setEnabled)
        QtCore.QObject.connect(self.uiQueryBTN, QtCore.SIGNAL("toggled(bool)"), self.uiQueryTREE.setVisible)
        QtCore.QObject.connect(self.uiQueryCHK, QtCore.SIGNAL("toggled(bool)"), self.uiQueryBTN.setEnabled)
        QtCore.QObject.connect(self.uiPagedCHK, QtCore.SIGNAL("toggled(bool)"), self.uiPagedSPN.setEnabled)
        QtCore.QObject.connect(self.uiPagedCHK, QtCore.SIGNAL("toggled(bool)"), self.uiPagedLBL.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.uiFindAllCHK.setText(QtGui.QApplication.translate("Form", "Find every record", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryCHK.setText(QtGui.QApplication.translate("Form", "Filtered where", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryTREE.headerItem().setText(0, QtGui.QApplication.translate("Form", "Join", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryTREE.headerItem().setText(1, QtGui.QApplication.translate("Form", "Column", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryTREE.headerItem().setText(2, QtGui.QApplication.translate("Form", "Operator", None, QtGui.QApplication.UnicodeUTF8))
        self.uiQueryTREE.headerItem().setText(3, QtGui.QApplication.translate("Form", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGroupingLBL.setText(QtGui.QApplication.translate("Form", "Grouped by: ", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGroupingBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiSortingLBL.setText(QtGui.QApplication.translate("Form", "Sorted by: ", None, QtGui.QApplication.UnicodeUTF8))
        self.uiSortingBTN.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiPagedCHK.setText(QtGui.QApplication.translate("Form", "Paged every", None, QtGui.QApplication.UnicodeUTF8))
        self.uiPagedLBL.setText(QtGui.QApplication.translate("Form", "results", None, QtGui.QApplication.UnicodeUTF8))

from projexui.widgets.xtreewidget import XTreeWidget
from projexui.widgets.xlineedit import XLineEdit

