__version__ = "0.2.6"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '2c88dcc165471595e52e52b8514d1716f6e0a76b'
__git_head_subject__ = 'Finished release v0.2.6.'
__git_head_message__ = '* release/v0.2.6:\n  TRIVIAL refactoring for readability\n  TRIVIAL dry_run\n  HOSTDEV-1940\n  jirelnotes fixes\n  other-versions-included-in-this-releases\n  TRIVIAL also notify clones'
__git_dirty_diff__ = ''