
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.0b7'
version_full = 'e9e6c78a346896e2ccccce1a5689f787ccfd79a9'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

