
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.4'
version_full = 'e7753d32a0cdd84f708ea786d2e77fba914ad737'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

