'''
This file contains the condition configuration.
'''

CONDITIONS = [
    Condition('Circe', 'Circe'),
    Condition('Spiegelcirce', 'SpiegelCirce'),
    Condition('Madrasi', 'Madrasi'),
    Condition('Volage', 'Volage'),
    Condition('Hypervolage', 'Hypervolage'),
    Condition('Bichromes-Schach', 'BichromesSchach'),
    Condition('Monochromes-Schach', 'MonochromesSchach'),
    Condition('Gitterschach', 'Gitterschach', gridchess_problem_action),
    Condition('K\\"oKo', 'KoeKo'),
    Condition('Schwarzer-Randz\\"uger', 'SchwarzerRandzueger'),
    Condition('Weisser-Randz\\"uger', 'WeisserRandzueger'),
    Condition('Leofamily', 'Leofamily'),
    Condition('Chinesisches-Schach', 'ChinesischesSchach'),
    Condition('Patrouilleschach', 'PatrouilleSchach'),
    Condition('Platzwechselcirce', 'PlatzwechselCirce'),
    Condition('Ohneschlag', 'Ohneschlag'),
    Condition('Immunschach', 'Immunschach'),
    Condition('Spiegel-Immun-Schach', 'SpiegelImmunSchach'),
    Condition('Kontaktgitter', 'KontaktGitter'),
    # Condition('Imitator', 'Imitator'),
    Condition('Cavalier-Majeur', 'CavalierMajeur'),
    Condition('Haaner-Schach', 'HaanerSchach'),
    Condition('Couscous-Circe', 'CouscousCirce'),
    # Condition('Chamaeleon-Circe', 'ChamaeleonCirce'),
    Condition('Equipollents-Circe', 'EquipollentsCirce'),
    Condition('File-Circe', 'FileCirce'),
    Condition('Sentinelles', 'Sentinelles'),
    Condition('Schwarzer-L\\"angstz\\"uger', 'SchwarzerLaengstzueger'),
    Condition('Schwarzer-K\\"urzestz\\"uger', 'SchwarzerKuerzestzueger'),
    Condition('Weisser-L\\"angstz\\"uger', 'WeisserLaengstzueger'),
    Condition('Weisser-K\\"urzestz\\"uger', 'WeisserKuerzestzueger'),
    # Condition('Magische-Felder', 'MagischeFelder'),
    Condition('Diagrammcirce', 'DiagrammCirce'),
    Condition('Tibetschach', 'TibetSchach'),
    Condition('Doppel-Tibetschach', 'DoppelTibetSchach'),
    # Condition('Loch', 'Loch'),
    Condition('Schwarzer-Schlagzwang', 'SchwarzerSchlagzwang'),
    Condition('Weisser-Schlagzwang', 'WeisserSchlagzwang'),
    Condition('Transmutierende-K\\"onige', 'TransmutierendeKoenige'),
    Condition('Schwarzer-Verfolgungsz\\"uger', 'SchwarzerVerfolgungszueger'),
    Condition('Weisser-Verfolgungsz\\"uger', 'WeisserVerfolgungszueger'),
    Condition('Duellantenschach', 'DuellantenSchach'),
    Condition('Circe-Parrain', 'CirceParrain'),
    Condition('Kontra-Parrain', 'KontraParrain'),
    Condition('Symmetriecirce', 'SymmetrieCirce'),
    Condition('OhneIUW', 'OhneIUW'),
    Condition('Vogtl\\"ander-Schach', 'VogtlaenderSchach'),
    Condition('Anticirce', 'AntiCirce'),
    Condition('Spiegel-File-Circe', 'SpiegelFileCirce'),
    Condition('Antipoden-Circe', 'AntipodenCirce'),
    Condition('Spiegelcirceclone', 'SpiegelCirceclone'),
    Condition('Anti-Spiegelcirce', 'AntiSpiegelCirce'),
    Condition('Anti-Diagrammcirce', 'AntiDiagrammCirce'),
    Condition('Anti-File-Circe', 'AntiFileCirce'),
    Condition('Anti-Symmetriecirce', 'AntiSymmetrieCirce'),
    Condition('Anti-Spiegel-File-Circe', 'AntiSpiegelFileCirce'),
    Condition('Anti-Antipoden-Circe', 'AntiAntipodenCirce'),
    Condition('Anti-Equipollents-Circe', 'AntiEquipollentsCirce'),
    Condition('File-Immunschach', 'FileImmunSchach'),
    Condition('Diagramm-Immunschach', 'DiagrammImmunSchach'),
    Condition('Spiegel-File-Immunschach', 'SpiegelFileImmunSchach'),
    Condition('Symmetrie-Immunschach', 'SymmetrieImmunSchach'),
    Condition('Antipoden-Immunschach', 'AntipodenImmunSchach'),
    Condition('Equipollents-Immunschach', 'EquipollentsImmunSchach'),
    Condition('K\\"afig-Immunschach', 'KaefigImmunSchach'),
    Condition('Supercirce', 'SuperCirce'),
    Condition('Reverses-Einstein-Schach', 'ReversesEinsteinSchach'),
    Condition('Degradierung', 'Degradierung'),
    Condition('Norsk-Sjakk', 'NorskSjakk'),
    Condition('Traitor-Chess', 'TraitorChess'),
    Condition('Andernachschach', 'AndernachSchach'),
    # Condition('Schwarzes-Zwangsfeld', 'SchwarzesZwangsfeld'),
    # Condition('Weisses-Zwangsfeld', 'WeissesZwangsfeld'),
    # Condition('Schwarzes-Konsequentes-Zwangsfeld', 'SchwarzesKonsequentesZwangsfeld'),
    # Condition('Weisses-Konsequentes-Zwangsfeld', 'WeissesKonsequentesZwangsfeld'),
    Condition('Bicolores', 'Bicolores'),
    Condition('Circe-Clone', 'CirceClone'),
    Condition('Einsteinschach', 'EinsteinSchach'),
    Condition('Neu-K\\"oko', 'NeuKoeko'),
    Condition('Reflektierende-K\\"onige', 'ReflektierendeKoenige'),
    # Condition('RexInklusive', 'RexInklusive'),
    Condition('Chamaeleonschach', 'ChamaeleonSchach'),
    Condition('Beamtenschach', 'BeamtenSchach'),
    Condition('Glasgow-Schach', 'GlasgowSchach'),
    Condition('Anti-Andernachschach', 'AntiAndernachSchach'),
    # Condition('Frischauf-Circe', 'FrischaufCirce'),
    Condition('Vertikales-Spiegelcirce', 'VertikalesSpiegelCirce'),
    Condition('Isardam', 'Isardam'),
    Condition('Ohneschach', 'Ohneschach'),
    Condition('Diametral-Circe', 'DiametralCirce'),
    # Condition('UWnur', 'UWnur'),
    Condition('Exklusiv-Schach', 'ExklusivSchach'),
    Condition('Marscirce', 'Marscirce'),
    Condition('Mars-Spiegelcirce', 'MarsSpiegelCirce'),
    Condition('Phantom-Schach', 'PhantomSchach'),
    Condition('Weisser-transmutierender-K\\"onig', 'WeisserTransmutierenderKoenig'),
    Condition('Schwarzer-transmutierender-K\\"onig', 'SchwarzerTransmutierenderKoenig'),
    Condition('Weisser-Reflektierender-K\\"onig', 'WeisserReflektierenderKoenig'),
    Condition('Schwarzer-Reflektierender-K\\"onig', 'SchwarzerReflektierenderKoenig'),
    Condition('Anti-Einsteinschach', 'AntiEinsteinSchach'),
    Condition('Spiegel-Couscous-Circe', 'SpiegelCouscousCirce'),
    Condition('Schwarzes-k\\"onigliches-Feld', 'SchwarzesKoeniglichesFeld'),
    Condition('Weisses-k\\"onigliches-Feld', 'WeissesKoeniglichesFeld'),
    Condition('Assassin-Circe', 'AssassinCirce'),
    Condition('Plus-Schach', 'PlusSchach'),
    Condition('Brunner-Schach', 'BrunnerSchach'),
    Condition('Zentralschach', 'ZentralSchach'),
    Condition('Ausrottungsschach', 'AusrottungsSchach'),
    Condition('Republikanerschach', 'RepublikanerSchach'),
    Condition('Actuated-Revolving-Board', 'ActuatedRevolvingBoard'),
    Condition('Messigny-Schach', 'MessignySchach'),
    Condition('Woozles', 'Woozles'),
    Condition('Bi-Woozles', 'BiWoozles'),
    Condition('Heffalumps', 'Heffalumps'),
    Condition('Bi-Heffalumps', 'BiHeffalumps'),
    # Condition('UWFeld-Weiss', 'UWFeldWeiss'),
    # Condition('UWFeld-Schwarz', 'UWFeldSchwarz'),
    Condition('Ohne-Weiss-UW', 'OhneWeissUW'),
    Condition('Ohne-Schwarz-UW', 'OhneSchwarzUW'),
    Condition('Eiffel-Schach', 'EiffelSchach'),
    Condition('Actuated-Revolving-Centre', 'ActuatedRevolvingCentre'),
    Condition('L\\"angstz\\"uger', 'Laengstzueger'),
    Condition('Ultra-Schachzwang', 'UltraSchachZwang'),
    Condition('Weisser-Ultra-Schachzwang', 'WeisserUltraSchachZwang'),
    Condition('Schwarzer-Ultra-Schachzwang', 'SchwarzerUltraSchachZwang'),
    Condition('Schutzk\\"onige', 'Schutzkoenige'),
    Condition('Sting-Schach', 'StingSchach'),
    Condition('weisser-Ohneschlag', 'WeisserOhneschlag'),
    Condition('schwarzer-Ohneschlag', 'SchwarzerOhneschlag'),
    Condition('Aprilschach', 'AprilSchach'),
    Condition('Alphabetisches-Schach', 'AlphabetischesSchach'),
    Condition('Linien-Chamaeleon-Schach', 'LinienChamaeleonSchach'),
    Condition('Turncoat-Circe', 'TurncoatCirce'),
    Condition('Doppel-Agenten-Circe', 'DoppelAgentenCirce'),
    Condition('AMU', 'AMU'),
    Condition('Nur-Partiesatzsteine', 'NurPartiesatzsteine'),
    Condition('MAFF', 'MAFF'),
    Condition('OWU', 'OWU'),
    Condition('Weisse-oszillierende-K\\"onige', 'WeisseOszillierendeKoenige'),
    Condition('Schwarze-oszillierende-K\\"onige', 'SchwarzeOszillierendeKoenige'),
    Condition('Anti-K\\"onige', 'AntiKoenige'),
    Condition('Anti-Mars-Circe', 'AntiMarsCirce'),
    Condition('Anti-Mars-Malefique-Circe', 'AntiMarsMalefiqueCirce'),
    Condition('Anti-Mars-Antipodean-Circe', 'AntiMarsAntipodeanCirce'),
    Condition('Weisser-Super-Transmutierender-K\\"onig', 'WeisserSuperTransmutierenderKoenig'),
    Condition('Schwarzer-Super-Transmutierender-K\\"onig', 'SchwarzerSuperTransmutierenderKoenig'),
    Condition('Anti-Super-Circe', 'AntiSuperCirce'),
    Condition('Ultra-Patrouille', 'UltraPatrouille'),
    Condition('Tausch-K\\"onige', 'TauschKoenige'),
    Condition('K\\"onigs-Dynastie', 'KoenigsDynastie'),
    Condition('SAT', 'SAT'),
    Condition('Strict-SAT', 'StrictSAT'),
    Condition('Take\\&Make-Schach', 'Take&MakeSchach'),
    Condition('schwarzer-Synchron-Z\\"uger', 'SchwarzerSynchronZueger'),
    Condition('Weisser-Synchron-Z\\"uger', 'WeisserSynchronZueger'),
    Condition('Schwarzer-Anti-Synchron-Z\\"uger', 'SchwarzerAntiSynchronZueger'),
    Condition('Weisser-Anti-Synchron-Z\\"uger', 'WeisserAntiSynchronZueger'),
    Condition('Masand', 'Masand'),
    Condition('BGL', 'BGL'),
    Condition('Annan-Schach', 'AnnanSchach'),
    Condition('Normalbauern', 'NormalBauern'),
    Condition('Schwarz-Sch\\"acher', 'SchwarzSchaecher'),
    Condition('Genfer-Schach', 'GenferSchach'),
    Condition('Vaulting-Kings', 'VaultingKings'),
    Condition('Weisser-Vaulting-King', 'WeisserVaultingKing'),
    Condition('Schwarzer-Vaulting-King', 'SchwarzerVaultingKing'),
    Condition('Proteisches-Schach', 'ProteischesSchach'),
    Condition('Elliuortap', 'Elliuortap'),
    Condition('Chamaeleon-Verfolgung', 'ChamaeleonVerfolgung'),
    Condition('Anti-K\\"oko', 'AntiKoeko'),
    Condition('Rochade-Schach', 'RochadeSchach'),
    Condition('Schlagschach', 'Schlagschach'),
    Condition('Geisterschach', 'Geisterschach'),
    Condition('K\\"afig-Circe', 'KaefigCirce'),
    Condition('Fussball', 'Fussball'),
    Condition('Weisses-Alphabetisches-Schach', 'WeissesAlphabetischesSchach'),
    Condition('Schwarzes-Alphabetisches-Schach', 'SchwarzesAlphabetischesSchach'),
    Condition('Kobul-K\\"onige', 'KobulKoenige'),
    Condition('Vertikal-Zylinder', None, verticalcylinder_problem_action),
    Condition('Horizontal-Zylinder', None, horizontalcylinder_problem_action),
]


