#!/usr/bin/env python
"""
Copyright 2012 GroupDocs.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class SignatureSignFieldSettingsInfo:
    """
    
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'fieldType': 'int',
            'data': 'str',
            'minGraphSizeW': 'int',
            'minGraphSizeH': 'int',
            'locations': 'list[SignatureSignFieldLocationSettingsInfo]'

        }


        self.fieldType = None # int
        self.data = None # str
        self.minGraphSizeW = None # int
        self.minGraphSizeH = None # int
        self.locations = None # list[SignatureSignFieldLocationSettingsInfo]
        
