INSTALLED_APPS = (
    'oauth_tokens',
    'taggit',
    'odnoklassniki_api',
    'odnoklassniki_groups',
    'odnoklassniki_users',
)

OAUTH_TOKENS_ODNOKLASSNIKI_CLIENT_ID =
OAUTH_TOKENS_ODNOKLASSNIKI_CLIENT_PUBLIC =
OAUTH_TOKENS_ODNOKLASSNIKI_CLIENT_SECRET =
OAUTH_TOKENS_ODNOKLASSNIKI_SCOPE = ['VALUABLE_ACCESS']
OAUTH_TOKENS_ODNOKLASSNIKI_USERNAME =
OAUTH_TOKENS_ODNOKLASSNIKI_PASSWORD =
