
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.0-21-g3038804'
version_full = '303880437982347a30ecd423770d234c311e3f7f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

