
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.0'
version_full = '9940e4d9b182530c1b35e3c0561bf4baf8609852'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

