
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.1'
version_full = 'a2eb928a32432233ca51d5be3209b8a469e46c18'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

